### ISSUE TITLE
RulerShell loses special keys after sending it to the background

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#1]
After sending the RulerShell to the background (via CTRL-Z) and the pulling it back to foreground (fg) it fails to recognize special keys like `arrow up` or `esc` and instead prints `^[[A` or `^[`

![screen shot 2015-01-16 at 2 25 04 pm](https://cloud.githubusercontent.com/assets/4502559/5784667/8b14b2c6-9d8b-11e4-90cf-ddb066d07c0c.png)

**Comment by myedibleenso** [comment]
I'm going to label this one as `wontfix` and close it.  Given the behavior of `sbt` which uses Jline, it can be done, but this is too low of a priority atm.  For the time being, just keep the shell running in a `tmux` session.
