### ISSUE TITLE
All Mentions should have context (proposal)

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#107]
Currently it seems only Mentions with the label "Event" have associated context, but coupling all Mention with context has the potential to improve at least three components of REACH: 

1. grounding
  - grounding could use species information to narrow or refine search
2. coreference 
  - improved grounding means better coreference resolution
  - coref could make direct use of contextual information (ex. species) to better resolve Mentions
3. assembly
 - improvements to either grounding or coreference improve assembly

Is there a reason not to associate some context with each `Mention`?

**Comment by MihaiSurdeanu** [comment]
Assign context to Event and Entity (see taxonomy).

**Comment by enoriega** [comment]
Implemented. See pull request #132
