### ISSUE TITLE
case insensitive string comparison

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#11]
If we want to match a token ignoring case we have to use a regular expression: `/(?i)token/`

There should be an easier way to do it.

One option is prepending the character `i` to the quotes, like: `i"token"`, which would compare the string ignoring case and should be cheaper than a full-blown regular expression.

**Comment by myedibleenso** [comment]
Closing this as it is an `Odin` issue.  

We can reopen in [`processors`](https://github.com/clulab/processors/issues) if needed.
