### ISSUE TITLE
Context should not return species context for species not in the papers

### ISSUE THREAD

**Issue by hickst** [clulab/reach#116]
Context is attaching spurious species IDs to many of the mentions; most of them are for Chrysanthemum flowers (taxonomy:41568) which are not found in these papers. This is causing unnecessary extra work for Grounding which dutifully checks those against the mention's candidate species and then, since they never match, preferentially selects the human grounding.

**Comment by MihaiSurdeanu** [comment]
@enoriega: can you verify these situations? Tom: do you have a concrete sentence/paragraph where this happens?

**Comment by enoriega** [comment]
Yes. I think "mum" makes a false positive:

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?lvl=0&id=41568

I'll remove that entry from bio resources if that's the case

**Comment by hickst** [comment]
I wouldn't remove anything from bio resources until we understand the problem completely. The example given is not the only false ID that I've gotten back from Context: only the most prevalent.

So where is 'mum' coming from? If I grep for 'mum' within PMC88976.nxml, for example, the only hit is the line:
        ```minimum significance level of p &#8804; 0.05. Student's```
But PMC88976 has 39 instances of attached Species context 41568.
That implies to me that 'mum' is not the problem and that there is some other problem that we need to understand.

**Comment by enoriega** [comment]
Yeah. I will remove it only if that's the cause but that was my first guess

**Comment by enoriega** [comment]
The reason of why is giving false positives with "mum" is because text normalization converts µM to muM, which matches an entry in the KB.

Here is a list of all the mentions that match for species in PMC88976.nxml:

DEBUG: human taxonomy:9606
**DEBUG: muM taxonomy:41568**
DEBUG: mouse taxonomy:10090
**DEBUG: FLAG taxonomy:34205**
DEBUG: Chinese hamster taxonomy:10029

By far, muM has the largest amount of mentions. We can just delete that entry from bioresources

**Comment by hickst** [comment]
So you are proposing is to remove Mum and Mums from the Species KB? If this will temporarily fix the problem, I say "do it" since I highly doubt that many of our cancer papers are using Mums as research species.

**Comment by hickst** [comment]
I went ahead and removed Mum/s from the Species.tsv.gz, recompiled the NER files, updated the version to 1.1.1-SNAPSHOT, and checked it back in.

**Comment by enoriega** [comment]
Yes, this is what I meant, thanks tom!

**Comment by MihaiSurdeanu** [comment]
Releasing bioresources 1.1.2 now.
