### ISSUE TITLE
Coref errors in latest run

### ISSUE THREAD

**Issue by hickst** [clulab/reach#118]
I started a big paper run and processed about 1K out of 13K papers before stopping the run (for unrelated reasons). In the first 1K, I got 3 (4?) Coref-related errors (error log file attached).
[log-coref.txt](https://github.com/clulab/reach/files/171326/log-coref.txt)

**Comment by danebell** [comment]
I was able to reproduce the three errors caused by the `require` statement, and will get to work on clearing this type of error. I'm not sure how to deal with the last one since I can't reproduce it. If we have more instances in our logs that look like that one, I can try other papers.
