### ISSUE TITLE
Keep track if a regulation is direct or not

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#135]
A phosphorylates B - direct
A causes the phosphorylation of B - indirect
Add a Boolean flag to BioEventMention

**Comment by MihaiSurdeanu** [comment]
splitSimpleEvent should always create BioMentions with the Boolean flag (isDirectReg) set to true.

**Comment by MihaiSurdeanu** [comment]
The isDirectReg flag must be added to BioEventMention

**Comment by hickst** [comment]
Is splitSimpleEvent the only place where BioMentions will have their isDirectReg flag set to true?

**Comment by MihaiSurdeanu** [comment]
Yes!

**Comment by hickst** [comment]
Closed by pull request #165 .

**Comment by myedibleenso** [comment]
Should `isDirect` be set to `true` for "Akt interacts with Raf and **phosphorylates it at Ser259** ." in	PMC1242134?  Currently, it seems to be `false`...

**Comment by MihaiSurdeanu** [comment]
I think so...
