### ISSUE TITLE
ReachCLI should use PaperReader

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#141]
We could simplify `application.conf` and our lives if `ReachCLI` used `PaperReader`, which can handle both `.nxml` and `.csv`.

Also, we could provide an option to generate output from serialized mentions.

**Comment by myedibleenso** [comment]
I think at this point `AssemblyCLI` should just replace/be renamed to `ReachCLI`.   If we do that, this issue can be closed.

**Comment by hickst** [comment]
I don't think this is a good idea.
1. Assembly seems expensive and it is nice to be able to run papers with it
2. AssemblyCLI doesn't handle Text or Indexcard output, both of which are still useful to have.

**Comment by myedibleenso** [comment]
Good points.

>1. Assembly seems expensive and it is nice to be able to run papers with it  

Yeah, it certainly has slowed down compared to runtime before the summer.  I want to profile it to better understand what's causing this.

>AssemblyCLI doesn't handle Text or Indexcard output, both of which are still useful to have.

Yep.  Not yet anyway...

**Comment by hickst** [comment]
I just did a small test: I ran the ReachCLI and the AssemblyCLI on the 15 DryRun files.
The AssemblyCLI took 1438s and the ReachCLI took 320s (4.5x ratio).
But, note that the ReachCLI failed to process the single CSV file, did not produce an error for that failure, and produced no output for that input.

**Comment by myedibleenso** [comment]
>AssemblyCLI took 1438s  

That's terrible, but I'm certain I can improve it.  I will have to profile after the evaluation to be better understand where all the time is being spent.

Anyway I merged the two systems, cleaned them up, made assembly configurable (I added a `withAssembly` variable to the config), added support for all of the existing output formats + the assembly tsv thing we used for the previous dry run, and added a test for fries + assembly.  

That at least addresses your second point.

**Comment by hickst** [comment]
After PR #294, I reran all the tests with the current build and they passed. Running ReachCLI on the DR3 files also worked (using withAssembly config).

BUT I am getting a strange error when running TestReachCLI with the current Processors 5.9.4-snapshot (but no compiler errors or warnings):
```
featureFactory=org.clulab.processors.corenlp.chunker.ChunkingFeatureFactory
writing PMC1240239.txt ...
writing PMC3847091.txt ...
writing PMC3441633.txt ...
writing PMC88976.txt ...
Will output FRIES output in directory /var/folders/mg/l1jhb1p923d3v3sjg6shbz600000z8/T/tmpFries-959602092985970-109-0
Will output FRIES with Assembly output in directory /var/folders/mg/l1jhb1p923d3v3sjg6shbz600000z8/T/tmpWithAssemblyFries-959684390870632-109-0
[info] TestReachCLI:
[info] ReachCLI
[info] - should output TEXT correctly on NXML papers (2 minutes, 37 seconds)
[info] - should output FRIES correctly on NXML papers without assembly (1 minute, 22 seconds)
[info] Exception encountered when attempting to run a suite with class name: org.clulab.reach.TestReachCLI *** ABORTED *** (7 minutes, 31 seconds)
[info]   java.lang.StackOverflowError:
[info]   at scala.collection.SetLike$class.newBuilder(SetLike.scala:76)
[info]   at scala.collection.AbstractSet.newBuilder(Set.scala:47)
[info]   at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
[info]   at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
[info]   at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
[info]   at org.clulab.reach.mentions.BioEventMention.hashCode(BioMention.scala:39)
[info]   at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
[info]   at scala.util.hashing.MurmurHash3$$anonfun$unorderedHash$1.apply(MurmurHash3.scala:92)
[info]   at scala.util.hashing.MurmurHash3$$anonfun$unorderedHash$1.apply(MurmurHash3.scala:91)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   ...
[info] Run completed in 7 minutes, 31 seconds.
[info] Total number of tests run: 2
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error] 	org.clulab.reach.TestReachCLI
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 453 s, completed Jul 29, 2016 3:34:38 AM
```

**Comment by myedibleenso** [comment]
What is the full stack trace and/or can you paste the log for that test?

**Comment by myedibleenso** [comment]
Except for the version number, the current 9.3.4-SNAPSHOT is identical to 5.9.3 (which is what we're using on `reach` master).

**Comment by hickst** [comment]
Yea, this looked like some odd class versioning or caching problem to me but it was too late at night to investigate. I'll start over recompiling the whole chain of Bioresources, Proc and then Reach and retest.

**Comment by hickst** [comment]
BTW - The above *is* the run log with the only stack trace that came from running that test-only at the command line.

**Comment by hickst** [comment]
Gus and I think this is some Assembly problem and we're investigating. Moving this to issue #296.
