### ISSUE TITLE
BioProcess shouldn't be controller of regulation

### ISSUE THREAD

**Issue by danebell** [clulab/reach#150]
e.g. "senescence reduced the phosphorylation of p53 on Ser15" in "The knockdown of SOCS1 during STAT5 induced senescence reduced the phosphorylation of p53 on Ser15 , diminished the nuclear accumulation of p53 and compromised the development of senescence phenotype ."

**Comment by MihaiSurdeanu** [comment]
This is allowed only if the Controlled is another bio process.
