### ISSUE TITLE
Need tests for correct NER operation

### ISSUE THREAD

**Issue by hickst** [clulab/reach#153]
The recent cell line bug (#145) would have been caught by simple tests for correct NER labeling. There don't seem to be any NER tests yet.

**Comment by MihaiSurdeanu** [comment]
Please add additional tests to edu.arizona.sista.reach.TestEntities

**Comment by hickst** [comment]
This turned out to be surprisingly hard -- several randomly chosen items  in each label category were either not labeled by the NER or were labeled in another category. The latter was due to term overlap among the KBs (creating obvious ambiguity). But, I would have expected that unambiguous terms from each KB would always be labeled, but this did not seem to be the case.
