### ISSUE TITLE
Continuing multiple antecedents found issue

### ISSUE THREAD

**Issue by hickst** [clulab/reach#160]
Still getting this voluminous error. If not fatal to processing of this paper, print one line warning into output (or ignore it) and move on. If fatal to processing of paper, print one line error into output and move on (stack trace is not necessary as we know where this occur and the user can do nothing about the error anyway).

¡¡¡ extraction error !!!

paper: PMC3660063

error:
java.lang.IllegalArgumentException: requirement failed: Multiple (2) antecedents found for mutants: BRAF, BRAF!

stack trace:
scala.Predef$.require(Predef.scala:219)
edu.arizona.sista.reach.mentions.Anaphoric$class.antecedent(Anaphoric.scala:35)
edu.arizona.sista.reach.mentions.CorefTextBoundMention.antecedent(CorefMention.scala:9)
edu.arizona.sista.reach.mentions.CorefTextBoundMention.isComplete(CorefMention.scala:59)
edu.arizona.sista.coref.Coref$$anonfun$apply$30$$anonfun$apply$38.apply(Coref.scala:414)
edu.arizona.sista.coref.Coref$$anonfun$apply$30$$anonfun$apply$38.apply(Coref.scala:414)
scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
scala.collection.immutable.List.foreach(List.scala:381)
scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
scala.collection.AbstractTraversable.filter(Traversable.scala:104)
edu.arizona.sista.coref.Coref$$anonfun$apply$30.apply(Coref.scala:414)
edu.arizona.sista.coref.Coref$$anonfun$apply$30.apply(Coref.scala:340)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
scala.collection.AbstractTraversable.map(Traversable.scala:104)
edu.arizona.sista.coref.Coref.apply(Coref.scala:340)
edu.arizona.sista.reach.ReachSystem.resolveCoref(ReachSystem.scala:154)
edu.arizona.sista.reach.ReachSystem.extractFrom(ReachSystem.scala:77)
edu.arizona.sista.reach.ReachCLI$$anonfun$processPapers$2.apply(ReachCLI.scala:116)
edu.arizona.sista.reach.ReachCLI$$anonfun$processPapers$2.apply(ReachCLI.scala:50)

**Comment by MihaiSurdeanu** [comment]
@danebell: please fix this

**Comment by danebell** [comment]
@hickst I was not able to reproduce this error with the paper cited above. Do you have any other (perhaps more current) papers that produced errors?

**Comment by hickst** [comment]
@danebell I just tried and it succeeded. I have to conclude that the error has been OBE (overcome by events) or should we coin a new term FBRC (fixed by recent changes). I'm closing.
