### ISSUE TITLE
Use PubChem in preference to ChEBI

### ISSUE THREAD

**Issue by hickst** [clulab/reach#167]

**Comment by hickst** [comment]
I think using PubChem is going to be a major problem. Just spent 1.5 hours on their site trying to figure out how to get either their entire database or, preferably, just the little bit of information that we need out. To download the entire database we could use their FTP site which contains 4757 separate XML files, totalling 235 Gigabytes of download. We would then need a custom program to find and extract just the fragments of data we need. I question why MITRE has decided to use this database when perfectly good and easily available alternatives exist.

**Comment by hickst** [comment]
Matt Peterson at MITRE claims "there is  a mapper between ChEBI and PubChem...". Investigate this.

**Comment by bgyori** [comment]
Hi Tom, if you're mapping to ChEBI in your system, you can just get the ChEBI ID first and then lookup the associated PubChem ID from the ChEBI entry.
One example is here: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:63637
If you click on "View more database links" it gives you the PubChem ID. I'm pretty sure their webservice can also do this mapping. What I'm not sure about is how easy it is to construct a bulk download table of these mappings.

**Comment by hickst** [comment]
We're going to try create a local Pubchem KB via the Pubchem mapping service:
https://pubchem.ncbi.nlm.nih.gov/idexchange/idexchange-help.html

**Comment by hickst** [comment]
Closed by pull request #169
