### ISSUE TITLE
Add tests for FRIES output formatter

### ISSUE THREAD

**Issue by hickst** [clulab/reach#172]

**Comment by myedibleenso** [comment]
What will these look like?  Just validation checks, or are you going to try to count stuff between runs?

**Comment by hickst** [comment]
Good question. Counting is very data and rule driven, which makes it hard to keep up-to-date. I was just planning to verify pieces of the generated JSON against portions the Hans schema.

**Comment by hickst** [comment]
Closed by pull request #202
