### ISSUE TITLE
Make sure indirect regulations are reported in FRIES

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#179]
The "is-indirect" flag must be included. 
Add a unit test:
- "A induces the phosphorylation of B" - indirect
- "A phosphorylates B" - direct
Hans must be aware of what the conversion from this index cards with GENERICs is!

**Comment by hickst** [comment]
is-direct flag is being reported with default false. True values are few and far between (e.g., counts from the eval NXML files):
```[twelf:eval-fb () 1628] => grep -c '"is-direct":true' *events.json
PMC1234335.uaz.events.json:0
PMC3178447.uaz.events.json:3
PMC3690480.uaz.events.json:0
PMC4345513.uaz.events.json:2
PMC534114.uaz.events.json:2
[twelf:eval-fb () 1629] => grep -c '"is-direct":false' *events.json
PMC1234335.uaz.events.json:39
PMC3178447.uaz.events.json:74
PMC3690480.uaz.events.json:208
PMC4345513.uaz.events.json:57
PMC534114.uaz.events.json:190
```

**Comment by hickst** [comment]
The isDirect flag is being tested in TestRegulationEvents.scala. I "piggybacked" isDirect tests on the following existing test phrases:

The ubiquitinated Ras protein phosphorylates AKT. (true)
The phosphorylation of ASPP1 inhibits the ubiquitination of ASPP2 (false)
The binding of ASPP1 and ASPP2 promotes the phosphorylation of MEK (false)
Human deoxycytidine kinase is phosphorylated by ASPP2 on serine 128. (true)
Human deoxycytidine kinase is phosphorylated on serine 128 by ASPP2. (true)
The binding of BS1 and BS2 promotes the phosphorylation of MEK (false)
