### ISSUE TITLE
Preparing the family members KB

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#182]
Make sure we have TSV file (from Ben?) with:
"family name(s)" TAB member1 grounding_for_member1 ...

**Comment by MihaiSurdeanu** [comment]
Then, export the families as a collection of their members. We need to check with MITRE on WHICH members should be included (all, just the ones mentioned in the paper, magic?).

**Comment by hickst** [comment]
Add family information from MITRE model and NMZ file.
