### ISSUE TITLE
Globally label protein families

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#183]
If a protein mention is flipped from Protein to Family, make sure all instances THROUGHOUT the paper are labeled in the same way.

**Comment by MihaiSurdeanu** [comment]
This has to be done in Reach, after the entity engine runs for ALL sections of the paper.

**Comment by hickst** [comment]
I will update the overlap spreadsheet for the 3 recent KB changes, very soon and attach it here.

**Comment by MihaiSurdeanu** [comment]
This is based on a config file with 4 columns:
Family|Protein|family|protein

That is,
NewLabel|OldLabel|context for new label|context when to keep the old label

**Comment by hickst** [comment]
Picture of the latest KB overlap map; updated after the final replacement of homemade KBs:

![overlap2](https://cloud.githubusercontent.com/assets/22797/15560020/426edfc8-229c-11e6-9392-82a126df384b.jpg)

**Comment by hickst** [comment]
Sent to Hans and incorporated non-conflicting families into master override KB.
