### ISSUE TITLE
When the Controller of a reg is an event, convert it to a Controller entity + participant features:

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#184]
This might be done already? 
Make sure it shows in the FRIES format.

**Comment by MihaiSurdeanu** [comment]
The above works well when the Controller is a simple event. BUT, this functionality is not triggered when the Controller is another regulation. For example, in this made up example:

"The up-regulation of the phosphorylation of A by B promotes the ubiquitination of C",

the Controller is PosReg(controller:B, controlled: Phospho(A)). In this situations, the Controller should be converted to this entity: A_phospho. Or A_not_phospho, if it's a NegReg.

**Comment by MihaiSurdeanu** [comment]
There is a test for the "flattening" of Controllers in TestFeedback2.

**Comment by MihaiSurdeanu** [comment]
The same for flattening Controllers should be applied to BOTH Regulations and Activations.

The Controlled participants are NOT affected by this!

**Comment by myedibleenso** [comment]
>Or A_not_phospho, if it's a NegReg.

This isn't currently supported in the `PTM` modifications on Mentions, though it is for the `PTM` modifications in **assembly**.  I guess I will need to modify the `PTM` mod for Mentions.

**Comment by myedibleenso** [comment]
I am thinking to replace `convertEventToEntity` with a recursive pattern matching function with this signature:
`(m: Mention, negated: Boolean = false): BioMention = m.toBioMention match {`

Here's a summary of the version I've drafted:

1. An `Entity` is returned unmodified*.  I think we should reconsider this, as the parent of this entity might be something like a `NegativeActivation` (ex. deactivated RAS), right? Perhaps we could/should add a `Negation` mod to this entity or create a `PTM` modification with an "UNKNOWN" label.  As of now, though, I just return the `Entity` as-is...  
2. Bindings are converted into a `Complex`, so that they behave like entities as far as the system is concerned (this is what we were already doing)  
3. A `SimpleEvent` is converted into a `PTM` modification on its `theme`.  The "negated" value of this `PTM` is determined by the current value of "negated".  
4. If it sees a _positive_ `ComplexEvent`,it makes a recursive call on the controlled (the event’s "output") using the current value of the "negated" parameter.  
5. If it sees a _negative_ `ComplexEvent`, it makes a recursive call on the `controlled` (the event’s "output") and flags it as negated.

**Comment by myedibleenso** [comment]
Thoughts?

**Comment by myedibleenso** [comment]
```scala
/** Recursively converts an Event to an Entity with the appropriate modifications representing its state.
    * SimpleEvent -> theme + PTM <br>
    * Binding -> Complex (treated as an Entity) <br>
    * ComplexEvent -> recursive call on controlled (the event's "output") <br>
    */
  @tailrec
  private def convertEventToEntity(m: Mention, negated: Boolean = false): BioMention = m.toBioMention match {

    // no conversion needed
    // FIXME: consider case of "activated RAS".
    // We may want to add a Negation mod to this entity conditionally
    // or add a PTM with the label "UNKNOWN" and negate it (depending on value of negated)
    case tb: BioTextBoundMention => tb

    // convert a binding into a Complex so that it is treated as an entity
    case binding if binding matches "Binding" =>
      new BioRelationMention(
        DarpaActions.taxonomy.hypernymsFor("Complex"),
        binding.arguments,
        binding.sentence,
        binding.document,
        binding.keep,
        binding.foundBy)

    // convert event to PTM on its theme.
    // negate PTM according to current value of "negated"
    // (this SimpleEvent may have been the controlled to some negative ComplexEvent)
    case se: BioEventMention if se matches "SimpleEvent" =>
      // get the theme of the event (assume only one theme)
      val entity = se.arguments("theme").head.toBioMention
      // get an optional site (assume only one site)
      val siteOption = se.arguments.get("site").map(_.head)
      // create new mention for the entity
      val modifiedEntity = new BioTextBoundMention(
        entity.labels,
        entity.tokenInterval,
        entity.sentence,
        entity.document,
        entity.keep,
        entity.foundBy)
      // attach a modification based on the event trigger
      val label = getModificationLabel(se.trigger.text)
      BioMention.copyAttachments(entity, modifiedEntity)
      modifiedEntity.modifications += PTM(label, evidence = Some(se.trigger), site = siteOption, negated)
      modifiedEntity

    // dig into the controlled (event's "output" or the part that is altered in some way)
    case posEvent if (posEvent matches "ComplexEvent") && (!hasNegativePolarity(posEvent)) =>
      // get the controlled of the event (assume only one controlled)
      val controlled = posEvent.arguments("controlled").head.toBioMention
      convertEventToEntity(controlled, negated)

    // dig into the controlled (event's "output" or the part that is altered in some way)
    // ComplexEvents with negative polarity "negate" the ptm of the contained entity
    // (see https://github.com/clulab/reach/issues/184)
    case negEvent if (negEvent matches "ComplexEvent") && hasNegativePolarity(negEvent) =>
      // get the controlled of the event (assume only one controlled)
      val controlled = negEvent.arguments("controlled").head.toBioMention
      // negate the underlying PTM
      // if received event has negative polarity (see issue #184)
      convertEventToEntity(controlled, negated=true)
  }
```

**Comment by myedibleenso** [comment]
## TODO ([`curse-of-the-flat-man` branch](https://github.com/clulab/reach/tree/curse-of-the-flat-man))
- [ ] Fix export (see `MentionManager.modificationsToStrings`)
- [ ] Decide whether or not to add `Negation` or `PTM("UNKNOWN")` to entities

**Comment by MihaiSurdeanu** [comment]
I like this Gus!

@hickst and @myedibleenso: Please pick a solution for negations output in FRIES, and make sure Hans is aware of it.

**Comment by myedibleenso** [comment]
Note that a consequence of this flattening/conversion is that Events are no longer valid controllers.

**Comment by myedibleenso** [comment]
14 failing tests to go...

**Comment by MihaiSurdeanu** [comment]
Not sure that's true: the rules should still match Events as Controllers,
since this change happens *later*, when the actions is applied. No?

**Comment by myedibleenso** [comment]
In that case, 44 failing tests...

**Comment by MihaiSurdeanu** [comment]
Is it simpler to do this conversion just before the export?
And keep Controllers as Events in the core of Reach?

**Comment by myedibleenso** [comment]
I'm still trying to understand these errors, but I think we can allow controllers to be events no matter where we decide to perform the flattening.

>Is it simpler to do this conversion just before the export?

I believe it would be better for us to do this kind of thing at export.  Isolating it to the germination of output (or certain output formats) gives us more flexibility and power, and the core of the system need not be hampered or degraded by ever-changing export requirements.

**Comment by MihaiSurdeanu** [comment]
I agree! This is ultimately just a requirement for the export. I also
prefer to keep the internal representations more explicit and close to the
text.

**Comment by myedibleenso** [comment]
Existing tests now pass.
