### ISSUE TITLE
Add complexes_with relation

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#188]
This should be done only for explicit mentions of complexes, e.g.: "the A-B-C complex"

**Comment by MihaiSurdeanu** [comment]
processors 5.8.6-SNAPSHOT has global tokenization for complexes. That is, assuming A, B, and C are mentioned as standalone proteins in the paper, the text "the A-B-C complex", or "the A/B/C complex" is tokenized into: "the A, B, and C complex". 

Please write a surface rule to capture these complexes as Binding events with 2+ themes. Do it as a surface rule: syntax is generally broken in the parser for longer enumerations.

**Comment by marcovzla** [comment]
I don't think the tokenizer is doing the right thing in BioProcessors.
Are there tests for this tokenizer feature?

For example, binary complexes ("the A-B complex") always split into "the A and B complex",
even when A and B were not mentioned as standalone proteins.

And "the A-B-C complex" is never turned into "the A, B, and C complex", even when A, B, and C were mentioned as standalone proteins.

**Comment by marcovzla** [comment]
@MihaiSurdeanu binary complexes seem to be treated as a special case.
Is this the correct behavior?

**Comment by marcovzla** [comment]
@MihaiSurdeanu are these BioTokenizer tests correct?
https://github.com/clulab/processors/blob/d12900e5d5d1b90897e68da1aba0113c5aaf0e79/src/test/scala/org/clulab/processors/TestBioNLPTokenizer.scala#L84-L98

**Comment by marcovzla** [comment]
It seems that the global tokenization algorithm is correct, but it is being called per sentence. See https://github.com/clulab/processors/blob/09117506c93d38f62a43ab90cd80c2bce3053b72/src/main/scala/org/clulab/processors/shallownlp/ShallowNLPProcessor.scala#L126-L127

**Comment by MihaiSurdeanu** [comment]
Good catch.
I will fix this!
Mihai

**Comment by MihaiSurdeanu** [comment]
And yes, binary complexes are a special case.
Meanwhile, you can still handle n-ary complexes that are specified directly
with an enumeration, e.g., "A, B, and C complex"

**Comment by MihaiSurdeanu** [comment]
@marcovzla: it turns out the bug in processors is kinda of a pain to fix.
But, thinking more about this, I would actually like to change the logic: I will break n-ary complexes such as "A-B-C-D complex" only into parts that exist in our KBs. For example, "A-B" may be an existing protein, rather than 2 ("A" and "B"). 
I think this is safer than using the text, because the text obviously contains many other tokens as well. For example, "a" appear as a determiner much more often than as a protein, which may lead to false positives splits in complexes that contain "a-...".
What do you think?

**Comment by marcovzla** [comment]
Sounds good. This can be done at the sentence level.
Will you do it or do you want me to?

**Comment by MihaiSurdeanu** [comment]
I'll do it.

**Comment by MihaiSurdeanu** [comment]
In the end, I think I was overcomplicating things on the processors side. I ended up implementing a simpler logic in processors that relies solely on regexes. Now both binary and n-ary complexes are handled by the same logic. All tests in processors pass.

You'll have to publishLocally 5.9.3-SNAPSHOT.
