### ISSUE TITLE
Replace homemade KBs

### ISSUE THREAD

**Issue by hickst** [clulab/reach#190]
Need to replace our homemade context KBs (CellLine, CellType, and Organs) with "official" ones. MIRIAM registered KBs are most preferred, followed by other recognized industry sources:

- [x] cell type with Cell Ontology
- [x] cell line with Cellosaurus
- [x] Organs with Uberon

**Comment by MihaiSurdeanu** [comment]
@enoriega, can you please help here?
Mihai

**Comment by hickst** [comment]
I think it's better if one person is responsible for this kind of task. I don't care who but it should be one person.

**Comment by enoriega** [comment]
I will like to replace the cell lines and the organs at least with Cellosaurus and Uberon respectively. They seem well established and we can get rid of the internal ids by using them.

**Comment by hickst** [comment]
Sounds good. I am currently working on replacing the cell types with CellOntology.

**Comment by hickst** [comment]
Let's coordinate our replacements of the KBs. I've created branch 'issue190' in both Bioresources and Reach for this purpose. We can share these branches for our work (so be careful with pushes, etc).

**Comment by enoriega** [comment]
Ok, Thanks

**Comment by hickst** [comment]
Closed by pull request #211.
