### ISSUE TITLE
Update OdinWeb with latest Reach

### ISSUE THREAD

**Issue by hickst** [clulab/reach#201]

**Comment by antonkulaga** [comment]
It would also be nice to see reach 1.2.3 officially published.

**Comment by hickst** [comment]
Per MS 6/24/16: Must be done by, at latest, July 15th.

**Comment by MihaiSurdeanu** [comment]
Thanks Tom!

**Comment by hickst** [comment]
Done but will open new issue for problematic BRAT output due to complex event nesting.
