### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by antonkulaga** [clulab/reach#203]
org.biopax.paxtools#paxtools-core;4.3.0: not found

Please, update dependencies!

**Comment by myedibleenso** [comment]
Hi.  This dependency has already been updated:

https://github.com/clulab/reach/blob/3a7520591688de2b0be6579a51630773a327c4ed/build.sbt#L73

We will publish a new version of `reach` soon.  I'm surprised the previous version of this dependency was removed from maven...

For the time being, you should be able to clone and run things as they're configured here.

**Comment by myedibleenso** [comment]
Ah, I think that version (4.3.0) was never on Maven.  Previously, we were using a different resolver, but BioPax started publishing to Maven so we removed the old resolver.

**Comment by hickst** [comment]
If you need to compile with paxtools 4.3.0, I believe that adding the following back into the build file might allow you to do so:

resolvers ++= Seq(
  "BioPAX Releases" at "http://biopax.sourceforge.net/m2repo/releases",
  "BioPAX Snapshots" at "http://biopax.sourceforge.net/m2repo/snapshots"
)
