### ISSUE TITLE
system error in Windows

### ISSUE THREAD

**Issue by dnanni** [clulab/reach#206]
application.conf: 7: could not resolve substitution to a value: ${HOME}

any solutions?

**Comment by marcovzla** [comment]
Can you try replacing `${HOME}` with `${user.home}`?
That should work on windows too, but I don't have a windows machine to test it.
Let us know if it works to fix the config accordingly.

**Comment by dnanni** [comment]
Could you elaborate a bit, please? I'm not sure what to do.

**Comment by myedibleenso** [comment]
@dnanni, have you cloned the repository?  If so, can you try changing instances of `${HOME}` to `${user.home}` in this file: https://github.com/clulab/reach/blob/3a7520591688de2b0be6579a51630773a327c4ed/src/main/resources/application.conf? 

(`src/main/resources/application.conf`)

**Comment by myedibleenso** [comment]
Any luck with that solution, @dnanni?

**Comment by dnanni** [comment]
I changed each instance of HOME to user.home, but my error message is unchanged. I'm looking to see if I have another instance of reach that the files are using, but I can't seem to find one.

**Comment by myedibleenso** [comment]
Ah, drat...I expected the error message to at least change.  

Is it now `application.conf: 7: could not resolve substitution to a value: ${user.home}`?

Can you try changing those lines to the full paths where you expect those documents to be?

**Comment by dnanni** [comment]
Unfortunately the error message is the same, still ${HOME}. I also tried putting C:/Users/Daniel/Documents etc. instead of ${HOME}, but the message is still unchanged.

**Comment by hickst** [comment]
It's not important to use a HOME variable in the configuration file. Simply enter the path to the area where your input, output, and temp files reside. Assuming C:/Users/Daniel/Documents is a valid Windows path, that should work (I haven't used Windows in 25 years but aren't those slashes backwards for Windows?). If you are still getting messages about HOME, then you must have missed one of the replacements in the config file (I find 5 uses of HOME var in the current config file).

**Comment by dnanni** [comment]
I think the error must be in some other files that I'm overlooking. Any changes to the .conf file in reach changes nothing in the error message, even after I change all five instances of "HOME". I'll check back later if I find the problem.

**Comment by hickst** [comment]
I grep'ed the entire project for uses of HOME variable and this is the only file I found that contains HOME. Are you sure that you are correctly modifying the application.conf file in
 ...reach/src/main/resources (don't laugh....I've edited the wrong copy of a file before).

Also, if you are using sbt, you should do a 'sbt clean compile' between attempts.

**Comment by dnanni** [comment]
Yes, that's the .conf file I've been changing. I also tried "sbt clean compile", with no differing results.

**Comment by hickst** [comment]
Sorry that you're having trouble but we're all out of ideas here, as none of us use or know Windows. I suggest that you contact your local Windows guru to help you troubleshoot the issue.

As we are a small grant-funded research project, we do not have the resources to provide much support and Windows is very low down on our prority list. If you do solve the problem, you are encouraged to post to this issue again so that others may benefit from your efforts in the future. Thanks and good luck.
