### ISSUE TITLE
get rid of redundant Option[Collection]

### ISSUE THREAD

**Issue by antonkulaga** [clulab/reach#208]
In the codebase I see a lot of lines like this:
```scala
 var context: Option[Map[String, Seq[String]]] = None //it is an example but here can be any collection
```
I think wrapping collections in Options is simply redundant and only makes the code more complicated.
You can use
```scala
 var context: Map[String, Seq[String]] = Map.empty[String, Seq[String]]]
```
instead

**Comment by antonkulaga** [comment]
On the long term I suggest about thinking of moving from large mutable classes to small immutable case classes (or classes with extractors) in places where it does not hurt performance. Right now I am writing a lot of case classes + conversion code just to be able to transmit the results that I get from reach to ScalaJS frontend of my app ...

**Comment by MihaiSurdeanu** [comment]
Closing for now.
