### ISSUE TITLE
scalajs support for core classes

### ISSUE THREAD

**Issue by antonkulaga** [clulab/reach#221]
Right now I am writing ScalaJS-based UI that visualises REACH results, integrates it with kappa annotations and also adds additional features (like adding new rules for by users from UI).
So I had to write my own case classes and ugly conversions like this:
https://github.com/antonkulaga/bio-nlp/blob/master/app/jvm/src/main/scala/org/denigma/nlp/extractions/ReachConverters.scala

In the Future, it will be nice if mains classes (like Sentence, Document, Mention and Rules) will cross build to Scala/ScalaJS, in such case any scalajs pickler libraries will serialize/deserialize them automatically, so developers will be able to manipulate mentions/sentences/kbentries classes directly in their UIs and send them back with just several lines of code.

Of course, it will require significant changes but I suggest to think about in the longterm

**Comment by hickst** [comment]
The Reach project is a research project with very specific goals, limited resources, and a limited mandate. At this time, we have no need to support cross-compilation libraries, such as ScalaJS. We feel that you have correctly located these conversion routines for your needs.
