### ISSUE TITLE
"Protein|Family inhibitor|inhibitors" -> Simple_chemical

### ISSUE THREAD

**Issue by danebell** [clulab/reach#230]
@MihaiSurdeanu :
>Add drug NE rules in Reach for "Raf Inhibitors". That is: "Protein|Family inhibitor|inhibitors" should be labeled as Drug.

"Raf inhibitors" should match as a Simple_chemical, and the "Raf" should not match as a Family (or anything else).

There are many protein names that include the substring `inhibitor` e.g. `Venom chymotrypsin inhibitor`, so this should only apply to cases where `inhibitor` is not part of an existing entity.

**Comment by hickst** [comment]
Some quantification of that clever observation: entries containing 'inhibitor'
in Uniprot: 5948
in PFAM: 112
in InterPro protein family KB: 150
in InterPro protein domains KB: 50
in HGNC gene KB: 248
