### ISSUE TITLE
GPP vs. Protein: confusing labeling schism

### ISSUE THREAD

**Issue by hickst** [clulab/reach#236]
ReachSystem re-labels some GPP items as 'protein' so output results are confusing and unpredictable (to humans): many proteins are labeled as 'protein', many are labeled as 'gene-or-gene-product'.
This makes tests fail when the KB data (or the even KB data source) changes for a given GPP item.

We should either stop the protein re-labeling or force FRIES outputter to undo the re-labeling on output.

**Comment by MihaiSurdeanu** [comment]
@hickst: I am not sure this is an issue. This block of code in ReachSystem normalizes the displayLabel of entity mentions that are ambiguously labeled as GGPs:

if(em.labels.contains("Gene_or_gene_product")) { // we only need to disambiguate these
      if (ReachKBUtils.isFamilyGrounded(em)) {
        // found a Family incorrectly labeled as protein
        em.displayLabel = "Family"
      } else if(parents.contains("Transcription")) {
        // found a Gene
        em.displayLabel = "Gene"
      } else {
        em.displayLabel = "Protein"
      }
    }

After this code is executed, the displayLabel should NOT contain GGP anymore.

**Comment by hickst** [comment]
Yes, that is the location in code that I meant in my initial report.
In our June 2015 evaluation results, 58% of entities were labeled 'protein' and 22% were labeled 'gene-or-gene-product'
In our most recent June 2016 evaluation results 42% of entities were labeled 'protein' and 20% were labeled 'gene-or-gen-product'.
This has been a problem for consistent testing. Do you consider it an problem for output and/or would you like to do something about it?

**Comment by MihaiSurdeanu** [comment]
This could be a bug in the exporter. Is the exporter using displayLabel for mentions? As the code above shows, this label should *never* be GGP, because that code always changes to something else. If you are using displayLabel in the exporter, and we still see GGP in the FRIES output, this is a bug.

**Comment by hickst** [comment]
I'm afraid this is a bug then. I checked that before I filed the issue but I also just double-checked: the line that creates the entity type label is:
    f("type") = prettifyLabel(mention.displayLabel)

Note, however, that (in ReachSystem) the re-assignment code (cited above) is only called IF the labels array contains "Events":

https://github.com/clulab/reach/blob/master/src/main/scala/edu/arizona/sista/reach/ReachSystem.scala#L182-L185

If we want this to apply to Entities, then this is most likely the bug.

**Comment by MihaiSurdeanu** [comment]
This is a bug. I will fix this.
Mihai

**Comment by MihaiSurdeanu** [comment]
I changed the code that generates displayLabel. See ReachSystem.resolveDisplayLabelForEntities() in the branch issue236.

@hickst: now the condition on line 112 in TestFriesOutput fails. Can you please see what's up? Also, if not existing already, can you please add a unit test to make sure all GGPs are converted?

**Comment by hickst** [comment]
Closed by pull request #240.
