### ISSUE TITLE
Figure out how to identify kinases

### ISSUE THREAD

**Issue by hickst** [clulab/reach#239]
Look for resources.

**Comment by hickst** [comment]
Attach modification as Kinase. Don't add kinase to taxonomy. Create lookup table of kinases from uniprot. Global rules use context (BOW) to find kinase.

**Comment by hickst** [comment]
@MihaiSurdeanu Uniprot includes species information. Should the Kinase lookup table be derived using human kinases only or all species?

**Comment by MihaiSurdeanu** [comment]
Can you please use all species, and generate a TSV file with two columns:

UniprotId TAB true|false (if the protein can serve as kinase)

Since the Uniprot ids have implicit species info, there's no need to save
that as well.
Thanks!

**Comment by hickst** [comment]
The current version IS using all species.
This problem is better solved as a Set membership problem, just as we are already doing with protein domain suffixes. I am using Scala's Set type internally and looking up the IDs through an isProteinKinase(id:String) API.
