### ISSUE TITLE
ReachSystem shouldn't contain code specific to export

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#241]
I propose that `resolveDisplay` and `resolveDisplayForArguments` be moved somewhere and called within the appropriate exporters.  

Each exporter should be responsible for figuring out what it needs to do with the mentions it receives.

**Comment by hickst** [comment]
This is based on the premise that displayLabel is only relevant to exporter code. IF that is true, then perhaps the displayLabel should not be added (via Display trait) as a property of the central data structure until it is needed.

**Comment by MihaiSurdeanu** [comment]
@marcovzla, @myedibleenso: wasn't this done?

**Comment by myedibleenso** [comment]
>@marcovzla, @myedibleenso: wasn't this done?

No this has not even been discussed.

As far as I can tell, the `displayLabel` (and the `Display` trait) is only relevant to "fries" (and index card?) export.  Is it used by anything else?  If not, perhaps we don't need that trait, and/or it is something that can be done at export for the relevant target formats...

**Comment by hickst** [comment]
What is the purpose of the `resolveDisplay`, `resolveDisplayForArguments`, `resolveDisplayForEntity` methods in the `ReachSystem` object?

They appear to be a post-extraction "fixup" in which heuristics are applied to try and disambiguate certain GGP entities. The `displayLabel` is used to hold the result of the heuristic; presumably so that the label set is not actually modified?

**Comment by myedibleenso** [comment]
Looking at it a bit more, it seems this used to disambiguate/sift through GGPs after grounding: 
https://github.com/clulab/reach/blob/a12abd9cdcf0a3afb1aa00c2afe469fe162f0362/main/src/main/scala/org/clulab/reach/ReachSystem.scala#L249-L258

It is the last thing we're doing in extraction.  The mentions are then passed along to export (I guess?).

I think this issue can be closed.  The category assignment performed by `resolveDisplay` gives us the "resolved/true" label.

**Comment by MihaiSurdeanu** [comment]
That's it.
They are not really used for export purposes. They generate canonical
labels into displayLabel. Yes, those labels are then read during export,
but there are other purposes for displayLabel. Mainly that they are easier
to interpret by human users.
If this is the only problem, I suggest to close this.
