### ISSUE TITLE
Extracting autophosphorylation

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#252]
Some proteins autophosphorylate, that is, they phosphorylate themselves. This can happen in cis (cis-autophosphorylation) when a single molecule phosphorylates itself or in trans (trans-autophosphorylation) when one molecule phosphorylates another molecule of the same type while they are in a complex (typically a dimer). This is the case for EGFR which trans-autophosphorylates in a dimer.

Some simple examples:
- EGFR autophosphorylates on a tyrosine residue.
- EGFR phosphorylates itself. _(strictly speaking not correct but people sometimes say this)_

I'm guessing there are two approaches to extracting such events, either as a new modification type called "autophosphorylation" with a single EGFR argument or the same phosphorylation event as for 2 different entities but with EGFR phosphorylating EGFR. 

This comes up in PMC534114:
- "However, stimulation with EGF for varying time intervals revealed no significant differences in the levels of autophosphorylation of EGFR in cells expressing wild type Gab1 versus the Gab1 F446/472/589 mutant.", 
- "As has been previously reported, recruitment of Shp2 by Gab1 does not alter the magnitude or kinetics of tyrosine autophosphorylation of EGFR.", 
- "Levels of EGFR autophosphorylation are represented linearly following quantitation by densitometry and normalization for protein expression levels.", 
- "Because the substrates of Shp2 are for the most part unknown, we were additionally interested in examining the state of EGFR tyrosine phosphorylation following treatment with EGF in order to determine if the failure of Gab1 to bind p85, and potentially recruit Shp2, would influence levels of EGFR autophosphorylation.", 
- "The experiment presented in Fig shows that all cell lines exhibit EGFR autophosphorylation in response to EGF treatment, while only cells expressing the ectopically introduced ErbB3 protein show ErbB3 tyrosine phosphorylation in response to EGF stimulation."

**Comment by myedibleenso** [comment]
Thanks, @bgyori!  With your examples and clear description, this shouldn't be too hard to address.

**Comment by myedibleenso** [comment]
I will take this approach:

>or the same phosphorylation event as for 2 different entities but with EGFR phosphorylating EGFR.

The event will be labeled as an `AutoPhosphorylation`, which will be treated as a sub-type of `Phosphorylation`.

**Comment by MihaiSurdeanu** [comment]
Ok!

**Comment by hickst** [comment]
Apparently the existing tests were not good enough for this issue which has broken the FIRES output formatter.

**Comment by hickst** [comment]
I've started a new branch for the fixes: - iss252

**Comment by hickst** [comment]
Example error:

```
paper: PMC3253115

error:
java.lang.Exception: org.clulab.reach.mentions.CorefEventMention@6e908258 with labels (List(AutoPhosphorylation, Phosphorylation, AdditionEvent, SimpleEvent, Event, PossibleController)) found by AutoPhosphorylation_syntax_2_noun is missing from the eventMap

stack trace:
org.clulab.reach.extern.export.fries.FriesOutput.org$clulab$reach$extern$export$fries$FriesOutput$$mkArgument(FriesOutput.scala:401)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention$1$$anonfun$apply$6$$anonfun$apply$7.apply(FriesOutput.scala:559)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention$1$$anonfun$apply$6$$anonfun$apply$7.apply(FriesOutput.scala:557)
scala.collection.immutable.Range.foreach(Range.scala:166)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention$1$$anonfun$apply$6.apply(FriesOutput.scala:557)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention$1$$anonfun$apply$6.apply(FriesOutput.scala:556)
scala.Option.foreach(Option.scala:257)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention$1.apply(FriesOutput.scala:556)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention$1.apply(FriesOutput.scala:555)
scala.collection.Iterator$class.foreach(Iterator.scala:750)
scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
org.clulab.reach.extern.export.fries.FriesOutput.org$clulab$reach$extern$export$fries$FriesOutput$$mkEventMention(FriesOutput.scala:555)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$eventsToModel$2$$anonfun$apply$3.apply(FriesOutput.scala:268)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$eventsToModel$2$$anonfun$apply$3.apply(FriesOutput.scala:266)
scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$eventsToModel$2.apply(FriesOutput.scala:266)
org.clulab.reach.extern.export.fries.FriesOutput$$anonfun$eventsToModel$2.apply(FriesOutput.scala:258)
scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
org.clulab.reach.extern.export.fries.FriesOutput.eventsToModel(FriesOutput.scala:258)
org.clulab.reach.extern.export.fries.FriesOutput.writeJSON(FriesOutput.scala:126)
org.clulab.reach.ReachCLI.outputMentions(ReachCLI.scala:198)
org.clulab.reach.ReachCLI$$anonfun$processPapers$2.apply(ReachCLI.scala:153)
org.clulab.reach.ReachCLI$$anonfun$processPapers$2.apply(ReachCLI.scala:50)
scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by myedibleenso** [comment]
Hmm...well all the tests passed before.  I'm not familiar with the exporter (and would prefer to stay that way).  Do you think you can handle it, @hickst?

**Comment by hickst** [comment]
Yea, I'll work on it.

**Comment by myedibleenso** [comment]
I have no idea why it would be missing from the event map.

**Comment by hickst** [comment]
The autophosphorylation error arose from missing constant (fixed). Other errors observed were related to nested complex events and not to this issue so closing this issue again.
