### ISSUE TITLE
Abbreviated amino acid site missing from PTM

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#253]
Tyrosine is not extracted as the amino acid residue on which phosphorylation happens (PMC2841635):
- "AR and Wwox Tyr-phosphorylations appear to be involved in late stage progression of prostate cancer to androgen-independence."
- "Neoplasia observed in PB-Ack1 mice could be due to the combined effect of Ack1 mediated AKT, AR and Wwox Tyr-phosphorylations."

When changing to 
- "AR and Wwox **tyrosine phosphorylations** appear to be involved in late stage progression of prostate cancer to androgen-independence." 
- "Neoplasia observed in PB-Ack1 mice could be due to the combined effect of Ack1 mediated AKT, AR and Wwox **tyrosine phosphorylations**."

it is extracted correctly.

**Comment by MihaiSurdeanu** [comment]
@danebell: Any POS tag changes should be added to BioNLPProcessor.postprocessTags()

**Comment by hickst** [comment]
@MihaiSurdeanu Testing this at the shell seems to show the hypenated form failing to be tokenized around the hyphen:

>>> Tyr-phosphorylations
sentence #0
Tyr-phosphorylations
Tokens: (0,Tyr-phosphorylations,NNS)
tyr-phosphorylation
roots: 0
outgoing:
incoming:
entities:
events:
==================================================
>>> Tyr phosphorylations
sentence #0
Tyr phosphorylations
Tokens: (0,Tyr,NN), (1,phosphorylations,NNS)
tyr phosphorylation
roots: 1
outgoing:
	0:
	1: (0,nn)
incoming:
	0: (1,nn)
	1:

entities:
mention text: Tyr
List(Site)
	------------------------------
	Rule => ner-domain-entities
	Type => CorefTextBoundMention
	------------------------------
	Site|List(Site) => Tyr
	grounding: KBResolution(tyr, uaz, UAZ-S-019, human)
	------------------------------
events:
==================================================

**Comment by myedibleenso** [comment]
@hickst, is that with the latest `processors`?

**Comment by hickst** [comment]
yes: Reach master which uses published processors 5.9.1

**Comment by MihaiSurdeanu** [comment]
These abbrevs. prpbably fell thru the cracks when I implemented the dash
handling. I will look at these soon.

**Comment by MihaiSurdeanu** [comment]
This tokenization is now fixed and merged into the master branch of processors. processors tests pass. One test in reach fails:

[info] Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, and Val are now labeled as Sites.
[info] - should have Site labels *** FAILED *** (14 milliseconds)
[info]   20 was not equal to 18 (TestOverrides.scala:293)
[info] Run completed in 2 minutes, 41 seconds.
[info] Total number of tests run: 40
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 39, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.clulab.reach.TestOverrides

However, it seems to me that test is incorrect. The condition tested should be 20 not 18.

**Comment by MihaiSurdeanu** [comment]
@hickst, @danebell: can you please take it from here?

**Comment by hickst** [comment]
You are correct about the test. But I did leave a comment right above the errant test:
    // the counts will be wrong until processors issue #77 is fixed:
and comments on the each test workaround which said:
   // wrong: workaround issue #77 

All tests are now passing in branch 'iss253' BUT this branch is dependent on Processors 5.9.2-SNAPSHOT so it can't be auto-tested by Travis on checkin.

**Comment by MihaiSurdeanu** [comment]
Do you want to release 5.9.2?

**Comment by hickst** [comment]
Closed by pull request #271
