### ISSUE TITLE
Amino acid site missing when it appears before PTM

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#254]
The tyrosine residue is missing from the extracted phosphorylation event (PMC534114): 
"We did not detect a change in the tyrosine phosphorylation of EGFR in cells expressing Gab1 proteins that are deficient in recruitment of Shp2."

When changed to: "We did not detect a change in the phosphorylation of **EGFR on tyrosine** in cells expressing Gab1 proteins that are deficient in recruitment of Shp2.",
tyrosine is recognized correctly.

**Comment by MihaiSurdeanu** [comment]
@bgyori: Ben, all these are awesome! Thanks for the feedback!
