### ISSUE TITLE
Extract translocation without controller (not passive form)

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#257]
Translocation is currently extracted only if it's in a passive form, e.g. "FOXO3a is translocated to the nucleus". But it is not extracted as "FOXO3a translocates to the nucleus".

**Comment by myedibleenso** [comment]
@danebell, I think you were/are the the translocation-miester, no?

**Comment by danebell** [comment]
Translocation has been assigned to @enoriega

**Comment by myedibleenso** [comment]
Ah, I thought he was the **transcription** guy.

**Comment by bgyori** [comment]
Are you extracting anything about transcriptions, by the way? I didn't encounter any examples of it yet.

**Comment by myedibleenso** [comment]
No, currently we're not capturing them.  We do have some rules for transcription events, but those rules have been inactive for awhile now.

**Comment by enoriega** [comment]
This was addressed with the code from pull request Issue257
