### ISSUE TITLE
PTM location with position before amino acid code is not extracted

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#258]
This comes up in PMC4729484: "Rac1 is phosphorylated on 71 S by Akt, which does not change Rac1 GTPase activity of Rac1, but inhibits its binding to GTP." 

Removing the space ("Rac1 is phosphorylated on 71S by Akt") doesn't help but "Rac1 is phosphorylated on **S71** by Akt" is handled correctly. 

Some other examples:
- Moreover, Rac1 is phosphorylated at 64 Y by FAK and SRC kinases, potentially playing a role in the regulation of cell spreading.
- We have previously shown that extracellular signal regulated kinases [ERK, consisting of p44 (ERK1) and p42 (ERK2)] phosphorylates 108 T of Rac1 in response to EGF stimulation.
- These results suggest that the phosphorylation of RhoA 88 S and 100 T increases the interaction between RhoA and ROCK1.

**Comment by myedibleenso** [comment]
It sounds like we'll need to expand our site rules.  According to your examples, I think this  is the pattern we're missing:

1. sequence of 2-3 digits followed by a valid amino acid letter (capitalized)
   - `71 S`, `71S`, `108 T`, `88 S`, etc.

Does that sound right, @bgyori?

**Comment by danebell** [comment]
This is a very useful observation. Because it overlaps a bit with a change we needed to make in our site rules for the feedback2 branch, @myedibleenso , I made changes that cover these cases on that branch. Once that's merged, this issue can be closed.

**Comment by danebell** [comment]
@myedibleenso I believe all these example pass now, so I will close it. If you object, feel free to reopen.
