### ISSUE TITLE
Past tense phosphorylation, inconsistent extractions

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#259]
I am not sure what is going on here so I'll just post some observations:

From this sentence (PMC4331489)
`However, while MEK5D phosphorylated a kinase dead mutant of ERK5 (ERK5-KD) at its TEY site...`
2 events are extracted: a correct one that says MEK5D phosphorylates ERK5 and an incorrect one in which MEK5D gets phosphorylated.
 
Interestingly, `However, while MEK5D phosphorylated ERK5.` produces no events, `MEK5D phosphorylated ERK5.` produces no events but `MEK5D phosphorylated an ERK5.` produces a correct phosphorylation event between MEK5D and ERK5.

Further, `However, while MEK5D ubiquitinated a kinase dead ERK5.` produces the correct ubiquitination event but `However, while MEK5D phosphorylated a kinase dead ERK5.` again produces an incorrect phosphorylation event in which MEK5D is phosphorylated.

**Comment by danebell** [comment]
> However, while MEK5D phosphorylated ERK5
This is fully ambiguous because of the tokenizer removing hyphens. Imagine the following continuations:
> However, while MEK5D phosphorylated ERK5 did not react to treatment...

> However, while MEK5D phosphorylated ERK5, it did not affect...
I hesitate to write a surface rule for exactly this reason. We can't even rely on the tags here.

I'm currently working on the other two examples.
