### ISSUE TITLE
ReachConstants should be constructed from the taxonomy

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#260]
`ReachConstants` is used by the grounder and exporter (anything else, @hickst?) for handling classes of events.  It basically duplicates the information in taxonomy.  

It turns out that currently if someone adds a new event to the taxonomy, they need to also update `ReachConstants`.  It would be better to build this object automatically from the the taxonomy.

**Comment by myedibleenso** [comment]
I think we can wrap a [`Taxonomy` object](https://github.com/clulab/processors/blob/cfffbaf9939080074804adce99c4458f3aeeae43/src/main/scala/org/clulab/odin/impl/Taxonomy.scala) instantiated from `taxonomy.yml` and have `ReachConstants` query that.

**Comment by hickst** [comment]
Searching seems to show that it is only used by the exporters. I applaud any plan like this to reduce redundant information in the system.
