### ISSUE TITLE
Extraction of events from inhibition conditions

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#264]
From the sentence ```In preclinical melanoma models, BRAF inhibition has proven to paradoxically activate the MAPK signaling in cells with wild-type BRAF.``` a negative-activation event is extracted between BRAF and MAPK. In the original text, we have an _observation_ (that MAPK is observed to be activated when inhibiting BRAF) but the extracted even asserts a _mechanism_ (BRAF inhibits MAPK). However, this is not a valid mechanism behind the observation: `BRAF inactivates MAPK` is not the reason why MAPK is activated upon BRAF inhibition. In fact, BRAF activates MAPK, and there is a more complex mechanism behind BRAF inhibition actually resulting in MAPK activation (in certain contexts!). So I'm wondering if rules of the type that derive mechanisms from observations like `A inihibition activates B => A inhibits B` are always justified.

**Comment by MihaiSurdeanu** [comment]
@bgyori: any potential solution you see here?
I don't want to mess too much with the multiple negation code. That is very commonly used we found, and it generally works well.

**Comment by bgyori** [comment]
I think the problem is that this extraction rule is implicitly inferring a _mechanism_ from an empirical _observation_. A longer term solution could be to extract the observation more faithfully, that is, extract `((inhibition of BRAF) activate MAPK)` or `((inhibition of BRAF) increase (activation of MAPK))`. These could then still be sorted out and interpreted in downstream assembly and analysis systems. If the reading system doubles down on one possible _mechanism_ to explain the _observation_, there is little chance to figure out that `BRAF inactivates MAPK` is something that was inferred in the reading system and not declaratively stated in the text.

**Comment by bgyori** [comment]
Setting aside my concerns above regarding this rule, I found some further cases for which this rule could be extended. As a synthetic example, consider `EGFR inhibition deactivates MAPK1` from which REACH extracts an event stating that EGFR positively activates MAPK. Similarly, `EGFR knockdown deactivates MAPK1` yields a positive activation event. However, the same rule is not applied for `EGFR silencing` and `EGFR deletion`, resulting in a negative activation event to be extracted. 

An example from the wild is `Grb10 silencing promotes cell proliferation in untransformed wildtype and Nf1 mutant MEFs` from which GRB10 positively activates NF1 is extracted. (Of course, the extracted event will be incorrect even if the negative/positive activation is sorted out since the sentence talks about `Nf1 mutant MEFs` and not about `Nf1` per se - I will file this as a separate issue).

**Comment by bgyori** [comment]
One further example comes from another issue I posted: `loss of neurofibromin in monocytes and macrophages enhances ROS production`. Here `loss of` needs to be taken into account to determine the polarity of the effect of neurofibromin on ROS.

**Comment by MihaiSurdeanu** [comment]
Thanks Ben!
I am not sure what to do about changing the event representations... I get your point. But these new representations no longer match BioPAX, and that scares me.

Meanwhile, I added all the words you mentioned (I'll push my changes in a minute). Btw, the entire regex we use for polarity reversal is this:

`val SEMANTIC_NEGATIVE_PATTERN = "attenu|block|deactiv|decreas|degrad|delet|diminish|disrupt|impair|imped|inhibit|knockdown|limit|loss|lower|negat|reduc|reliev|repress|restrict|revers|silenc|slow|starv|suppress|supress".r`

Please let me know if we should add anything else.

**Comment by bgyori** [comment]
So the issue is that BioPAX is meant to represent _mechanisms_ whereas much of the literature (specifically many of the sentences that trigger this rule) describes _observations_. In this sense, it is not unexpected that BioPAX cannot express certain types of empirical observations. I understand that this would be a fundamental change in the system but it is something to keep in mind for the future.

As for the extended regex, I think `knockout` in addition to `knockdown` could be added.

**Comment by MihaiSurdeanu** [comment]
Done.

Closing this issue, just for house cleaning. We can reopen if we have a practical solution for the remaining problems.
