### ISSUE TITLE
Incorrect complex formation extracted

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#268]
In PMC4329006: 
`We provide evidence and a model illustrating how oncogenic, activated Ras can increase the DNA binding and transcription function of SAF-1 / MAZ transcription factor, a transcriptional regulator of VEGF.` 
is extracted as `SAF-1 forms a complex with VEGF` by the ominously named `binding3wrong` rule.

**Comment by myedibleenso** [comment]
>by the ominously named binding3wrong rule.

ha!
