### ISSUE TITLE
Incorrect NER labeling of entities

### ISSUE THREAD

**Issue by hickst** [clulab/reach#274]
1) The proteins 'Smad 2', 'Smad 3', 'Smad 4', etc. are *already* in the Uniprot KB (in this form).
2) They appear in the ...kb/ner/Gene_or_gene_product.tsv.gz file (ex: 'SMAD 2')
3) They are not overridden in the NER override file.
4) The shorter entry 'SMAD' *does* appear in the NER override table as a family.

The number SMADs should be identified/labeled as GGP and later grounded with correct uniprot ID, but that is not happening which results in 'smad' labeled as a Family and '2' being ignored altogether.

I suspect that some component of NER resolution is not using the longest prefix string available.

**Comment by MihaiSurdeanu** [comment]
@hickst: I can't replicate this issue in processors. See the last 2 tests in this file:
https://github.com/clulab/processors/blob/master/src/test/scala/org/clulab/processors/TestBioNLPProcessor.scala

They both pass. If you find a NER situation that fails related to this issue, can you please add a unit test for it in processors? If it's a grounding issue, can you please take over?

**Comment by hickst** [comment]
Well, a Processors test is certainly a good first step. But since the NER spans Processors and Reach we should have the same tests in Reach, too. I've added your processor tests (and several others) to the Reach suite in the 'iss274' branch. These tests indicate that grounding contains the necessary entries and is working correctly when given 'smad 2'.

Note the failed result of your same Processors test at the Reach shell:
```
Welcome to ReachShell!

>>> Smad 2 is doing something.
sentence #0
Smad 2 is doing something .
Tokens: (0,Smad,NN), (1,2,CD), (2,is,VBZ), (3,doing,VBG), (4,something,NN), (5,.,.)
smad 2 be do something .
roots: 3
outgoing:
	0: (1,num)
	1:
	2:
	3: (0,nsubj) (2,aux) (4,dobj)
	4:
incoming:
	0: (3,nsubj)
	1: (0,num)
	2: (3,aux)
	3:
	4: (3,dobj)

entities:
mention text: Smad
List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)
	------------------------------
	Rule => ner-gene_or_gene_product-entities
	Type => CorefTextBoundMention
	------------------------------
	Protein|List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController) => Smad
	grounding: KBResolution(smad, uaz, UAZ-PF-214, human)
	------------------------------
```

**Comment by hickst** [comment]
This debugging statement in ReachEntityLookup:
```println(s"(resolveMention): Request to resolve '${mention.text}' with label: ${mention.label}")```

Seems to show that 'smad 2' in the input causes a call to grounding with *only* 'smad' as the text (but with the correct GGP label from the Processors part of the NER):
```(resolveMention): Request to resolve 'Smad' with label: Gene_or_gene_product```

Does this imply that we are missing an NER rule to consolidate multiple tokens labeled as GGP?

**Comment by MihaiSurdeanu** [comment]
No, those rules exist.
I suspect this is in grounding?

**Comment by hickst** [comment]
I've just written multiple passing tests which show that grounding contains the correct entries and that grounding returns the correct ID when given the string 'smad 2'. The debugging output given in the previous comment is the *first* statement in the first top-level call to grounding and it shows that grounding is being handed a mention whose text is 'smad' for the input 'smad 2'.

**Comment by MihaiSurdeanu** [comment]
Ok, then I'm lost. Clearly something gets lost between the NER and
grounding. Can you please try to trace it down?

**Comment by hickst** [comment]
Yes, of course...I will continue looking into where it is happening.

**Comment by hickst** [comment]
As I suspected, this appears related to the failure of rules which consolidate GGP tokens. I am inputting the sentence 'Smad 2 is doing something'. There are two (level 3) rules (shown below) which should match on the input token sequence (B-ggp I-ggp), which is being correctly produced by the processors NER labeling phase for the text 'Smad 2'. The 'ner-family-entities' rule, however, looks (to my inexperienced eye) like it should fail, as the GGP-labeled token sequence is not followed by 'protein' and/or 'family'.

The output I expect is a single mention, labeled 'Gene_or_gene_product', with the consolidated text ('smad 2') of the two matched tokens. Here are the rules I *think* are causing the problem:

```
- name: ner-gene_or_gene_product-entities
  label: Gene_or_gene_product
  action: mkNERMentions
  priority: 3
  type: token
  pattern: |
    [entity='B-Gene_or_gene_product' & !word=/(?i)^([ACDEFGHIKLMNQRSTVWY]?\d+_|Delta)?[ACDEFGHIKLMNQRSTVWY]?\d+(del|ins|dup|fs)?[ACDEFGHIKLMNPQRSTVWY]*$/]+
    [entity='I-Gene_or_gene_product' & !word=/(?i)^([ACDEFGHIKLMNQRSTVWY]?\d+_|Delta)?[ACDEFGHIKLMNQRSTVWY]?\d+(del|ins|dup|fs)?[ACDEFGHIKLMNPQRSTVWY]*$/]*
    # we may see the word "protein"
    # we can't always trust the crf.  Make sure it isn't an obvious family
    (?!
    [lemma=substrate | lemma=family]
    |
    [lemma=protein] [lemma=family]
    |
    [lemma=inhibitor & !entity=/Gene_or_gene_product/]
    )

# TODO: verify this ontology
- name: ner-family-entities
  label: Family
  action: mkNERMentions
  priority: 3
  type: token
  pattern: |
    [entity='B-Family']+ [entity='I-Family']* (?! [lemma=substrate] | [lemma=inhibitor & entity=/Family/])
    | # we can't always trust the crf.
    [entity='B-Gene_or_gene_product']+ [entity='I-Gene_or_gene_product']*
    # only allow the GGP NER label iff lemma of next tok is "family"
    (?=  [lemma=protein]? [lemma="family"])
```

**Comment by hickst** [comment]
I also note that both call the action 'mkNERMentions' which **says** that it prevents the creation of overlapping mentions. This *might* be relevant (as 'smad' occurs as a Family and 'smad 2' occurs as a GGP in our KBs) BUT I can't figure out how a clash would ever occur as the processors NER is correctly labeling 'smad 2' as two consecutive GGP tokens.

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: can you please fix this? Note that single digits are valid parts of a protein name (e.g., "Smad 2").

**Comment by myedibleenso** [comment]
I wish those patterns had been commented, but it looks like those were constraints added to avoid slurping up mutants.  Yeah, I can fix this...

**Comment by MihaiSurdeanu** [comment]
Thanks!

**Comment by hickst** [comment]
Gus rewrote the complex and errant rules, which now pass my tests (pull request #281)
