### ISSUE TITLE
Reach master won't process Dry Run 3 files

### ISSUE THREAD

**Issue by hickst** [clulab/reach#284]
Too many changes seem to have been made to the master branch without any testing on real-world files (tests must have passed, of course). Running the AssemblyCLI on the 5 files from DryRun3 produces no output as all files fail with assertion errors (see attached run log) about passageMap missing the current chunkId.

Note that no new assertions were added recently, so this code used to work.

[run-asscli.txt](https://github.com/clulab/reach/files/385329/run-asscli.txt)

**Comment by myedibleenso** [comment]
What is the `passageMap` and how is it built?

**Comment by myedibleenso** [comment]
If the assertions are critical, maybe we should add tests to ensure they aren't failing.

**Comment by myedibleenso** [comment]
@hickst, I believe this is the problem: https://github.com/clulab/reach/blob/4f96bc36ba2fd9913171f86a7dbf683cafa3be27/src/main/scala/org/clulab/reach/AssemblyCLI.scala#L86

If we just change the chunk to anything other than "" I'm guessing it will fix it.

**Comment by myedibleenso** [comment]
Well, that didn't work.  Looking into it a little deeper, it seems the chunkID has to match what `getChunkID` (in `FriesOutput`) returns.  This is sort of pointless now that we're using only a single `FriesEntry`, but so it goes.

**Comment by myedibleenso** [comment]
I did some refactoring on this (see the `issue284` branch), but it didn't solve the problem.  I'm out of ideas at the moment...
