### ISSUE TITLE
Complex name matches multiple entity rules

### ISSUE THREAD

**Issue by danebell** [clulab/reach#29]
Ras-GDP is Ras bound to GDP (and thus "inactive"), but it's matching twice, so we get twice as many events as we should.

List(Gene_or_gene_product, BioChemicalEntity, MacroMolecule, PossibleController)
	------------------------------
	Rule => ner-gene_or_gene_product-entities
	Type => BioTextBoundMention
	------------------------------
	Protein|List(Gene_or_gene_product, BioChemicalEntity, MacroMolecule, PossibleController) => Ras-GDP
	xref: Xref(uazid,UAZ00001)
	------------------------------

List(Simple_chemical, Missing, BioChemicalEntity, PossibleController)
	------------------------------
	Rule => missing-simple_chemical
	Type => BioTextBoundMention
	------------------------------
	Simple_chemical|List(Simple_chemical, Missing, BioChemicalEntity, PossibleController) => Ras-GDP
	xref: Xref(uazid,UAZ00001)
	------------------------------

**Comment by myedibleenso** [comment]
This seems to be fixed now:

```
>>> Ras-GDP
sentence #0
Ras-GDP
Tokens: (0,Ras-GDP,NNP)
roots: 0
outgoing:
incoming:


entities:
mention text: Ras-GDP
List(Gene_or_gene_product, MacroMolecule, BioChemicalEntity, Entity, PossibleController)
	------------------------------
	Rule => ner-gene_or_gene_product-entities
	Type => CorefTextBoundMention
	------------------------------
	Gene_or_gene_product|List(Gene_or_gene_product, MacroMolecule, BioChemicalEntity, Entity, PossibleController) => Ras-GDP
	xref: Xref(uazid,UA-BP-GGP-00141)
	------------------------------


events:
==================================================
```
