### ISSUE TITLE
Allow token-based match restriction prior to dependency in Odin

### ISSUE THREAD

**Issue by danebell** [clulab/reach#30]
For example:

theme:BioChemicalEntity+ = prep_of ([lemma=member] nn+ | [!(lemma=member)] nn*)

This would mean that you either have a lemma matching 'member' with at least one nn dependency, or any other lemma with at least zero nn dependencies. Right now this has to be written as:

theme:BioChemicalEntity+ = prep_of [lemma=member] nn+ | prep_of [!(lemma=member)] nn*

**Comment by marcovzla** [comment]
This has been possible for a while now.
