### ISSUE TITLE
'senescence' is a bioprocess, not a protein family

### ISSUE THREAD

**Issue by danebell** [clulab/reach#301]
`senescence` is now recognized as a protein family by the NER, when it should be a bioprocess. For completeness, it might be worth doing a set intersection on the Family kb and BioProcess kb (since the latter is less than 300 members) to check for other instances of this problem.

**Comment by hickst** [comment]
Sadly, it is both! [Senescence](http://pfam.xfam.org/family/senescence)
*BUT*, since this is a plant family protein, I will override the family in favor of the bioprocess.
Good idea on the overlap check: I haven't done that check since mid-May. I'll do it again and post the results here.

**Comment by hickst** [comment]
I forgot to mention that the overlap check turned up 5 redundant, duplicate entries in the table, so thanks for that. I'm testing Proc and Reach now, but these fixes should appear soon in the BR 1.1.15-SNAPSHOT.

**Comment by hickst** [comment]
@danebell Good news: I redid the overlap computation and 'senescence' was (still) the only overlap between bio_processes and PFAM.

**Comment by hickst** [comment]
Closed by recent updates to Bioresources 1.1.15-SNAPSHOT.
