### ISSUE TITLE
produce `complexes-with` relation for complex mentions

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#306]
We are currently capturing complex mentions as binding events among its participants.
We need to represent this in the output as `complexes-with` relation

**Comment by marcovzla** [comment]
Complexes were captured in #303

**Comment by hickst** [comment]
Depending on how this is implemented, the outputter may need to be changed to accomodate this also so I'm adding myself, too.

**Comment by MihaiSurdeanu** [comment]
There are two situations:
- A Binding event serves as Controller of an act/reg. In such situations, Gus's code should "flatten" this event into its output entity, i.e., the corresponding Complex entity. This applies to any kind of Binding, binary of not. Please ask @myedibleenso to handle this.

- A n-ary Binding event occurs standalone in the text, e.g., "We experimented with the A-B-C complex". In these cases, we do not do anything. We simply report an n-ary Binding. Hans promised to convert this into a complexes_with relation in the index card format. @marcovzla, please email Hans about this situation, with an example (even if artificial), and tell him about the needed conversion. Cc me and Tom please.

**Comment by hickst** [comment]
Send sample output to Hans and Cheryl.

**Comment by myedibleenso** [comment]
>A Binding event serves as Controller of an act/reg. In such situations, Gus's code should "flatten" this event into its output entity, i.e., the corresponding Complex entity. This applies to any kind of Binding, binary of not. Please ask @myedibleenso to handle this.

This doesn't really sound flattened, but I can do it.  We just throw away the trigger and change the label from `Binding` to `Complex`, right?

**Comment by MihaiSurdeanu** [comment]
Yes. But I think the fundamental difference there is the Complex should be
an entity (it's the output of the event), whereas Binding is the event
itself. In the end this is semantics though. As long as you can uniquely
identify these for Hans, we're good.

**Comment by marcovzla** [comment]
What about a Binding that was split into binary bindings? should we attempt to put it back together? or just create several binary complexes?

**Comment by myedibleenso** [comment]
@marcovzla, it might be easier if you give him an example to look at.

**Comment by myedibleenso** [comment]
I'm guessing no, though.

**Comment by MihaiSurdeanu** [comment]
Just create several binary complexes. Remember that we only do this if they
serve as Controllers for act/reg. In such situations, I think the text is
more likely to state something like "the A-B... complex regulates
something" than "the binding between A, B, and C regulates something".

**Comment by myedibleenso** [comment]
Yeah, this is already being done.  Will put in a PR for the tests.

**Comment by hickst** [comment]
Attached is the FRIES event output JSON for this text:
```
The Mek-Ras-Akt1 complex is not well-studied but we know that the Mek-Ras-Akt1 complex activates ASPP1. The binding of MEK and RAS also activates ASPP1.
```

[PMCiss306.uaz.events.json.txt](https://github.com/clulab/reach/files/400472/PMCiss306.uaz.events.json.txt)

It looks good to me but I would appreciate a review to see if this is what is expected.

**Comment by marcovzla** [comment]
LGTM
