### ISSUE TITLE
Reach Errors in 1k run

### ISSUE THREAD

**Issue by hickst** [clulab/reach#309]
I ran the current system against the 1,000 papers in:
`/net/kate/storage/data/nlp/corpora/pmc_openaccess/darpa_eval_mar2016/Top1Kof16K/nxml/`

Configuration:
* Bioresources (master) 1.1.15-SNAPSHOT
* Processors (master) 5.9.4-SNAPSHOT w/ build using BR 1.1.15-SNAPSHOT
* Reach (iss285) 1.3.2-SNAPSHOT w/ build using BR 1.1.15-SNAPSHOT and Proc 5.9.4-SNAPSHOT

There are still 16 papers processing but, so far, 957 have  finished successfully and 27 papers failed with errors (log file with errors attached below). A quick review shows about 1/2 dozen different types of errors, including:

1. NXML document reading,
2. darpa.MentionFilter problems, 
3. events missing from the eventMap in Fries outputter, and
4. a couple of odd ones: `Entity argument [apoptosis [mods: }]] not in entityMap`
5. empty iterator errors in Assembly

[1k-log.txt](https://github.com/clulab/reach/files/401356/1k-log.txt)

**Comment by myedibleenso** [comment]
I've pared down the log to just the errors (attached).

[1k-log-errors-only.txt](https://github.com/clulab/reach/files/401457/1k-log-errors-only.txt)

# Error classification
Would be nice to open an issue for each type of error we're getting.  Right off the bat I'm seeing...

- "requirement failed: children list is empty"
   - `NxmlReader` error that occurred *6* times
     - assigned to @marcovzla

- "key not found: controller"
  - that's the `MentionFilter` error  that occurred *4* times 
  - assigned to @myedibleenso

- "next on empty iterator"
  - happened once.   It's apparently an assembly thing and I'm guessing a corner case.  
  - assigned to @myedibleenso

- all of those "X not found in entity/event map" errors
  - occurred **13** times
  - These will be the hardest to debug (I have no idea at this point), but I probably introduced them via flattening and/or filtering so I'll take responsibility for them...😭
  - assigned to @myedibleenso 

# Timeline
I suspect the `MentionFilter` and empty iterator will be easy fixes (I could possibly address them today, but before Saturday).

The "X not found in entity/event map" will take an unknown amount of time (sometime before the eval).  Hopefully I get lucky and they end up all being related to one another and simple to fix...


# Question
I'm not really familiar with the exporter logic, but as a temporary solution is it possible to just update the entity/event map whenever we find one of these missing guys?

**Comment by MihaiSurdeanu** [comment]
Thanks @hickst! Good idea to run over the 1K set.

The "X not found in entity/event map" is a logic error: we first export the simple events, then the regulations that operate on top of these simple events. This error is triggered when such a simple event is not found. I would prefer we understand the error, rather than hack it. 

@marcovzla: can you please look at the NxmlReader error?

**Comment by hickst** [comment]
I'm also worried that the job has not finished: 7 hours after I filed this issue, only 7 more papers have finished! So 984 papers finished (or failed) in 6.5 hours and then, so far, only 991 papers have finished in ~14 hours. So, it appears that some few papers take a HUGE amount of time. I also note the oddity that, starting with 24 threads, I have only 2 still active.

**Comment by hickst** [comment]
@mihai I'm more worried about the two outputter *entity* errors (than the event errors), as I have never seen these before and I don't understand how the initial pass over the entities failed to put them in the entityMap.

**Comment by myedibleenso** [comment]
Why not just kill it and provide a list of those papers that are hanging?

**Comment by MihaiSurdeanu** [comment]
I'm not sure either... it would help a lot of you could identify the
sentences where it happens....

**Comment by hickst** [comment]
@myedibleenso Yea, I could certainly do that but this is a systemic problem that happens every time I run a batch of papers: they slow way down toward the end, I lose most of the processing threads that I started with, and some few papers take a **huge** amount of time (this last point might explain the loss of threads -- perhaps they are tied up with the outlier-slow files).

For example the current log shows the last file that finished (this morning at 6:49 am) took 28611 seconds to process -- that's almost **8 hours** for one file!

**Comment by myedibleenso** [comment]
Can you try running one of those files on its own?  Maybe you could send me one so that i can start debugging/narrowing down where the problem is...

**Comment by MihaiSurdeanu** [comment]
I'm not too worried about that. We found out in the past that these are
actually conference proceedings, which actually contain ALL the papers from
a conference. This won't happen during the evaluation.

**Comment by myedibleenso** [comment]
I think @MihaiSurdeanu is probably right about those few papers, but can we confirm that's the case here?

**Comment by hickst** [comment]
That last file that ran so long was PMC4408443 and it turns out it is a monster file: 1446704 bytes. Perhaps we just need to filter out files over a certain size. They tend to be "not really papers" in many cases: poster sessions, special publications, or article collections.

**Comment by hickst** [comment]
I think it's confirmation of what he said. :)

**Comment by myedibleenso** [comment]
Ok, one less thing to worry about.

**Comment by hickst** [comment]
I killed the job....there were no more errors after the initial filing of this issue last night so Gus' analysis is up-to-date.

**Comment by hickst** [comment]
I've collected all the input NXML files which failed with errors in:

/net/kate/storage/data/nlp/corpora/pmc_openaccess/darpa_eval_mar2016/1krun-error-files_160804

**Comment by hickst** [comment]
Status: Mention filter and feature extractor changes, and the FRIES outputter rewrite have reduced the number of failing files in the 1K run from 27 to 3. Two of the 3 are NXML reader errors (separate issue #314). The last error, Gus thinks was a possible Coref issue and Dane was investigating it.

**Comment by hickst** [comment]
This may be an assembly event, so Gus and I have re-assigned ourselves to this one.

**Comment by hickst** [comment]
This issue is still present even after fixes of all known bugs in the FRIES outputter.

**Comment by myedibleenso** [comment]
@hickst, can you clarify your last comment?   What is the remaining error for this issue?

**Comment by hickst** [comment]
Remaining 3 errors separated into issues #314 and #322 so I am closing this issue.
