### ISSUE TITLE
Text in the Nxml standoff mismatches text in the processors document

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#316]
## Bug
Since the nxml document instance is constructed by the `NxmlReader` class _before_ `ReachSystem` creates a document object, the standoff is built using the original, not-romanized unicode text.

This creates a mismatch between the offsets in the `Sentence` objects and messes with the sentence splitting.

Here is an example:

* __Original text:__ 
```
HEK-293 cells , stably expressing AMPK [ \xce\xb11 WT ( wild-type ) , \xce\xb11-S487A or \xce\xb12 WT as indicated ] were grown to \xe2\x89\x88 80 % confluence and then serum starved for 16 h. Cells were then treated as described in the Figure legends .
```

* __Preprocessed text:__ 
```
HEK-293 cells , stably expressing AMPK [ alpha1 WT ( wild-type ) , alpha1-S487A or alpha2 WT as indicated ] were grown to = ~ 80 % confluence and then serum starved for 16h .'
```
 and 
```
Cells were then treated as described in the Figure legends .
```

## Proposed solution
Run proc.preprocessText over the text _before_ constructing the nxml document object
```scala
val text = io.Source.fromFile(file).getLines.mkString("\n")
val preprocessedText = reach.processor.preprocessText(text)
val nxmlDoc = nxmlReader.parse(preProcessedText)
```

**Comment by MihaiSurdeanu** [comment]
I agree.
MIhai
