### ISSUE TITLE
Unable to process CSV files from Natasa

### ISSUE THREAD

**Issue by hickst** [clulab/reach#324]
All her CSV files get same error: java.nio.charset.MalformedInputException: Input length = 1 (stack trace below). I tried converting all files using dos2unix -- same errors.

I notice that *none* of the files include an entry containing the document title (the first entry is the abstract) but don't know if this is a problem. I tried adding a title line to one file and it failed in exactly same way as before.

A failing file is attached (extension renamed to .txt because of stupid GitHub restriction).
[PMID7514175.csv](https://github.com/clulab/reach/files/434017/PMID7514175.csv.txt)

```
paper: PMID9597127

error:
java.nio.charset.MalformedInputException: Input length = 1

stack trace:
java.nio.charset.CoderResult.throwException(CoderResult.java:281)
sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
java.io.InputStreamReader.read(InputStreamReader.java:184)
java.io.BufferedReader.fill(BufferedReader.java:161)
java.io.BufferedReader.readLine(BufferedReader.java:324)
java.io.BufferedReader.readLine(BufferedReader.java:389)
scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
scala.collection.Iterator$class.drop(Iterator.scala:364)
scala.collection.AbstractIterator.drop(Iterator.scala:1336)
org.clulab.reach.utils.DSVParser.toFriesEntries(DSVParser.scala:39)
org.clulab.reach.utils.DSVParser.toFriesEntry(DSVParser.scala:74)
org.clulab.reach.PaperReader$.getEntryFromPaper(PaperReader.scala:110)
org.clulab.reach.ReachCLI.processPaper(ReachCLI.scala:103)
org.clulab.reach.ReachCLI$$anonfun$2.apply(ReachCLI.scala:53)
org.clulab.reach.ReachCLI$$anonfun$2.apply(ReachCLI.scala:49)
scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by myedibleenso** [comment]
Probably what we need is an input specification (ex. column 1 = X, column 2 = Y, etc.) for the dsv (csv/tsv) files.

**Comment by myedibleenso** [comment]
If you open it up, it looks like the file isn't formatted correctly (see lines 4-47).  There are a bunch of lines where it's just part of the text from some section in the paper.  Also the encoding is wonky.  I am about to push a "fix" for the encoding issue, but the formatting is another problem...

The `DSVParser` could be rewritten via the `application.conf` to allow for more flexibility in the input file formats.  Alternatively, we could simply include documentation that requires users to prepare their `.csv`/ `.tsv` files in the following format:

#Expected Format

## Header 
**required** 
`csv` header example: `PMCID,CHUNK ID,TEXT,MY CUSTOM THING 1,MY CUSTOM THING 2,SECTION ID`

## column 1  
PMCID  
## column 2  
chunk ID (could be blank)  
## column 3    
text  (**required**)
## final column 
section ID (could be blank)

**Comment by MihaiSurdeanu** [comment]
Tom, can you please document what's wrong with the format and let Natasa
know?

**Comment by hickst** [comment]
Wow, I never looked at this particular file but the problem is obvious in this one. I looked at several others where the problem is not so obvious. I picked this one because it was the smallest one that failed (that was clearly a mistake)!

**Comment by myedibleenso** [comment]
Just to reiterate: the files should a) have  header and b) contain three columns: PMCID, chunk ID (could be blank), and text

**Comment by hickst** [comment]
Yes, and that's what the sample I sent her had. Thanks!

**Comment by myedibleenso** [comment]
As far as the encoding issue goes, I'm not sure if this is an acceptable solution: https://github.com/clulab/reach/compare/dsv-parser-encoding

**Comment by hickst** [comment]
Refined and separated into issue #339
