### ISSUE TITLE
Negative feedback regulation and activation

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#326]
From the sentence `ERK activation induces several negative feedback regulators of EGFR signaling including SPRY2.`, two events are extracted: `ERK negatively activates EGFR` and `SPRY2 positively activates EGFR`. 

Let's set aside the complexities of disambiguating what is meant by `EGFR signaling` and assume that `EGFR activity` is a proxy for `EGFR signaling`. I think then the correct extractions here would be `ERK positively activates SPRY2` and `SPRY2 negatively activates EGFR`.

**Comment by MihaiSurdeanu** [comment]
We need to improve "polarity flipping" code.

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: this is hard: we would have to transfer the negative trigger ("negative") from the first activation to the second. Not sure how to do this... Any ideas? If not, I think we should take the hit on this one...

**Comment by myedibleenso** [comment]
If it bothers you to have it open, we can close it.  That said, I think these kinds of issues should be marked as unsolved in case we decide to revisit at some point in the future.  Simply closing it without a record to that effect gives the false impression that it's been "solved".

**Comment by MihaiSurdeanu** [comment]
Good point. Can you please mark it as unsolved as well?
