### ISSUE TITLE
Roles reversed in negative activation event

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#327]
In this sentence: `EVH1 domain mutations with reduced binding to the GRD also disrupted the ERK suppression activity of SPRED1.`, the `ERK suppression activity of SPRED1` phrase should yield `SPRED1 negatively activates ERK` but instead the event `ERK negatively activates SPRED1` is extracted.

**Comment by MihaiSurdeanu** [comment]
We'll take a look. This might be a syntax issue...

**Comment by MihaiSurdeanu** [comment]
@bgyori: But if the text were `ERK suppression of SPRED1` than the event `ERK negatively activates SPRED1` would be correct?

**Comment by MihaiSurdeanu** [comment]
@bgyori: What about the text `ERK suppression regulation of SPRED1` (I know this is a bit artificial)?

**Comment by bgyori** [comment]
I've been thinking about this and deciding on `ERK suppression of SPRED1` out of context and without assuming domain knowledge is not really possible. For instance, `Vemurafenib suppression of BRAF` has the same pattern and since Vemurafenib is a drug targeting BRAF, it's obvious that the interpretation is `Vemurafenib negatiely activates BRAF` and not the other way around. 
So perhaps the rule just shouldn't apply to this pattern unless there is additional context?

For `ERK suppression regulation of SPRED1` I would go with the `SPRED1 negatively activates ERK` interpretation.

**Comment by MihaiSurdeanu** [comment]
I really don't know what to do here...
@bgyori: this might be an assembly issue? That is, we do the best we can using *just* the textual information. Then, on your side, you flip the participants using domain information?

Closing for now. But happy to reopen if we have a better solution.
