### ISSUE TITLE
Confounding events affecting protein _amount_ with protein _activity_

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#328]
This is more systemic issue that I wanted to bring up. In cell biology the process in which one protein regulates the _amount_ of another protein and the process in which one protein regulates the _activity_ of another protein are different and should therefore be differentiated in REACH extractions. The former, that is, the regulation of the _amount_ of a protein can happen via transcriptional regulation or, for instance, the regulation of protein degradation. The latter, that is, the regulation of the _activity_ of a protein typically happens via post-translational modification, or, for instance, translocation.

Consider the sentence `Ets-1 upregulates MMP-9 expression triggered by TGF-beta1 and TPA via MAPK signaling`. Here Ets-1 is understood to affect the _amount_ of MMP-9 protein, not its _activity_. Currently REACH extracts that `Ets-1 positively activates MMP-9`, which is not correct.

To solve this problem, I believe, REACH would need to be extended with events describing the expression of proteins and then allow regulations on this process.

**Comment by bgyori** [comment]
Another example of the same problem: `Therefore, we hypothesize that loss of neurofibromin in monocytes and macrophages enhances ROS production [...]. `. Here ROS refers to reactive oxygen species (not proteins) whose _amounts_ are important for the cell. The event extracted should reflect that neurofibromin increases the amount of ROS, but instead, currently, neurofibromin is extracted as a positive activator of ROS.

**Comment by MihaiSurdeanu** [comment]
Solution:
1. Add a simple event, Amount or Expression.
2. This is modeled as a Regulation, just like any other simple event. It should just work.
3. Modify the Fries format to allow for the new event.
4. Profit.

**Comment by MihaiSurdeanu** [comment]
Dane, Gus - add the new simple event.
Tom - output

**Comment by MihaiSurdeanu** [comment]
@bgyori: what triggers should we be using for detecting that it's about amounts: "expression", "production". What else?

**Comment by johnbachman** [comment]
"level(s) of"

**Comment by bgyori** [comment]
+ amount of, transcription of

**Comment by danebell** [comment]
Should this event type be merged with [the currently inactive type `Transcription`](https://github.com/clulab/reach/blob/master/src/main/resources/org/clulab/reach/biogrammar/inactive/transcription_events.yml)?

**Comment by johnbachman** [comment]
No, because there are many post-transcriptional ways of regulating protein abundance (mRNA stability, microRNAs, translation efficiency, protein stability, etc.).

**Comment by johnbachman** [comment]
But, having a Transcription type would be very useful! It would allow REACH-assembled networks to be used to explain transcriptional data, which is very abundant and relatively easy to obtain.

**Comment by danebell** [comment]
Would you say then that `Transcription` is a special case of `Amount`? If so, are there other special cases that are crucial to capture?

**Comment by johnbachman** [comment]
Yes, I think so. In fact we have also (partially) implemented such a hierarchy, with RegulateAmount as the Statement supertype and RegulateTranscription as the subtype.

**Comment by johnbachman** [comment]
There may be other special cases that we can pick up on from language, but they could probably be dealt with later--I would say there would be a big boost in specifically addressing transcription as soon as possible.

**Comment by danebell** [comment]
Okay, this makes sense to me. That shouldn't be an enormous investment, since we already have some rules written. Thanks!

**Comment by johnbachman** [comment]
One other thing that is worth noting--I would say that most often what you will find in papers is some reference to the amount not of the overall protein, but of some specifically modified form. For example, "X increases the amount of phosphorylated Y," or "X increases the amount of Y at the plasma membrane." Here the overall amount of protein Y is not changing, but some modified amount is. So for these extractions to make sense, the key is to correctly pick out the state of Y.

**Comment by danebell** [comment]
If I'm understanding you, "X increases the amount of phosphorylated Y" is equivalent to "X increases the phosphorylation of Y", so we should aim to extract a regulation of a phosphorylation, not a regulation of an amount. That's a very valuable observation.

**Comment by bgyori** [comment]
> If I'm understanding you, "X increases the amount of phosphorylated Y" is equivalent to "X increases the phosphorylation of Y", so we should aim to extract a regulation of a phosphorylation, not a regulation of an amount. That's a very valuable observation.

Yes, that's what I think too. It is a regulation of the _phosphorylation_ of Y, which is different from the regulation of the _overall amount_ / _expression_ of Y.

**Comment by danebell** [comment]
@myedibleenso, @hickst I believe the taxonomy, some admittedly limited rules, and basic tests are in place in the branch `issue328`. Could you please update the export and assembly code to allow the `Amount` events to be well-represented?

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: this is mainly fixed; but assembly needs to be updated for Transcription.

**Comment by hickst** [comment]
I fixed the FRIES output (without Assembly) but Assembly is still causing errors for FRIES output with Assembly and for IndexCards.

On last commit (b49a28) in this branch,  I renamed the Amount subevents to use the previous naming scheme (using underscores). It's not as pretty but it has the big advantage that underscores are converted automatically to hyphens so we get a nice field value of "decrease-amount" instead of "decreaseamount". If everyone hates it we can revert that commit.

**Comment by myedibleenso** [comment]
>but Assembly is still causing errors for FRIES output with Assembly and for IndexCards.

@hickst, can you paste in the error?  Is there a particular test that's failing or a whole slew of them?

**Comment by myedibleenso** [comment]
Ah, nm.  Found the problem...

**Comment by myedibleenso** [comment]
Ok, I've modified the `AssemblyManager` in `reach-assembly` to handle these events.  For the record, I ran it with the following examples and there weren't any hiccups:

```scala
import org.clulab.reach.PaperReader
import org.clulab.reach.mentions._
import org.clulab.reach.mentions.serialization.json._
// assembly has been moved under reach
import org.clulab.reach.assembly.AssemblyManager
import java.io.File

// event examples adapted from those listed in the 
// amount_events.yml, decrease_events.yml, and transcription_events.yml files
val text = "PTEN protein expression was detectable by Western blot in all cell lines. We went on to examine the levels of MCL-1 and BIM expressed in several uveal melanoma cell lines. Indeed, EGFR is overexpressed in 30%-85% patients with CRC. Indeed, expression of the Raf-RBD dramatically decreased Elk-1 dependent transcription by >80% whereas PI3KC2beta-RBD expressing cells were not inhibited further supporting the model that the PI3KC2beta-RBD does not interact with Ras-GTP. When looking at oxaliplatin, it can be concluded that when B-Raf is wild type (regardless of K-Ras mutation), increased levels of p73 protein correlate enhanced TAp73 transcription, in the presence of cetuximab (cetuximab or cetuximab plus oxaliplatin). Phosphorylation of MEK led to expression of NRF2 by Kras.  Phosphorylation of MEK increased ErbB3 gene transcription. Transcription of Kras increased MEK phosphorylation. Phosphorylation of MEK decreased levels of neurofibromin. Phosphorylation of MEK decreased neurofibromin levels."

val cms: Seq[CorefMention] = PaperReader.getMentionsFromText(text).map(_.toCorefMention)
// file is attached to this issue 
// it has the .txt extension because of GitHub's attachment limitations
cms.saveJSON("amount-examples.json", pretty = true)

// barf-less instantiation!
val am = AssemblyManager(cms)
```
[amount-examples.json.txt](https://github.com/clulab/reach/files/512018/amount-examples.json.txt)

I have another pending TODO in `reach-assembly`, after which I will release a new version of that project and then put in a PR with the updated dependency that will close this issue (and another).

**Comment by MihaiSurdeanu** [comment]
Done.
