### ISSUE TITLE
What to do with "XREF_BIBR"?

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#337]
We very frequently find passages in the captured REACH text containing the string "XREF_BIBR" where citations or cross-references would have appeared in the text of the paper. Examples:

* "Moreover, given the previous reports that p19 ARF can inhibit the activity of Myc (XREF_BIBR; XREF_BIBR), the mutual antagonism between Myc and p19 ARF could be explained, at least in part, by their cross regulation at the level of expression and activity (XREF_FIG)." (PMID19114593)
* "This pathological apoptosis appears to be mediated, at least partly, by p53 because genetic or pharmacological inhibition of p53 activation can significantly reduce the frequency of craniofacial defects in Twsg1 -/- and other mouse models (Tcof, Pax3) of craniofacial and neural defects (XREF_BIBR; XREF_BIBR; XREF_BIBR)." (PMID25468951)

Not infrequently, these actually show up as entities in the extractions. Examples:

* Extraction: ```XREF_BIBR activates adhesion,``` from the sentence "Further, adhesion of the aggressive prostate cancer cell line PC3 to fibronectin results in upregulation of survivin and protects the cells from apoptosis induced by TNF-alpha [XREF_BIBR]." (PMID20920299)
* Extraction: ```Wnt activates cardiac repair XREF_BIBR,``` from the sentence "Additionally, gene expression profiling performed after myocardial infarct showed post-injury activation of Wnt signaling suggesting the role of Wnt signaling in cardiac repair XREF_BIBR." (PMID22105346)
* Extraction: ```Phosphoinositide-interacting protein binds XREF_BIBR,``` from the sentence "Downstream of Beclin-1 and VPS34 complex activities that produce phosphatidylinositol 3-phosphate (PI3P), WD repeat domain phosphoinositide interacting protein (WIPI) s sense PI3P and control the localization of ATG9 and its role in autophagy regulation XREF_BIBR, XREF_BIBR, XREF_BIBR, autophagy linked FYVE protein (ALFY) binds PI3P and associates with cytoplasmic protein aggregates and mediates their autophagic degradation XREF_BIBR, XREF_BIBR, XREF_BIBR." (PMID25618581).

And many many others that can be provided upon request. In fact, since we've taken care of adding grounding info for the most frequently occurring ungrounded entities in our corpus, we're finding that the entity "XREF_BIBR" is now our new top ungrounded entity.

Are we making a mistake in how we are processing the REACH JSON? That is, are the XREF_BIBR references that we find in the extracted text resolved somewhere else in the JSON? Or is the parser actually running on text strings containing "XREF_BIBR"? If it's the latter, I expect you'll see a big boost just by systematically stripping this stuff out, especially if you can do it cleanly from the NXML.

**Comment by MihaiSurdeanu** [comment]
@hickst: add XREF_BIBR to our NER/grounding black list

**Comment by johnbachman** [comment]
While you're at it, blacklist XREF_FIG as well (see first example sentence, above).

**Comment by hickst** [comment]
@enoriega I added these to the Bioresources stop list but the Reach TestNERStopList test fails, claiming that XREF_BIBR entry is still producing a mention. Curiously, XREF_FIG does not produce a mention and that test succeeds. At the Reach shell, XREF_BIBR produces a GGP CorefTextBoundMention.

**Comment by hickst** [comment]
I should have mentioned: because of the modified Bioresources, I'm using
Bioresources 1.1.16-SNAPSHOT and Processors 5.9.5-SNAPSHOT (using BR 1.1.16-SNAPSHOT) and Reach master using them both.

**Comment by myedibleenso** [comment]
That's weird...it sounds like the blacklist may not be working.  Could it be that the blacklist entry is getting tokenized as `["XREF", "FIG"]`?  Probably not, right?   If it were getting split when processing the blacklist I would expect it to be tokenized the same way everywhere else...

The rule that produced the mention was `ner-gene_or_gene_product-entities`, right?

**Comment by MihaiSurdeanu** [comment]
I'll look at this.

**Comment by MihaiSurdeanu** [comment]
The stop list in bioresources only applies to entities with lower case or upper case. Since XREF* were all upper case, the override did not apply. I fixed this in processors with separate code. This change has been merged in master. I also removed XREF* from the bioresources stop list since they are no longer needed.

**Comment by MihaiSurdeanu** [comment]
I added a new test in the Reach TestNERStopList, and it passes as well.
I will release processors 5.9.5 next.

**Comment by MihaiSurdeanu** [comment]
5.9.5 has been released. @hickst, when you can, please update the build file for reach.

Closing this issue.

**Comment by myedibleenso** [comment]
@MihaiSurdeanu: for the record, can you outline the procedure for adding a **case-sensitive** entry to the NER blacklist?  It sounds like this can't be done in bioresources...

**Comment by MihaiSurdeanu** [comment]
The entries in the NER blacklist are matched in case-insensitive way. BUT, the override is only triggered if the original text in the paper is lower case or upper initial.

**Comment by johnbachman** [comment]
Presumably this is addressed by the recent fix, but I also just found that the string "XREF_BIBR-XREF_BIBR" also appears frequently in our results.

**Comment by johnbachman** [comment]
And here's another one, with a bracket: "XREF_BIBR]"

**Comment by johnbachman** [comment]
And also "XREF_SUPPLEMENTARY"

**Comment by MihaiSurdeanu** [comment]
All things starting with XREF_ are covered.
