### ISSUE TITLE
Problems with complex formation from ligation

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#338]
We encountered a few suspicious extractions of complex formations based on the occurrence of the word `ligation`. 

Two sentences where this seems to be the issue are:
- It has been reported that there is increased activity of MAPKs with ligation of ICAM-1, VCAM-1 or E-selectin ligation in epithelial and endothelial cells.
- Rac GTPases are activated by a broad array of extracellular stimuli relevant to RA, including chemokines, lymphocyte antigen receptor ligation, inflammatory cytokines, and cell-cell adhesion

from which `ICAM-1 binds VCAM-1` and `antigen binds antigen receptor` are extracted, respectively.

I tried a few synthetic sentences and I found that `antigen receptor ligation` in itself doesn't result in any events being extracted but `lymphocyte antigen receptor ligation` produces the previously seen `antigen binds antigen receptor` event. 

The rule being implicated is `binding7a`.

**Comment by MihaiSurdeanu** [comment]
@bgyori: So, should we extract these complexes or not?

**Comment by bgyori** [comment]
No, these two examples I showed are incorrect extractions based on the original sentences. Weirdly enough, the `antigen binds antigen receptor` is technically correct, but how does this rule get that from `lymphocyte antigen receptor ligation`?

**Comment by hickst** [comment]
> It has been reported that there is increased activity of MAPKs with ligation of ICAM-1, VCAM-1 or E-selectin ligation in epithelial and endothelial cells.

What is the correct interpretation of this sentence? (it seems multi-way ambiguous depending on where you attach the "with ligation...." and "in epithelial and endothelial cells"):
1. In epithelial and endothelial cells, there is increased binding of MAPKs to ICAM-1, VCAM-1, and E-selectin OR
2. When ICAM-1, VCAM-1, and E-selectin are bound (by some unspecified process) this increases MAPK activity.

**Comment by johnbachman** [comment]
The latter interpretation (2) is correct. I would guess that this is actually the most common use of "ligation", where the particular ligand is unmentioned. For example, "Ligation of the EGFR receptor activates downstream signaling." There are many possible EGFR ligands so authors don't mention any one in particular.

I've seen a number of examples (don't have the specific sentences/PMIDs handy) where usage of this type leads REACH to spurious dimerization extractions. E.g., there was a sentence involving "ligation of the B-cell receptor" that pulled out ```B-cell receptor binds B-cell receptor.``` Here again the ligand is unmentioned.

In the sentence you quoted, ICAM-1, etc. are cell surface proteins that bind to a variety of cytokines and receptors on other cells (https://en.wikipedia.org/wiki/ICAM-1).

**Comment by johnbachman** [comment]
Also, the appearance of the second ligation (after E-selectin) is just bad English, I would say.

**Comment by bgyori** [comment]
The first sentence basically means: `if a ligand binds  to the ICAM-1 protein or if a ligand binds to the VCAM-1 protein, or if a ligand binds to the E-selectin protein, MAP kinases become activated. The meaning of the sentence is therefore perhaps faithfully captured by `ICAM-1 (indirectly) activates MAPK`, `VCAM-1 (indirectly) activates MAPK`, etc.

**Comment by MihaiSurdeanu** [comment]
@marcovzla: it seems that the practical actions are:
1. Remove "ligation" as trigger word for binding.
2. See why we get `antigen binds antigen receptor` from the sentence "Rac GTPases are activated by a broad array of extracellular stimuli relevant to RA, including chemokines, lymphocyte antigen receptor ligation, inflammatory cytokines, and cell-cell adhesion". This is scary to me: it seems that there are overlapping entities there? That should never happen.

**Comment by MihaiSurdeanu** [comment]
@marcovzla: related to point 2 above. In this other sentence: "Epidermal growth factor receptorvIII mediated cell proliferation and anchorage independent growth is both resistant and stimulated by gefitinib" we extract two overlapping entities: "Epidermal growth factor" and ""Epidermal growth factor receptorvIII", both labeled as GGP. This should not happen: we do not allow overlapping entities at this point. Can you please check? This is similar to the example above.

**Comment by MihaiSurdeanu** [comment]
@marcovzla: we shouldn't allow arguments in a complex that overlap in tokens. See mkRegulation for how I did this for regulations.
