### ISSUE TITLE
Display trait not specific to Bio processing: move to Processors

### ISSUE THREAD

**Issue by hickst** [clulab/reach#34]
We discussed this briefly before the evaluation but the discussion was postponed. I don't see any reason that the Display Trait (with field displayLabel) is specific to BioNLP processing. Generalizing it by moving it to Processors seems like a useful optimization.

**Comment by myedibleenso** [comment]
Has this been done?  If so, can we close this issue?

**Comment by MihaiSurdeanu** [comment]
No, Keep it in Reach.
