### ISSUE TITLE
Bug in syntax_3c_verb

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#342]
The [any_ptm]_syntax_3c_verb rule seems to be buggy and consistently produces incorrect events. Some examples (I can provide more if it helps):
- Expression of SIRT1, SIRT2, and acetylated (Ac)-p53 in gastric cancer cell lines.
`-> SIRT1 is acetylated`
- Sirt1 is a deacetylase and can deacetylate proteins in order to regulate cellular function.
`-> Deacetylase is deacetylated`
- This involves cooperation between phosphorylation dependent poly-ubiquitinated cytoplasmic forms of Tax and poly-sumoylated nuclear forms
`-> Tax is sumoylated`
- the expression levels of hepcidin and caspase 8 increased, while those of Bcl-2, Bcl-xL, and phosphorylated Akt significantly decreased.
`-> Bcl-2 is phosphorylated`
- Moreover, accumulation of p62 and polyubiquitinated proteins has been reported in murine cells deficient in autophagy (Atg-5 or Atg-7 deficient mice)
`-> p62 is ubiquitinated`

**Comment by MihaiSurdeanu** [comment]
@danebell: we should fix this rule or remove it.
