### ISSUE TITLE
Create Reach text wrapper

### ISSUE THREAD

**Issue by hickst** [clulab/reach#343]
From Mihai's TODO list: Write the ReachTxt wrapper, which runs Reach on an arbitrary text file.

We need to have this ASAP in order to process the text extracted from CMU's non Open Access papers.

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: you said you'll do this.

**Comment by hickst** [comment]
@terroni assigned to work on the HTML text extraction portion of this task, coordinating with Gus.

**Comment by myedibleenso** [comment]
?

Yes, I'll write the text file reader.  Does this need to be done today?  It seems like there are at least two issues being discussed here...

**Comment by myedibleenso** [comment]
The HTML reader should be it's own issue...

**Comment by MihaiSurdeanu** [comment]
Yes:
1. @terroni will download the HTML files.
2. We need that text wrapper.

**Comment by MihaiSurdeanu** [comment]
But 2 doesn't need to happen today. Early next week is fine.

**Comment by hickst** [comment]
@myedibleenso maybe HTML issue should be its own issue but we need Terron to coordinate with you on the format of the input to the wrapper (and for your valuable advice and guidance :)
