### ISSUE TITLE
Mutants as Controllers does not work?

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#346]
"Gab1 mutant protein enhances EGF-induced activation of the PI-3" does not work, but
"Gab1 protein enhances EGF-induced activation of the PI-3" does

**Comment by MihaiSurdeanu** [comment]
Gus, do you think you can fix this by Monday? (This is BUG2 in our emails)
If not, please let me and @hickst know, so he can restart the big run without it.
Thanks!

**Comment by MihaiSurdeanu** [comment]
Sorry, I meant BUG1

**Comment by myedibleenso** [comment]
I honestly don't know.  I'll take a look tomorrow (Sunday), but it is hard to say at this point...

**Comment by myedibleenso** [comment]
### What I know so far...

Ok, this is really weird.

>Gab1 mutant protein enhances EGF-induced activation of the PI-3.

...produces this mention:

```
mention text: Gab1 mutant protein enhances EGF-induced activation of the PI-3
List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
       	------------------------------
       	Rule => Positive_regulation_syntax_1_verb
       	Type => CorefEventMention
       	------------------------------
       	------------------------------
       	trigger => enhances
       	controlled (List(Positive_activation, ActivationEvent, ComplexEvent, Event, PossibleController)) => EGF-induced activation of the PI-3
       	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => Gab1
       	with 1 modification =>
       		GenericMutant by "mutant"
       			Mutation rule: mutantlate_1
       			Mutation attachment rule: mutantmod_1a
       	------------------------------
```
For some mysterious reason, [that mention disappears right after coref](https://github.com/clulab/reach/blob/5993323a4cf7d61ad5bf6558f110be3287b17205/src/main/scala/org/clulab/reach/ReachSystem.scala#L103).

I have no idea why (yet).

Tomorrow I guess I'll consult the Oracle at Delphi and try to step through `resolveCoref` and `groupMentionsByDocument`.

Anyway, you can verify this is where the mention is dropped by running the provided sentence through the shell on the [`issue346` branch](https://github.com/clulab/reach/commits/5993323a4cf7d61ad5bf6558f110be3287b17205).

Stranger still, if my log is to be believed it seems like that mention hits the `mkRegulation` and passes through its checks EIGHT times (4 before a global event and then another 4 after that) in the `eventEngine` (log is attached).

**Comment by myedibleenso** [comment]
[issue346-log.txt](https://github.com/clulab/reach/files/453800/issue346-log.txt)

**Comment by myedibleenso** [comment]
@danebell, any ideas why a mention (something with the label "Event") that makes its way into coref might not come out the other end?  The only thing I can think of that wouldn't make it through would be an anaphoric expression that you were unable to resolve, but the missing event does not carry the albatross of `Generic_event`.

**Comment by MihaiSurdeanu** [comment]
Thanks Gus and Dane!
This sounds like a bug...

**Comment by danebell** [comment]
@myedibleenso Events are removed if they have required arguments that don't pass the `isComplete` check. But running that sentence with the filter removed doesn't solve the problem. The problem is in `resolveComplexEvents`, where I failed to make an exception for generic mutants. Because there's no resolution for the mutation, the `Positive_regulation` doesn't get carried over. It's probably easier and faster if I fix this bug.

**Comment by myedibleenso** [comment]
Thanks, @danebell!  

Hope it didn't take you too long to figure out what was going on...

If you don't mind, I'd appreciate it if you took charge of this one (sounds like you already know how to fix it).  Once you've fixed the coref part, I believe there is  test that has been commented out that you can use.

**Comment by danebell** [comment]
Update: An additional problem was that the Coref system explicitly ignored ComplexEvents that have ComplexEvents (like activations) as arguments. I've changed this and added an additional test with the errorful sequence. The only remaining TODO is for @myedibleenso to check/confirm whether the debug statements he put in are still appropriate.

**Comment by myedibleenso** [comment]
I think it's fine.  If another example fails, it should now be a little easier to isolate what component is responsible by toggling the log level.  

PR?

**Comment by MihaiSurdeanu** [comment]
If the test passes, yes PR.
