### ISSUE TITLE
sent24 in TestCoreference fails

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#347]
@danebell: sent24 in TestCoreference now fails. We catch a lot of the events in that sentence, so it's almost Ok. But we miss a couple, most importantly a NegAct(Binding(Gab1, p85), PI-3), I think.
Can you please see if you can fix at least this missing event (see my comments in code).

**Comment by cl4yton** [comment]
@danebell: best way to fix is remove the test

**Comment by hickst** [comment]
Closed by pull request #493.
