### ISSUE TITLE
prefixes such as GST, FLAG, His, etc. should be stripped off during grounding (from issue #321)

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#354]
"GST-p85" erroneously grounded to CBFA2T2, instead of p85 (protein family). In general, epitope tag prefixes such as GST, FLAG, His, etc. for fusion proteins should be stripped off during the entity extraction step::

[Evidence(reach, PMID12515821, {}, GST-p85 or either of its SH2 domains could bind to Abi1 (XREF_FIG B) and to various pTyr containing proteins, one of which co-migrated with Abi1 (unpublished data).)]

**Comment by MihaiSurdeanu** [comment]
@johnbachman, @bgyori: can you please tell us what these prefixes are? Also, is there an exhaustive list? Thanks!

**Comment by bgyori** [comment]
Those are experimental tags on proteins, e.g. copied from the internet "The GST Tag. Glutathione S-transferase (GST) is a 211 amino acid protein (26kDa) whose DNA sequence is frequently integrated into expression vectors for production of recombinant proteins."

Handling them correctly leads to bigger questions - one would essentially have to have an understanding and a model of the experimental method to understand the meaning of a sentence that makes a statement about a tagged protein. Maybe in most cases just stripping off the tag and taking the protein that remains as the entity is a good enough heuristic. I think @johnbachman has a better understanding of this so he could elaborate.

**Comment by MihaiSurdeanu** [comment]
We would like to keep the entire String in the name, but ground it using the stripped off version. Best of both worlds for now?

**Comment by hickst** [comment]
OK, but we still need a complete list of what these prefixes can be in order to recognize and remove them.

**Comment by johnbachman** [comment]
You don't need to capture the presence of the GST/His/Flag tag in the extraction (i.e., it doesn't need to be represented as a kind of modification). Similar for fluorescent tags (GFP/Venus/YFP/CFP/mCherry etc.) While these tags can certainly affect function, generally a good study will measure the effect of the tag on the function of the protein and only proceed in cases where the tag doesn't appear to affect the function too much. 

So it's fine to keep the string in the name, but ground it using the stripped off version. I will work on compiling a list of these. Note that other prefix tags include "p-" for phosphorylation, and "wt" or "wt-" for wild-type (non-mutant) proteins--though perhaps you guys are already handling these?

Also, suffixes are common. FYI a prefix before the protein name indicates that the tag is at the protein N-terminus, while a suffix indicates that the tag is at the C-terminus (e.g., GFP-Raf vs. Raf-GFP).

**Comment by johnbachman** [comment]
I've compiled a list of 137 prefixes and suffixes are frequently attached to gene names and included it in the latest bioentities. These were found by reviewing the entities extracted by REACH on 32k papers (70k entities).

https://github.com/sorgerlab/bioentities/blob/master/gene_prefixes.csv

There's a description of entries and categories in the CSV file in the README:

https://github.com/sorgerlab/bioentities/blob/master/README.md

Hope this helps--let me know if you have any questions!

**Comment by MihaiSurdeanu** [comment]
The prefixes from Harvard are here:
https://github.com/sorgerlab/bioentities/blob/master/gene_prefixes.csv

Important points:
- You only care about single word prefixes, e.g., "Ad-Gene", but not multiword ones, e.g., "endogenous gene"
- The very last part of the file (line 117 onwards) has semantic meaning (inhibition). In the future, we need to modify the polarity flipping code for these. This does not affect grounding however. They should be treated like any other prefix.

**Comment by MihaiSurdeanu** [comment]
Mihai: build a specialized NER that recognizes these as proteins/genes, if the prefix is present.

**Comment by johnbachman** [comment]
Hi @MihaiSurdeanu, not sure if this is what you meant about single vs. multi word prefixes, but we do need to pay attention to multiple combinations of the various prefixes/suffixes: "the prefixes/suffixes may be applied additively, for example Myr-Flag-Akt1, indicating myristoylated, FLAG-tagged AKT1; or GFP-KRAS-G12V, indicating GFP-tagged KRAS with a G12V mutation."

**Comment by MihaiSurdeanu** [comment]
@johnbachman: this is a good observation, thanks! @hickst: please sure this is captured in your stripping code. But I was talking about prefixes that appear in separate words, e.g., "endogenous <gene>". These are generally not included in the entities, so they don't need to be handled explicitly.

**Comment by MihaiSurdeanu** [comment]
@hickst: we need to handle generic dashes (e.g., mutations, domains) in the same code here.

**Comment by MihaiSurdeanu** [comment]
@hickst: would a generic record-linkage library help?

**Comment by MihaiSurdeanu** [comment]
@hickst: for example this: http://infolab.stanford.edu/serf/

**Comment by hickst** [comment]
MS suggests iterative stripping. Try the longest match(es) first.

**Comment by hickst** [comment]
Closed by pull request #491
