### ISSUE TITLE
Missing entity E2F

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#368]
In ancient times (circa last May?), coref found an `Activation` with the trigger "upregulates" for the following text (from PMC2721311):

>Cyclin D1 is upregulated by growth factors, like EGF and estrogen, and binds to CDK4/6 and partially phosphorylates RB, which in turn releases E2F. E2F is a transcription factor that targets the cyclin E gene and upregulates it. The cyclin E gene product binds to CDK2 and forms the cyclinE-CDK2 holoenzyme, which then completes the phosphorylation and inactivation of RB.

I think the activation was something like "E2F upregulates cyclin E", which formed a nice precedence relation with the "cyclin E gene product binds to CDK2" from the sentence that follows.

Currently, all we find are a couple of entities (transcription seems questionable here):

```
ENTITIES: 2

MENTION TEXT:  transcription
LABELS:        List(BioProcess, BioEntity, Entity, PossibleController)
DISPLAY LABEL: BioProcess
	------------------------------
	RULE => ner-bioprocess-entities
	TYPE => CorefTextBoundMention
	------------------------------
	GROUNDING: KBResolution(transcription, go, GO:0006351, human)

	CONTEXT: CellLine => List(cellosaurus:CVCL_3502)
	------------------------------



MENTION TEXT:  cyclin E
LABELS:        List(Family, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)
DISPLAY LABEL: Family
	------------------------------
	RULE => ner-family-entities
	TYPE => CorefTextBoundMention
	------------------------------
	GROUNDING: KBResolution(cycline, interpro, IPR028858, human)

	CONTEXT: CellLine => List(cellosaurus:CVCL_3502)
	------------------------------


EVENTS:   0
```

@MihaiSurdeanu, I believe you may have blacklisted certain three-character entities.  Is that what's happening here with [E2F](https://en.wikipedia.org/wiki/E2F)?

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: I checked and processors finds E2F as a GGP correctly. This information is preserved in Document.entities, but there is no Protein entity produced by the entity grammar. Can you please check why? You are more familiar with that grammar than I am. I suspect it is somehow overwritten by a rule in there.

**Comment by MihaiSurdeanu** [comment]
Please use the `e2f` Reach branch for this work. I added a test there in TestEntities, which currently fails

**Comment by hickst** [comment]
I noticed that E2F is the only entry in the NER override KB with that particular pattern. I added NER override entries for `E2E, F2E, F2F, A2A, A2B, B2B, and A2Z` (all with grounding identical to 'E2F'). I then compiled a local Bioresources and Processors and ran the Reach shell on top of them. At the prompt I entered the phrase:
```E2F, E2E, F2E, F2F, A2A, A2B, B2B, and A2Z are proteins.```
GGP entity mentions were produced ONLY for 'A2B', 'B2B', and 'A2Z'. All the rest failed to create any mentions. at all.

I suspect the culprit to be the `ner-gene_or_gene_product-entities` rule in `entities/entities.yml`
It is a hideously complex rule which is undocumented and has caused us trouble before.

**Comment by hickst** [comment]
@myedibleenso what is the status of this issue?

**Comment by myedibleenso** [comment]
>I suspect the culprit to be the ner-gene_or_gene_product-entities rule in entities/entities.yml
It is a hideously complex rule which is undocumented and has caused us trouble before.

This is most likely the problem.

**Comment by myedibleenso** [comment]
Yes, it must be a rule issue.  The token is getting assigned `B-Gene_or_gene_product`: https://gist.github.com/myedibleenso/817b430b41787df4e45b9cf542930da5#file-e2f-doc-json-L10

**Comment by myedibleenso** [comment]
Ok, I understand what's going on.  In the `mkNERmention` action, there is a filter to see if any overlapping entities have already been found.  This is a conservative check to avoid labelling something as a `GGP` that is more likely a `Mutant` or `Site1.  In this case, `E2F` has already been identified as a `SubstitutionMutant` by `mutant_sub1`: 

```yaml
- name: mutant_sub1
  label: SubstitutionMutant
  priority: 1
  type: token
  action: unpackRelations
  example: "K182L"
  keep: false
  pattern: |
    [lemma=/^(mutant|mutation)/]? (?<entity>[word=/(?i)^[ACDEFGHIKLMNPQRSTVWY]\d+[ACDEFGHIKLMNPQRSTVWY](\/[ACDEFGHIKLMNPQRSTVWY]\d+[ACDEFGHIKLMNPQRSTVWY])*$/]) [lemma=/^(mutant|mutation)/]?
```

@danebell, did you write the `mutant_sub1` rule?  Do you know if three-character strings of this sort (`[A-Z]\d[A-Z]`) are more often than not mutants?  Perhaps we should ask some biologists to weigh in...  

This may be indicative of a larger problem (or merely an exceptional case).  How confident are we in our ability to distinguish mutants from proteins?  Should we perhaps attempt a strict ground (exact string) here to avoid creating spurious mutants?

**Comment by myedibleenso** [comment]
>I noticed that E2F is the only entry in the NER override KB with that particular pattern.

@hickst, do you mean you searched for something like `[A-Z]\d[A-Z]` ?  That makes me think that `[A-Z]\d[A-Z]` might more commonly indicate a mutant.

**Comment by myedibleenso** [comment]
Relevant: https://en.wikipedia.org/wiki/Gene_nomenclature#Mutant_nomenclature

I tried querying a Lucene index with this pattern using project odinson. Here are some example matches:

 - [ ] `P2X` (receptor site?)
 - [ ] `P2Y` (receptor site?)
 - [ ] `C1M`
 - [ ] `C4M`
 - [ ] `C4A`
 - [ ] `C4B`
 - [ ] `Q2W`
 - [ ] `Q4W`
 - [ ] `S1P`
 - [ ] `H2A`
 - [ ] `H2B`
 - [ ] `A1C`
 - [ ] `A2A`
 - [ ] `A2B`
 - [ ] `R2X` 
 - [ ] `R2Y` 
 - [ ] `H2A` 
 - [ ] `H2B` 
 - [ ] `C1Q` (some kind of complex?)
 - [ ] `C1R` (a gene?)
 - [ ] `C1S` (a gene?)

**Comment by danebell** [comment]
I did write the mutant rules. AFAIK, `[ACDEFGHIKLMNPQRSTVWY]\d[ACDEFGHIKLMNPQRSTVWY]` is a very, very common (substitution) mutant string. The exceptions you cite above are exactly that. Mutant detection right now is priority 1, but if we put those exceptional cases into a priority 1 rule, I think that the mutant detection rules could be made priority 2 without creating other problems. Then the mutant rules could be amended to ensure they're not capturing existing mentions.

**Comment by myedibleenso** [comment]
Thanks, @danebell.  I hesitate to add a bunch of exceptional cases to any of the rules.  If we care to detect these, perhaps the answer is to call grounding on these mutant candidates, and only promote those without an real entry in one of our KBs.  

Thoughts?  While this will increase precision, it may have an impact on runtime.  @hickst, can you give us a sense of the computational cost of attempting to find a non-mutant grounding for ~10-20 mentions per paper?

**Comment by myedibleenso** [comment]
Do we (successfully) ground mutants?  Do our KBs include entries specific to mutants, or are they grounded to the superclass protein (ex mutant PROTEIN_A -> PROTEIN_A)?  Does the KB resolution produced by grounding have any element that distinguishes between mutant and non-mutant entities?

**Comment by MihaiSurdeanu** [comment]
Since this overlaps significantly with mutants, I propose to not do anything for now.

**Comment by hickst** [comment]
Note that E2F is still not being recognized as any entity and therefore we will miss any sentences containing E2F.
