### ISSUE TITLE
Missing activations?

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#369]
In PMC2808051, we have the following sentence:

>CAMK phosphorylates and activates ERK , and ERK phosphorylates and inactivates p27 .

It seems like we should find two activations (one positive and one negative), but we only find the positive regulations (the phosphorylations with controllers).

I am unsure if this is because of limitations in our rules, or if there is some filter constraint we impose on the output (ex. "prefer regulations over activations").

**Comment by MihaiSurdeanu** [comment]
Double check that we don't get the activation because we prefer the regulation. If so, this is expected behavior.
