### ISSUE TITLE
Generate a tabular format for output 

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#381]
We have this, thanks to Gus.
But make sure it works all the time, even withAssembly = false

**Comment by MihaiSurdeanu** [comment]
A few additional things to add: information if the interaction is direct or indirect (remember that we have this information for regulations; activations are always indirect); and context information (everything there is relevant).

**Comment by myedibleenso** [comment]
Addressed by #399, #396, and #394
