### ISSUE TITLE
#NAME error in excel

### ISSUE THREAD

**Issue by aabutchy** [clulab/reach#384]
The #NAME error has appeared in various fields after translation. I believe that this is a result of starting a cell with a hyphen. 
![name_error](https://cloud.githubusercontent.com/assets/22522429/18954910/1c6fe0b6-8623-11e6-8119-9038036bf811.PNG)

**Comment by hickst** [comment]
I do not understand this issue: the attached image shows neither a '#NAME' error nor a cell starting with a hyphen.

**Comment by aabutchy** [comment]
This was in response to a question Mihai asked me a little while ago. Here are screenshots of the error in excel and here is the same code again but with the error highlighted. It is the same as in the one above, I was just using a search function in the one above so it highlighted what I was looking for. The same error is in line 1484 above. 
![name_error2](https://cloud.githubusercontent.com/assets/22522429/18960148/be7bde42-8636-11e6-9ea6-eceb9d11ae45.PNG)
![name_error3](https://cloud.githubusercontent.com/assets/22522429/18960147/be7b7880-8636-11e6-9f1f-acc95758c711.PNG)

**Comment by MihaiSurdeanu** [comment]
Thanks @aabutchy!

**Comment by MihaiSurdeanu** [comment]
This is not really a bug: we catch "-delta" as an entity, as well as the preceding "C/EBPbeta". This means that the real canonical name for this entity should be "C/EBPdelta". We do not do this normalization at this point. For this reason, the entity remains "-delta", which shows up incorrectly in Excel.
