### ISSUE TITLE
Direct phosphorylation as a single frame vs two frames?

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#39]
I noticed that phosphorylation is always (or at least with everything I tried to parse so far) extracted as 2 frames: a "regulation / positive-regulation" frame which refers to a "protein-modification / phosphorylation" frame as its controlled argument. I think this structure is adequate when parsing a sentence like "A induces the phosphorylation of B." or "The activity of A leads to the phosphorylation of B" but not the best for a sentence like "A phosphorylates B."

For instance, "AKT1 phosphorylates BAD" is broken up as 
AKT1 (regulation / positive-regulation) ((protein-modification / phosphorylation) BAD)

But in this case it is actually AKT1 that directly, physically phosphorylates BAD so the interpretation that "AKT1 positively regulates the phosphorylation of BAD" is more indirect than it should be and a single frame of the form:
AKT1 (protein-modification / phosphorylation) BAD
could instead be extracted with AKT1 flagged as the "kinase" in the event.

Another example is "TORC1 phosphorylates S6 kinase (S6K) and initiation factor 4E binding protein 1 (4E-BP1), both regulators of protein translation". Here again the phosphorylation is direct with TORC1 acting as a kinase on S6K and 4E-BP1. 

Yet another, somewhat special example is "Sunitinib inhibited RET autophosphorylation at Y1062."
Here RET actually directly phosphorylates itself and so a corresponding frame would have RET both as a kinase and a substrate.

**Comment by MihaiSurdeanu** [comment]
Ben,
We are completely agnostic wrt this issue. We followed the 2 frame idea because this is how BioPAX represents this (one is the phosphorylation biochemical reaction, the other is the catalysis). Maybe you and Emek should discuss this? We'd be happy to support the consensus idea.
MIhai

**Comment by bgyori** [comment]
Yes, you are right that BioPAX would encode "A phosphorylates B" as a BiochemicalReaction:
B-unphosphorylated -> B-phosphorylated and a Catalysis by A referring to the reaction. 

To put it another way, I think it would be really valuable if the REACH system would, based on the language of the sentence, differentiate between direct phosphorylation and processes or entities that indirectly have an effect on a phosphorylation process. This, for us is especially important because we treat direct mechanisms very differently from indirect effects in our models. Do you think this is possible?

**Comment by MihaiSurdeanu** [comment]
Ben,
This is in fact what we do internally (we have different grammars for direct vs. indirect phosphorylations). But then we collapse the outputs in the same BioPAX-friendly representation...
I'll have to think how to represent this difference simply. But it is definitely possible.
Mihai

**Comment by MihaiSurdeanu** [comment]
We are in the process of extracting both direct and indirect causal relations from papers. This will however take a while, so I am closing this issue for now.
