### ISSUE TITLE
Read nxml string with ApiRuler?

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#392]
This is a question about the ApiRuler. Currently the `annotateNxml(nxml: String, outFormat: String)` method at
https://github.com/clulab/reach/blob/master/src/main/scala/org/clulab/reach/apis/ApiRuler.scala#L43
seems to only work with an nxml file path as an argument. Is it possible that it _used to_ take an nxml string as an argument? I'm confused because we used this API call with nxml strings, not file names in the past.
In any case, would it be possible to add an API method that allows processing nxml string rather than nxml file?

**Comment by hickst** [comment]
Hi Ben, I think the calls you want for that are in the sister class `Api.scala` in the same package.

**Comment by bgyori** [comment]
Just a remark: it looks like your commit https://github.com/clulab/reach/commit/7b3571356fa02fdee3a9c8a85044d9ec1f8ce220 in October reversed this behavior. Now the ApiRuler annotateNnxml againg takes the nxml string and not the file name.
