### ISSUE TITLE
NER: Handle appositives for detecting abbreviations/acronyms; propagate globally

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#397]

**Comment by MihaiSurdeanu** [comment]
@danebell: can you please send us the code for grounding appositives? @myedibleenso

**Comment by MihaiSurdeanu** [comment]
@danebell: if contradicting with existing ids, add all of them

**Comment by danebell** [comment]
The existing code is [here](https://github.com/clulab/reach/blob/76b06926cf62520960cc08d2633598621e074eef/main/src/main/scala/org/clulab/coref/Coref.scala#L379-L404). The Alias rules are [here](https://github.com/clulab/reach/blob/76b06926cf62520960cc08d2633598621e074eef/main/src/main/resources/org/clulab/reach/biogrammar/coref/alias_template.yml) and are called [here](https://github.com/clulab/reach/blob/76b06926cf62520960cc08d2633598621e074eef/main/src/main/resources/org/clulab/reach/biogrammar/modifications_master.yml)

**Comment by MihaiSurdeanu** [comment]
Thanks! This is a great foundation for this issue.
