### ISSUE TITLE
insulin receptor substrate-1

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#404]
In the sentence: "We now show that mTOR inhibition induces insulin receptor substrate-1 expression and abrogates feedback inhibition of the pathway." we get "insulin receptor" as an entity, instead of the longer match "insulin receptor substrate-1", which, according to our biologist friends exists in Uniprot with id UniProtKB - P35568 (IRS1_HUMAN).

Why is this? This is scary to me, because it may mean that the "longest match" NER heuristic is not doing its job. A simpler explanation might be that the string "insulin receptor substrate-1" does not appear as a synonym in Uniprot?  @marcovzla, @hickst: can you please investigate?

**Comment by hickst** [comment]
We do have "Insulin receptor substrate 1" in our Uniprot KB (without a dash) so this should be found by grounding IFF the NER labels it as a GGP. But, I think you told me the other day that the NER does not remove the dashes when it does its comparison, so I suspect that the dash is preventing NER from labeling this as a GGP.

**Comment by hickst** [comment]
I think this points out the need for a global, common (canonical) treatment of strings (for lookup purposes) which spans several projects and functional levels within projects. I think that the best place in the architecture for such methods would be in a utility class within the Bioresources project, upon which all other projects depend (i.e. the base project).

**Comment by MihaiSurdeanu** [comment]
This was fixed in a recent PR in processors, available in 6.0.1.-SNAPSHOT.

**Comment by hickst** [comment]
Please be more specific when closing an issue: 1) what was done and 2) which pull request fixed it.

**Comment by MihaiSurdeanu** [comment]
In reality there have to be 2 canonicalization procedures:
- One for grounding, which we *do* have. We also normalize casing, remove non-alpha characters, etc. @hickst: where is the code for this? Note that this procedure works by *removing* characters.
- One for NER, which I just added: https://github.com/clulab/processors/blob/master/corenlp/src/main/scala/org/clulab/processors/bionlp/ner/LexicalVariations.scala
This one has to both remove characters (e.g., replace dashes with spaces), and *insert* characters, e.g., add dashes "insulin receptor substrate 1" -> "insulin receptor substrate-1", because we (ideally) should not mess with the input text.

**Comment by hickst** [comment]
The actual canonicalization function is in: 
https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/reach/grounding/ReachKBKeyTransforms.scala#L13-L19

Note that this file is currently changing (in a development branch) to implement the (somewhat misnamed) "prefix stripping" (issue #354).

**Comment by johnbachman** [comment]
Good point, I was overlooking the fact that what I referred to as "raw text" has already been canonicalized by REACH (handling of greek letters, slashes, etc.). I guess the big boost for us would be if all the readers canonicalized strings the same way so that we didn't have to re-curate the same entities. Not sure how the logistics of a shared canonicalization procedure would work though!

**Comment by myedibleenso** [comment]
> I guess the big boost for us would be if all the readers canonicalized strings the same way so that we didn't have to re-curate the same entities.

I can imagine that is a pain.  

Perhaps we could provide an option where we take normalized, tokenized text and run our system against that.  Our trained models and grammars are likely sensitive to many of those normalization decisions, though.

**Comment by MihaiSurdeanu** [comment]
We can certainly discuss this. Ours is a bit ad-hoc.
Mihai
