### ISSUE TITLE
Sub-project "assembly" clashing with "sbt assembly"

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#407]
We have been assembling REACH into fat jars using the sbt-assembly plugin (https://github.com/sbt/sbt-assembly) by running `sbt assembly`. However, this doesn't work anymore, and I suspect this is because of the new `assembly` subproject. I might be missing something obvious but I haven't been able to get `sbt assembly` to work and looking for ideas. Thanks!

**Comment by hickst** [comment]
I have to smile: honestly, I had no idea Ben was doing this when I asked for this feature at last Wednesday's meeting. So now it's an official issue.

**Comment by hickst** [comment]
@bgyori  Marco updated the subproject name so it should no longer clash with the plugin.
When you get the UberJar working, can you please email (or attach) your build file containing the definitions and tasks that create it. Thanks.

**Comment by marcovzla** [comment]
I already added the sbt-assembly plugin to reach, so running `sbt assembly` should work.

**Comment by marcovzla** [comment]
To run it type:

`java -classpath reach-gordo-1.3.3-SNAPSHOT.jar org.clulab.reach.ReachCLI`

**Comment by hickst** [comment]
Thanks @marcovzla  -- that's great. I mentioned the task config because I was under the impression that it required some configuration to work, as in this project where Gus used it:

https://github.com/myedibleenso/processors-server/blob/master/build.sbt#L56-L68

**Comment by marcovzla** [comment]
The default merge strategy of the current version of sbt-assembly works.
You can see it here: https://github.com/sbt/sbt-assembly#merge-strategy

look for "Here is the default:"

**Comment by hickst** [comment]
It starts working, but it appears to be including the test classes and running all the tests before it builds the Uber JAR. Since we will *never* create an Uber JAR without having thoroughly tested the code :), I added a line to the build file to prevent testing within the assembly task. I made this pull request #409.

**Comment by bgyori** [comment]
Thanks! The reason we make fat (gordo, uber) jars is that INDRA uses REACH via a python-java bridge that needs to see REACH and all its dependencies on the classpath. So this is the most convenient way to get all that in one place. We have been disabling tests (`test in assembly := {}`) for assembly.

**Comment by bgyori** [comment]
One more thing here I just remembered: with `sbt assembly` I get a bunch of deduplication errors like
```
[error] deduplicate: different file contents found in the following:
[error] org/clulab/coref/Coref$$anonfun$15$$anonfun$16.class
[error] org/clulab/coref/Coref$$anonfun$15$$anonfun$16.class
```

The solution I found to get around this was to add this snippet to the end of `build.sbt`. You might consider adding this unless this is something that shouldn't be done...
```
assemblyMergeStrategy in assembly := {
 case PathList("META-INF", xs @ _*) => MergeStrategy.discard
 case x => MergeStrategy.first
}
```

**Comment by bgyori** [comment]
I have some further questions, we need the Api and ApiRuler classes in the assembled jar. This seems to have gone away with the current settings. How can I get these classes to appear in the jar?

**Comment by myedibleenso** [comment]
>One more thing here I just remembered: with sbt assembly I get a bunch of reduplication errors

Hmm...I don't see any errors when running `sbt assembly` on `master`.

**Comment by myedibleenso** [comment]
>I have some further questions, we need the Api and ApiRuler classes in the assembled jar.

The api stuff is now under `org.clulab.reach.export.apis`) (`org.clulab.reach.export.apis.Api` and `org.clulab.reach.export.apis.ApiRuler`).  Are you perhaps using a different path?

**Comment by myedibleenso** [comment]
@bgyori: https://github.com/sorgerlab/indra/blob/9f53525efbf9428a9b8eed1eb8c5b43a74aefee1/indra/reach/reach_reader.py#L30

**Comment by bgyori** [comment]
Thanks! I updated the path and it works. I couldn't find where ApiRuler went but it makes sense now.
