### ISSUE TITLE
TestReachCLI / ReachCLI refactoring

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#41]
Currently each test in `TestReachCLI` instantiates a new `ReachCLI`, which loads its own instance of `BioNLPProcessor`.  We end up loading a lot of models unnecessarily.  Could this be refactored?  We might consider something like https://github.com/clulab/reach/blob/60e8e26de7eeb43477a32033023c6d3482491ff4/src/main/scala/edu/arizona/sista/reach/ReachSystem.scala#L16-L19

This way we could pass the same `BioNLPProcessor` instance to each `ReachCLI` configuration we need to test.

**Comment by MihaiSurdeanu** [comment]
Makes sense. Go for it :)
