### ISSUE TITLE
Subproject config files should minimize configuration

### ISSUE THREAD

**Issue by hickst** [clulab/reach#417]
Example: the Assembly reference.conf file assumes that it is being run by a user with a HOME directory. This is not true for web applications. Since Reach cannot currently be compiled without Assembly this causes a runtime error in the web app (or forces the reconfiguration of multiple config files, prone to error when one forgets to change them all).

Perhaps all subprojects should inherit a common configuration and extend that common core. The root location of various temp paths would be specified in the common configuration and subprojects could build on the root path (just as SBT does). Using a root path would provide an easy way to quickly configure a system for a web app or other special need.

**Comment by hickst** [comment]
BTW the application.conf file uses `${HOME}/Documents/reach` as the default for path prefixes whereas Assembly reference.conf seems to use `${HOME}/Downloads` (note Downloads, not Documents). Is this intentional or a typo?

**Comment by myedibleenso** [comment]
> Since Reach cannot currently be compiled without Assembly this causes a runtime error in the web app

So your errors are due to the use of `${HOME}`?  That's a shame, as none of those paths/variables are used by your web app or `ReachCLI`.

As it is a `reference.conf`, any of its settings will be overwritten by an `application.conf`, which you can pass to the jar you're running.  That means you should change anything in the `reference.conf`.

I believe you should be using a custom `application.conf` for your web app, as that defines the configuration specific to your system.  I will think about how best to change those paths for `reach-exe`...

>Assembly reference.conf seems to use ${HOME}/Downloads (note Downloads, not Documents). Is this intentional or a typo?

Yes this is intentional.

**Comment by hickst** [comment]
I **am** using a custom application.conf for the the web app, which replaces any HOME vars. I wanted to avoid customizing more than one conf file, which it sounds like you are saying is possible IF I add settings to application.conf to override the ones in reference.conf. Of course, this means I have to know which ones need overriding and update the application.conf file if any are added to reference.conf.

Is reference.conf a standard "thing" in the Typesafe library? Are we using other reference conf files anywhere?

**Comment by marcovzla** [comment]
Yes, `reference.conf` is standard.

This is the order in which variables are resolved in decreasing order of priority:
  - system properties
  - `application.conf` (all resources on classpath with this name)
  - `application.json` (all resources on classpath with this name)
  - `application.properties` (all resources on classpath with this
    name)
  - `reference.conf` (all resources on classpath with this name)

So we can set defaults in `reference.conf` and they can be overriden in an `application.conf` or with properties passed as command line args.

**Comment by hickst** [comment]
OK, thanks for the reference! I'll update my web application.conf file, then.

**Comment by myedibleenso** [comment]
Yes, I understand why you were annoyed.  If you just look at the `application.conf`, it isn't obvious where the property is being set.  I wasn't thinking about `$HOME` being an undefined environment variable on some systems.  I was trying to avoid cluttering the `application.conf` with things that aren't relevant to the top-level stuff, but maybe now I don't have a choice...

More details on the resolution order are here:
https://github.com/typesafehub/config#standard-behavior

**Comment by hickst** [comment]
I wasn't annoyed I was just trying to reduce my already error-prone process of updating a configuration file specifically for a web compile.
Web containers like Tomcat usually run as special users who are not root and who do not have any login ability (and no home directories).
