### ISSUE TITLE
clean up of the events master grammar

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#424]
I'd like to clean up the events master grammar. What I'd like to do is set the triggers of regs/activations to some global variables. For example, instead of what we have now:
- import: org/clulab/reach/biogrammar/events/pos-reg_template.yml
  vars:
    triggers: "acceler|activat|aid|allow|augment...

I'd like to have:
- import: org/clulab/reach/biogrammar/events/pos-reg_template.yml
  vars:
    triggers: ${someGlobalVar}

Is this possible?

**Comment by MihaiSurdeanu** [comment]
Currently, variables can replace each other, but you can't use a variable when defining another variable.

We can add a limited version of this in which variables declared in a previous scope can be used in the current one.
This handles your example in which you want to use a global variable to initialize a local one.

I believe this could be accomplished by replacing this (see link below) Map concatenation with something fancier that inspects the values
of variables and replaces mentions of variables declared in a parent scope.

Currently what this Map concatenation does is replace a variable in a parent scope with a variable with the same
name declared in a descendant scope, without inspecting it.

The relevant code is here:
https://github.com/clulab/processors/blob/0b24ceac75e739f90bde29c93e9b980809660680/main/src/main/scala/org/clulab/odin/impl/RuleReader.scala#L208-L212

**Comment by MihaiSurdeanu** [comment]
@marcovzla: can you please implement this, when you feel like coding some basic stuff? Not urgent.

**Comment by myedibleenso** [comment]
This seems like a `processors` issue, no?

**Comment by MihaiSurdeanu** [comment]
It's both:
- First, Odin needs to be adjusted, as Marco notes above. This is now processors issue #107.
- Mihai adjusts the events grammar when the above issue is solved.

**Comment by MihaiSurdeanu** [comment]
Solved by PR 447
