### ISSUE TITLE
Find and process 22 PMC files for Cheryl

### ISSUE THREAD

**Issue by hickst** [clulab/reach#429]
PMC2248754
PMC2568943
PMC2740868
PMC2788426
PMC2887830
PMC3027602
PMC3088706
PMC3176292
PMC3395716
PMC3427313
PMC3464875
PMC3749168
PMC3822699
PMC3906956
PMC4074809
PMC4190548
PMC420458
PMC4223012
PMC4270087
PMC4509450
PMC4725756
PMC4942780

**Comment by MihaiSurdeanu** [comment]
She needs the tabular"Arizona" format.

**Comment by hickst** [comment]
Which you provided, so I'm closing this.
