### ISSUE TITLE
Missing enzyme for sentence about phosphorylation of multiple sites

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#432]
Here's something I came across today:

When processing the following sentence: "Activated Akt phosphorylates FoxO3a protein at Ser-318 and Ser-321 and Ser 253, which mediates FoxO3a nuclear exportation and transcription inhibition (XREF_BIBR)."

I get three phosphorylations (in INDRA statement form):

```
[Phosphorylation(None, FOXO3(), S, 321),
 Phosphorylation(AKT1(), FOXO3(), S, 253),
 Phosphorylation(None, FOXO3(), S, 318)]
```

The phosphorylation event for S253 correctly identifies the enzyme as the string "Akt", whereas the enzyme is missing for the other two sites (S321 and S318).

**Comment by MihaiSurdeanu** [comment]
@danebell: improve matching of sites?
