### ISSUE TITLE
Lemmatize context's NER

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#44]
Make the context NER match lemmas instead of words.

**Comment by myedibleenso** [comment]
@MihaiSurdeanu  and @enoriega: Given the recent changes to the NER system(s), is this still necessary?

**Comment by enoriega** [comment]
Yes.

**Comment by MihaiSurdeanu** [comment]
Why is this necessary? Remember that if we want to do this, we have to lemmatize all the KBs. This is risky, because the POS tags for these short strings will not be great. And lemmatization depends on that.

**Comment by enoriega** [comment]
To match singular and plurals with a single entry; for example the entry "**human**" could match "_human_" and "_humans_". We spoke about this once and agreed to make the change. Should we stick to have singular and plural variants of each entry?

**Comment by MihaiSurdeanu** [comment]
Let's discuss Wed the best solution.

**Comment by enoriega** [comment]
We decided not to do this. Instead pluralize the cellular location files
