### ISSUE TITLE
Add profiling to Reach

### ISSUE THREAD

**Issue by hickst** [clulab/reach#446]
Issue #426 depends on gathering this information. First, gather times by functional step.

**Comment by marcovzla** [comment]
We used flight recorder for profiling in #426.
I think it is not necessary to add this since flight recorder is sufficient.
Should we close this?

**Comment by myedibleenso** [comment]
I think so.  The profiling that was proposed would've been too coarse-grained to pinpoint the problem in #426.

**Comment by marcovzla** [comment]
closing in favor of using flight recorder
