### ISSUE TITLE
No configuration setting found for key 'csv'

### ISSUE THREAD

**Issue by davidserv** [clulab/reach#448]
Hi all,

Does anybody get that error message with the last version of REACH while running it:
 
_[error] (run-main-0) com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'csv'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'csv'__

It seems that it can't find the configuration file for ReachCSV... while I have it though: csv.conf is in reach/main/src/main/resources/. Whatever I place the configuration file in or out of the directory I get the same error message.

Would anybody help me with this ?

David S.

**Comment by myedibleenso** [comment]
David, could you provide us with a bit more information?  What version of Reach are you using?  

The `ReachCSV` runnable has been removed from Reach, though we are still able to read column-based files: https://github.com/clulab/reach/wiki/Supported-Input-Formats#tsv-files


Thanks for pointing out `csv.conf` file, though.  It seems that we forgot to remove that file.

**Comment by davidserv** [comment]
I use the REACH currently available on the master branch.

Thanks for telling me that the ReachCSV has been removed. Now I use the papersDir variable in the application.conf file to point to my new tsv file and this time, when I run REACH with the command line 'sbt "runMain org.clulab.reach.ReachCLI main/src/main/resources/application.conf" ', I get the message:

_00:06:07.834 [run-main-0] INFO  org.clulab.reach.ReachCLI - Initializing Reach ...
[error] (run-main-0) java.nio.charset.MalformedInputException: Input length = 1
java.nio.charset.MalformedInputException: Input length = 1_

Do I miss something ?

Best,
David S.

**Comment by myedibleenso** [comment]
@davidserv, I'm noticing two things about what you've reported...

1) If you're altering the provided `application.conf`, you don't need to specify the path.  `sbt "runMain org.clulab.reach.ReachCLI"` should be sufficient.
2) It sound like you may have an encoding error.  The default config assumes your files are UTF-8: https://github.com/clulab/reach/blob/master/main/src/main/resources/application.conf#L31

If your input files have been saved with a different encoding, you'll want to change this property in the config.

**Comment by davidserv** [comment]
Indeed specifying the path to the config file is useless, I should start acquiring good habits...

After a check, I can tell that my input file is in utf-8 already so the problem is somewhere else. I'm asking myself if it could be a simple java version problem.

Best,
David S.

**Comment by hickst** [comment]
Hi David,

Is the file proprietary or huge? Otherwise, perhaps you can just upload it and we can try to run it and see what happens for us.

**Comment by davidserv** [comment]
I don't use my own input file anymore, instead I use the nxml files located in reach/main/src/test/resources/inputs/nxml. I get that same error message whatever it is my input file or the nxml files.

Best,
David S.

**Comment by hickst** [comment]
1) I'm confused: from the previous messages, it looks like you were (are?) having problems with a specific input file in CSV form. Is this true of not?
2) Reach does require Java 8.

**Comment by davidserv** [comment]
At first this was the case, but then I realised that the same problem occurs with any kind of input file actually, even with the example files that comes with REACH ! Sorry, I didn't make that point clear.

Also, I forgot to mention that all this happens on a server running ubuntu 16.04. On my own laptop ubuntu 16.04 everything's fine but not on the server I'm working on.

Best,
David S.

**Comment by davidserv** [comment]
Java 8 is installed and up and running but the issue is still there...

Best,
David S.

**Comment by davidserv** [comment]
Hi,

I thought it would be easier for you to help me if you could see for yourself what is going on so I managed to reproduce the issue on a google server.

In attachment are the ssh keys (public and private) to be placed in your .ssh folder. Then to access the server type "ssh david@104.196.232.188" and it should work.

On the server, if you do a "ls" inside the home folder you will recognize the reach and the stanford-corenlp folders. You can check that the CLASSPATH environment variable is fully set. In the to_test_reach folder, is the tsv file which I try to run reach on. You are all set to run reach.

I would be so thankful if you could have a quick look at what's there and see where am I wrong.

Best,
David S.
________________________________

**Comment by davidserv** [comment]
Here is the link to my ssh keys: http://www.4shared.com/folder/EP8CQJdy/_online.html

Best,
David S.

**Comment by davidserv** [comment]
Lately I had the surprise to discover that reach works not on VPS ubuntu servers (and I tested several of them) but works well on the VPS CentOS servers. Indeed, the java error I had never appears on VPS CentOS servers. On laptops, reach seems to run like a charm on every plartforms, except on VPS servers. How can this be ?

Best,
David S.

**Comment by hickst** [comment]
Sorry, I don't know and I haven't had time to test this. However, I note that most virtual machine images do not include Java and those that do include Java, do not include Oracle Java due to licensing restrictions. Are you testing with an "official" Oracle version of Java 8? We're using (at least) 1.8.0_60 and 1.8.0_74.

**Comment by davidserv** [comment]
I confirm that I installed the Oracle java 1.8.0_112 both on the Ubuntu and CentOS virtual server. I obtained that java directly from the Oracle website. On the Ubuntu one, I get the java error, not on the CentOS one.

**Comment by hickst** [comment]
OK and which versions of Ubuntu and CentOS are you using? Which VM platform are you running those in (VirtualBox, EXSi, Parallels, etc).

**Comment by davidserv** [comment]
I used the Ubuntu 16.04.1 64bit and CentOS 7.2.1511. Currently the VM platform is qemu, however I tried other servers previously and they might run other VM platforms.

**Comment by MihaiSurdeanu** [comment]
We can't replicate this issue, so closing this for now.
