### ISSUE TITLE
Invalid UniProt ID assigned

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#449]
For some reason, whenever `HRE` appears in text it is grounded to UniProt with id `HRE`. This is strange becase HRE is the  raw string name of the entity and is not a valid UniProt ID. 

Here is an example sentence:
`In the present study, we first demonstrated that HIF-1alpha binds to an HRE in FGF-2 gene in ASCs to enhance mRNA and protein expression of FGF-2, thereby promoting proliferation.`
for which, under entities, I get:
```
      {
        "text":"HRE",
        "frame-id":"ment-api2674-UAZ-r1-Reach-0-150071",
        "type":"protein",
        "frame-type":"entity-mention",
        "end-pos":{
          "reference":"pass-api2674-UAZ-r1-Reach",
          "offset":75,
          "object-type":"relative-pos"
        },
        "xrefs":[
          {
            "namespace":"uniprot",
            "species":"human",
            "object-type":"db-reference",
            "id":"HRE"
          }
        ],
        "object-type":"frame",
        "start-pos":{
          "reference":"pass-api2674-UAZ-r1-Reach",
          "offset":72,
          "object-type":"relative-pos"
        },
        "sentence":"sent-api2674-UAZ-r1-Reach-0"
      },
```

**Comment by hickst** [comment]
Thanks for the report Ben, I'll check that out immediately.

**Comment by hickst** [comment]
It looks like HRE is a bad entry in the override file. I don't find HRE in any of our KBs nor in Uniprot online. Can you tell me what this entity is (family, protein, cell line, other?) and to what should it be grounded?

**Comment by johnbachman** [comment]
Also FYI HRE is not a protein (had to look this one up): https://en.wikipedia.org/wiki/Hormone_response_element

**Comment by johnbachman** [comment]
So to answer your question (our posts crossed) I don't think you could ground it to anything, at least not for the time being.

**Comment by hickst** [comment]
Thanks John. This will be corrected in the next release of the Bioresources project (hopefully coming by the end of the week).

**Comment by hickst** [comment]
I looked for other invalid entries with the same pattern in our override file and found 'ARE'. Again, not in our KBs and not sure what it refers to. Any ideas?

**Comment by bgyori** [comment]
I don't remember seeing ARE, do you know any papers it appears in?

**Comment by hickst** [comment]
I do not have any specific papers and, since it's a bad entry and I don't know where it came from, I'm just going to remove it. If it **is** used in papers, it will surface again.

**Comment by bgyori** [comment]
It might actually be Antioxidant Response Element, which is not currently groundable.
