### ISSUE TITLE
Best practices for extraction text from PDFs for reading with REACH?

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#451]
Hi, this is a question, not an issue. I've been looking at expanding the proportion of full text content that we can access, and the next biggest publisher to cover after Elsevier is Wiley. Wiley has TDM access to full text papers via the CrossRef clickthrough API, but they only return PDFs (not XML or plain text). So I'm playing around with Python packages for extracting text from PDFs (not involving any OCR, however). The main tool that people use appears to be PDFMiner (http://euske.github.io/pdfminer/index.html); I am using PDFMiner via a convenient wrapper called slate (https://github.com/timClicks/slate).

I am wondering if you guys have much experience running REACH on the (sometimes poor quality) text extracted from PDFs, and if so, if you have any advice. For example, the whitespace in the resulting text is often all over the place, frequently putting multiple line breaks between single words. The sections can also be mashed up.

I've attached a PDF file I tried today, along with the text extracted from the file by slate/PDFMiner:

[test_pdf_file.pdf](https://github.com/clulab/reach/files/595593/test_pdf_file.pdf)

[test_pdf_file.txt](https://github.com/clulab/reach/files/595606/test_pdf_file.txt)

When I try to process the whole paper with REACH, it sits for a long time--I haven't been patient enough yet to let it finish. When I process just the first page, I get some nice results, below (note that "MAGEE1" is the misgrounding of "damage", per issue #450 😉):

```
[Ubiquitination(MAGEE1(), MDM2()),
 Ubiquitination(None, TP53()),
 Activation(MDM2(), activity, TP53(), activity, False),
 Activation(CDKN2A(), activity, MAGEE1(), activity, True)]
```

I suspect that it's the references section at the end of the file that is causing REACH to take a long time to process, though I haven't verified this. If so, I could look into whether we can reliably strip the references section out from the extracted text.

**Comment by johnbachman** [comment]
Addendum--I stripped the references off the end of the paper and then ran REACH, it gave pretty good-looking results, so I guess it wasn't too screwed up by the formatting and mishmash of headers, etc.

Results:

```
[Acetylation(None, TP53()),
 Activation(BCNU(), activity, MDM2(), activity, False),
 Activation(CDIPT(), activity, TP53(), activity, True),
 Activation(CDKN1A(), activity, Nutlin_(), activity, True),
 Activation(CDKN1A(), activity, SERPINA1(), activity, True),
 Activation(CDKN2A(), activity, MAGEE1(), activity, True),
 Activation(CDKN2A(), activity, TP53(), activity, False),
 Activation(LMB(), activity, TP53(), activity, True),
 Activation(MAGEE1(), activity, MDM2(), activity, False),
 Activation(MDM2(), activity, FBLN5(), activity, True),
 Activation(MDM2(), activity, MAGEE1(), activity, True),
 Activation(MDM2(), activity, NCS_(), activity, True),
 Activation(MDM2(), activity, Nutlin_(), activity, True),
 Activation(MDM2(), activity, TP53(), activity, False),
 Activation(MDM2(), activity, TP53(), activity, True),
 Activation(MDM2(), activity, proliferation(), activity, True),
 Activation(MDM2_binding(), activity, TP53(), activity, True),
 Activation(NCS(), activity, MDM2(), activity, True),
 Activation(NCS(), activity, SERPINA1(), activity, True),
 Activation(NCS(), activity, TP53(), activity, True),
 Activation(NES(), activity, MDM2(), activity, False),
 Activation(SERPINA1(), activity, MDM2(), activity, True),
 Activation(Stress(), activity, MDM2(), activity, True),
 Activation(Stress(), activity, SERPINA1(), activity, True),
 Activation(TP53(), activity, FBLN5(), activity, True),
 Activation(TP53(), activity, MDM2(), activity, False),
 Activation(TP53(), activity, MDM2(), activity, True),
 Activation(TP53(), activity, NCS(), activity, True),
 Activation(Wortmannin(), activity, MAGEE1(), activity, False),
 Activation(Wortmannin(), activity, TP53(), activity, False),
 Activation(proteasome(), activity, MDM2(), activity, False),
 Activation(proteasome(), activity, TP53(), activity, False),
 Activation(wortman__nin(), activity, MDM2(), activity, True),
 Complex(MDM2(), TP53()),
 Complex(p53_NES(), MDM2()),
 Phosphorylation(ATM(), MDM2()),
 Phosphorylation(None, ATM()),
 Phosphorylation(None, HDM2_ATM()),
 Phosphorylation(None, MDM2()),
 Phosphorylation(None, TP53()),
 Phosphorylation(None, TP53(), S, 15),
 Ubiquitination(E3_ubiquitin_ligase(), TP53()),
 Ubiquitination(MAGEE1(), MDM2()),
 Ubiquitination(None, MDM2()),
 Ubiquitination(None, Mateu()),
 Ubiquitination(None, TP53()),
 Ubiquitination(None, proteasome())]
```

**Comment by hickst** [comment]
We tried something like this approach for PDF extraction but the results were just horribly inconsistent -- too many variations in the PDF formats and resulting extractions. Also, the text had intermixed figures, columns, labels, tables, authors, references, etc. Also many of the PDF documents we were interested in were older and were just images embedded in the PDF. We gave up.

We were going to try and extract paragraphs into our CSV input format; a simple input format but one that would give the document some structure (in theory).

**Comment by MihaiSurdeanu** [comment]
@johnbachman: we are not that affected by weird white spaces, as long sentences are maintained as sentences...

In any case, you should talk to @GullyAPCBurns. Gully developed a tool that converts PDFs into the NXML format, and I think he addressed several of these issues. No need to reinvent the wheel.

**Comment by johnbachman** [comment]
Nice! I assume this is lapdftext? https://github.com/GullyAPCBurns/lapdftext

**Comment by GullyAPCBurns** [comment]
That's it. Let me know if you have any difficulty, there might be some
wrinkles in terms of setting this up for the first time.

Gul

**Comment by GullyAPCBurns** [comment]
Actually, you should use this version.

https://github.com/BMKEG/lapdftext

G
