### ISSUE TITLE
Correct polarization of some regulations

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#454]
We need to improve the lexicon for polarity flipping. 
See examples where we get the polarity incorrectly in the attached spreadsheet (rows in red).

[Summary of annotated.xlsx](https://github.com/clulab/reach/files/609990/Summary.of.annotated.xlsx)

**Comment by hickst** [comment]
The Harvard guys have identified several contexts for inhibition. I should be able to handle the ones involving dashed prefixes and suffixes in grounding (issue #354) but here are the "standalone ones" (i.e. separated from the target by whitespace):

dominant negative {Gene name}   inhibition      dominant negative
dominant-negative {Gene name}   inhibition      dominant negative
silencing {Gene name}   inhibition
Targeting {Gene name}   inhibition      genetic or chemical inhibition
{Gene name} knockdown   inhibition      siRNA-based knockdown
{Gene name} knockout    inhibition
{Gene name} siRNA       inhibition      siRNA-based knockdown
{Gene name} siRNAs      inhibition      siRNA-based knockdown
{Gene name} shRNA       inhibition      siRNA-based knockdown

**Comment by danebell** [comment]
That's very helpful! Thank you!
