### ISSUE TITLE
REACH versions that change results?

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#474]
Hi, I was wondering if it's possible to get information on REACH updates that affect the extraction results rather than internal performance improvements, use-case specific additions, etc. We cache REACH reading results for papers on Amazon S3 along with the REACH version, and re-read papers when we have a sense that there have been a lot of updates to REACH since those papers were last read. Generally we're pretty conservative and force a re-read if we're not using the exact same commit of REACH as before, but if we had a better sense we could save time (and money) by not re-reading papers when updates haven't affected output.

Feel free to ignore this request if it is an undue burden :) I could also probably try to track the content of the pull requests more closely as they go in.

**Comment by MihaiSurdeanu** [comment]
@johnbachman: this is a good comment.
@hickst: we should add a simple statement to future Reach version ("this impacts extraction results") to clarify changes.

**Comment by hickst** [comment]
OK, I'll try to do that. Many of my changes have had to do with data handling, such as KB modifications and overrides, entity processing, and grounding IDs. Such changes always have the **potential** to modify the resulting identifications, whether they do or not. This is a recurring problem for our data-driven software test suites, some small test of which will often fail when I add a new entity to a KB.

**Comment by MihaiSurdeanu** [comment]
@hickst: also, please ask around the group before each release. There may be changes you are not aware of.

**Comment by hickst** [comment]
That's a good idea but perhaps I misunderstood John's request. I thought we were talking about attaching the impact information to each **issue** or **pull request** so that they know when to recompile and rerun their papers?
@johnbachman you guys are recompiling more frequently than official releases, right?

**Comment by bgyori** [comment]
Yes, we typically work off of the latest master.

**Comment by MihaiSurdeanu** [comment]
Ok. We can attach this to each PR. Tom, can you please remind me to discuss
this Wed?

**Comment by hickst** [comment]
@MihaiSurdeanu OK, I'm assigning this issue to you (as a reminder) and I've added it to the URGENT column of the project task control page.

**Comment by MihaiSurdeanu** [comment]
@hickst, @danebell, @myedibleenso, @marcovzla, @enoriega, @bgyori, @johnbachman: we will mark new PRs with the phrase "(RESULTS CHANGE)" when the PR affects the Reach output.

**Comment by johnbachman** [comment]
Great, thanks!
