### ISSUE TITLE
Multiple output formats

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#475]
Let's be able to output more than one output format at once. This is to be able to have multiple formats when doing big runs, like one over the whole open access subset

**Comment by hickst** [comment]
@myedibleenso Why was the `skipFiles` Set moved down to the instance level? It was a "class constant" and thus shared by all threads. Now each thread (of potentially several dozen) has to reread the file, creating another Set instance containing (potentially) hundreds of thousands of filename strings.

**Comment by hickst** [comment]
OK, we believe this is not the case: closing this issue again.
