### ISSUE TITLE
Slow processing of certain texts

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#480]
There was mention in #463 of three papers with a slow runtime:

```
Finished PMID27345422 successfully (675 seconds)
Finished PMID27521218 successfully (779 seconds)
Finished PMID27630114 successfully (603 seconds)
```

We should try to profile these and understand what might be slowing things down.

**Comment by myedibleenso** [comment]
@johnbachman, I was only able to find the full text nxml for PMC5050443 (PMID 27630114).  I just have abstracts for the other two.  Is that what you ran?

**Comment by johnbachman** [comment]
I used the nxml for PMID27630114, but got Elsevier full-text XML (from which we extracted plain text) for the other two. We've noticed with some papers that sometimes the extracted text gets words stuck together with no spaces--I'm actually looking into that as a separate issue on our side.

I'll email the text files to you privately so as not to run afoul of Elsevier's license agreement.

**Comment by myedibleenso** [comment]
>We've noticed with some papers that sometimes the extracted text gets words stuck together with no spaces--I'm actually looking into that as a separate issue on our side.

I've seen this, too.

>I'll email the text files to you privately so as not to run afoul of Elsevier's license agreement.

Ah, that's why I couldn't find them through our normal channels.  Thanks!

**Comment by myedibleenso** [comment]
After profiling, it seems the bottleneck here are some long sentences gumming up the chart parser.  If we exclude the initial KB loading, ~70% of the processing time is spent parsing.

**Comment by MihaiSurdeanu** [comment]
I will close this. But I will start a new issue on using the faster parser.
