### ISSUE TITLE
Akka microserver for knowledge base queries

### ISSUE THREAD

**Issue by hickst** [clulab/reach#496]
> We need a grounding microservice that minimally supports the following use cases:
> 
> 1. Endpoint receives a string, service returns all possible grounding IDs.
> 2. Endpoint receives a grounding ID, service returns all possible synonyms.
>
> Ideally, it would also have functionality to handle another use case:
> 
> 3. Endpoint receives a grounding ID, service returns the "short name".

**Comment by hickst** [comment]
1 and 2 can be implemented now.
For 3, many KBs don't make this distinction. The Uniprot protein database does, but our Uniprot KB collects and mixes all entries from the recommended name, short names, alternative names, alternative short names, gene names, and gene name synonyms (and so does not distinguish among the sources). To implement 3, I would have to re-create our Uniprot KB, so I'm going to postpone function 3 for now.
I will, however, design the service to allow it as a future enhancement.

**Comment by MihaiSurdeanu** [comment]
Thanks Tom!
How soon can you have something running?

**Comment by hickst** [comment]
### An example from Uniprot: Q02750 (MP2K1_HUMAN):
**Protein names**
_Recommended name:_
-    Dual specificity mitogen-activated protein kinase kinase 1 (EC:2.7.12.2)

**Short name:**
-    MAP kinase kinase 1
-    MAPKK 1
-    MKK1

**Alternative name(s):**
- ERK activator kinase 1
- MAPK/ERK kinase 1

_Alternative Short name:_
- MEK 1

**Gene names**
- Name: MAP2K1
- Synonyms: MEK1, PRKMK1

**Comment by hickst** [comment]
I think the previous example is fairly typical: there can be more than one "short name" and some alternatives may be more common than the official "short names" (e.g., it seems like I've seen 'MEK 1' a lot more than 'MKK1')

**Comment by hickst** [comment]
This task closed by delivery of a new repository: [kbquery](https://github.com/clulab/kbquery).

A MySQL dump of the `kbqdb` database has been uploaded to Kate at this location:

/net/kate/storage/data/nlp/code/KBQuery/kbqdb-twelf_17-04-09_23.57_wKeys.sql

This dump file can be used to very quickly (3-5 minutes) load/reload all our KBs into an existing installation of MySQL. Follow the instructions in the project README file to do so.
