### ISSUE TITLE
Positive_activation_syntax_1_verb misclassifies a catalysis as a positive activation

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#516]
The sentence

```GAPDH catalyzes the conversion of glyceraldehyde-3-phosphate to 1,3-bisphosphoglycerate```

Leads to an extraction of a positive activation event by ```Positive_activation_syntax_1_verb```, with GAPDH as the controller and glyceraldehyde-3-phosphate as the controlled. However GAPDH is actually here catalyzing the reaction that *consumes* glyceraldehyde-3-phosphate and *produces* 1,3-bisphosphoglycerate.

**Comment by myedibleenso** [comment]
closed by #517
