### ISSUE TITLE
Activation should be a regulation

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#52]
**Bug type**: `Rules`

**Description**: positive_activation should be a positive_reg of the phospho. 

```scala

import edu.arizona.sista.reach.nxml.FriesEntry
import edu.arizona.sista.reach.ReachSystem

// Initialize the REACH system
val rs = new ReachSystem

def mentionsFromText(text:String):Seq[Mention]= {
  val entry = FriesEntry("test", "1", "example", "example", isTitle = false, text)
  rs.extractFrom(entry)
}

val sentenceText = "it inhibits the activity of Wnt/beta-catenin pathway by phosphorylation of beta-catanin which results in its proteasomal degradation, while in other cases it promotes the pathway by phosphorylating LRP5
"

val mentionText = "GSK-3 interacts with the Wnt/beta-catenin pathway at multiple levels; in some circumstances it inhibits the activity of Wnt/beta-catenin pathway by phosphorylation of beta-catanin which results in its proteasomal degradation, while in other cases it promotes the pathway by phosphorylating LRP5/6 which results in the stabilization of beta-catenin."

val mentions = mentionsFromText(sentenceText)
```

**Comment by hickst** [comment]
Using branch issue #113, I'm not seeing a postive activation in either of these sentences entered at the ReachShell:

"GSK-3 inhibits the activity of Wnt/beta-catenin pathway by phosphorylation of beta-catanin which results in its proteasomal degradation, while in other cases it promotes the pathway by phosphorylating LRP5."

"GSK-3 interacts with the Wnt/beta-catenin pathway at multiple levels; in some circumstances it inhibits the activity of Wnt/beta-catenin pathway by phosphorylation of beta-catanin which results in its proteasomal degradation, while in other cases it promotes the pathway by phosphorylating LRP5/6 which results in the stabilization of beta-catenin."

**Comment by hickst** [comment]
However, I might have thought that the "phosphorylation of beta-catanin by GSK-3 => inhibits Wnt" would produce a negative_regulation?

**Comment by hickst** [comment]
Assigning this issue to Gus so that he can check whether it still exists.

**Comment by myedibleenso** [comment]
I can't reproduce the initial issue.  Maybe this requires some previous text for "it" to resolve and trigger the inhibition?

Closing for now...
