### ISSUE TITLE
REACH doesn't respect thread limits

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#528]
running ReachCLI doesn't respect the value assigned to the `threadLimit` setting in `application.conf`

**Comment by hickst** [comment]
What makes you say that? Can you provide some more information to illustrate that?

**Comment by enoriega** [comment]
I ran a big job on multiple servers and despite specifying a particular value to the setting, it uses more threads in all of them

**Comment by hickst** [comment]
Yes, I've glimpsed that pattern myself. Did you happen to see how many of the threads were active (vs blocked) at one time? I read somewhere that the ForkJoinPool is capable of spawning new threads to compensate for blocked threads (thus exceeding our limit?) *but* I don't believe that we've configured it to do this.

**Comment by hickst** [comment]
I'm stymied: Our code uses a class called `scala.concurrent.forkjoin.ForkJoinPool` but I cannot find any documentation or source code for this class (or its package!) in Scala 2.11. The entire package is listed in Scala 2.12 docs as `deprecated`. So, I don't know where this class is being found when we compile.

**Comment by MihaiSurdeanu** [comment]
This has been fixed.
