### ISSUE TITLE
Update Reach JSON serialization

### ISSUE THREAD

**Issue by hickst** [clulab/reach#529]
Some initial work in branch `jsonupdate`

JSON serialization in Reach is broken by the restructuring of base code in Processors. I need Reach to compile and pass tests with the latest (6.0.6-SNAPSHOT) version of Processors. I started to update Reach but got stuck by missing (obsoleted?) JSON methods.

**Comment by myedibleenso** [comment]
Ah, didn't notice the branch you mentioned...oops.  Anyway, I've fixed this on [`proc6.0.6`](https://github.com/clulab/reach/tree/proc6.0.6) in commit 2c55e56eeefd7d6854cfad91ffd49568ccca07c2

**Comment by hickst** [comment]
Thanks @myedibleenso ! I merged these fixes into my current working branch so I am going to close this issue (but not yet remove this branch).
