### ISSUE TITLE
Best way to use REACH as a web-service

### ISSUE THREAD

**Issue by JohnGiorgi** [clulab/reach#531]
Is there a 'best' way to use REACH as a standalone web-service? 

Right now, we have just dockerized a fork of REACH that essentially calls the WebUI (see [here](https://github.com/jvwong/reach_docker)), but is there a better approach?

(Note we are aware of the API but would like to set up a local instance of REACH as a web-service!)

Thanks very much in advance.

**Comment by MihaiSurdeanu** [comment]
@hickst?

**Comment by hickst** [comment]
I'll need a little clarification about what you guys are trying to do....

Q1) What must your `web-service` do? It seems to me that you want the functionality of the Reach API (http://agathon.sista.arizona.edu:8080/odinweb/api/help) but you want to run this on your locally compiled version of Reach?

Q2) The `FileProcessorWebUI` interface you are using is one that Gus created for his own research purposes. As far as I understand, it only supports 3 output formats: 2 specialized CSV formats and a *massive* JSON dump of the Reach internal data structures (which I recommend against unless you have very specialized needs). Have you identified one of these formats as what you need?

Some suggestions:

1) You don't need to clone Reach if all you want to do is change the runtime parameters. (In fact, it is very bad software practice to replace a general parameter mechanism with "hardwired" parameters. Always try to change code only as a last resort).
Scala runtime parameters are often specified in Typesafe configuration files ending with `.conf`. Reach has 8 of these files, controlling many aspects of its operation. The server parameters are located in `./assembly/src/main/resources/reference.conf`. Simply change the `akka.http.server.port` value to your local port. As noted in the configuration file, the default `host` is already `0.0.0.0`.
2) I'm not sure why you are using Docker in this case (unless Docker is your central or only mechanism for running everything). To run a single Reach server instance, you could just assemble a single _FAT_ or _Uber_ JAR:
`sbt assembly`  should compile Reach to create a single JAR file in `target/scala-2.11/reach-gordo-1.3.2.jar`. You can then run the JAR file from the command line or from within a shell script.

Please reply with some more information about your goals and use-cases and we can figure out the best path for you.

**Comment by JohnGiorgi** [comment]
> It seems to me that you want the functionality of the Reach API (http://agathon.sista.arizona.edu:8080/odinweb/api/help) but you want to run this on your locally compiled version of Reach?

That is exactly what we would like to do. I am working on a project for the Bader Lab and we want to ensure our demo will work when it needs to (this is why the team feels a little more comfortable running it locally). 

> The FileProcessorWebUI interface you are using is one that Gus created for his own research purposes. As far as I understand, it only supports 3 output formats: 2 specialized CSV formats and a massive JSON dump of the Reach internal data structures (which I recommend against unless you have very specialized needs). Have you identified one of these formats as what you need?

I did not know the `FileProcessorWebUI` interface was for internal testing, but that is good to know! At this point it is not incredibly important which output format we use, so long as we can easily extract entity/relationship mentions. So the Arizona format would be fine for example. 

> I'm not sure why you are using Docker in this case (unless Docker is your central or only mechanism for running everything). To run a single Reach server instance, you could just assemble a single FAT or Uber JAR:
sbt assembly should compile Reach to create a single JAR file in target/scala-2.11/reach-gordo-1.3.2.jar. You can then run the JAR file from the command line or from within a shell script.

This sounds closet to what we would like, the ability to take reach as-is and deploy it as a web-service. Our use case is fairly straightforward: 
1) we want to be able to provide a local instance of reach (deployed as a web service) with some text, and then receive the output 
2) the output will be used to model pathways in a front-end web UI we have already developed. 

What we need help with is the first step, and it sounds like the single FAT or Uber JAR method will probably best suit our use case. 

Thank you very much for the detailed answer and thanks in advance for any further advice you have!

**Comment by hickst** [comment]
It sounds like the Uber JAR may solve your issue. Please correct me if that is not the case. Also, please let me know if you need any additional assistance. You probably already know about this but, don't forget the [additional information available on the Reach Wiki:](https://github.com/clulab/reach/wiki)
