### ISSUE TITLE
In reference to #535 and #531

### ISSUE THREAD

**Issue by JohnGiorgi** [clulab/reach#536]
@hickst 
I was able to successfully create the FAT JAR (as per your instructions in #535). I just need some direction with running the JAR and accessing the service. 

Currently, I am running the jar from the command line by calling:

`java -cp reach-gordo-1.3.5-SNAPSHOT.jar org.clulab.reach.RunReachCLI`

Which seems to do the trick, here is the output:

```
09:21:13.536 [main] INFO  org.clulab.reach.RunReachCLI$ - ReachCLI (w/o assembly) begins ...
09:21:13.551 [main] INFO  org.clulab.reach.ReachCLI - Initializing Reach ...
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.6 sec].
Adding annotator lemma
09:21:52.740 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Beginning to load the KBs for the rule-based bio NER...
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label BioProcess. This matcher contains 12 unique strings; the size of the first layer is 11.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label CellLine. This matcher contains 23 unique strings; the size of the first layer is 18.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label CellType. This matcher contains 8 unique strings; the size of the first layer is 6.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Cellular_component. This matcher contains 14 unique strings; the size of the first layer is 9.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Family. This matcher contains 128 unique strings; the size of the first layer is 95.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Gene_or_gene_product. This matcher contains 204 unique strings; the size of the first layer is 169.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Organ. This matcher contains 13 unique strings; the size of the first layer is 5.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Simple_chemical. This matcher contains 82 unique strings; the size of the first layer is 68.
09:21:52.769 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label Site. This matcher contains 47 unique strings; the size of the first layer is 46.
09:21:52.770 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded OVERRIDE matcher for label TissueType. This matcher contains 1 unique strings; the size of the first layer is 1.
09:22:02.114 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Gene_or_gene_product. This matcher contains 74472 unique strings; the size of the first layer is 62085.
09:22:15.078 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Family. This matcher contains 34588 unique strings; the size of the first layer is 27638.
09:22:15.091 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Cellular_component. This matcher contains 1388 unique strings; the size of the first layer is 873.
09:23:22.519 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Simple_chemical. This matcher contains 132037 unique strings; the size of the first layer is 78599.
09:23:22.873 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Site. This matcher contains 7312 unique strings; the size of the first layer is 3238.
09:23:22.875 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label BioProcess. This matcher contains 247 unique strings; the size of the first layer is 147.
09:23:22.888 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Species. This matcher contains 1944 unique strings; the size of the first layer is 1175.
09:23:24.123 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label CellLine. This matcher contains 72333 unique strings; the size of the first layer is 67250.
09:23:24.130 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label TissueType. This matcher contains 1312 unique strings; the size of the first layer is 1093.
09:23:24.161 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label CellType. This matcher contains 2631 unique strings; the size of the first layer is 1829.
09:23:24.598 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - Loaded matcher for label Organ. This matcher contains 8704 unique strings; the size of the first layer is 5671.
09:23:24.598 [procCoreServer-akka.actor.default-dispatcher-2] INFO  o.c.processors.bionlp.ner.KBLoader - KB loading completed.
macro=true
featureFactory=org.clulab.processors.bionlp.ner.BioNERFactory
Loading classifier from org/clulab/processors/bionlp/ner/bioner.dat ... done [1.2 sec].
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.7 sec].
macro=true
featureCountThresh=10
featureFactory=org.clulab.processors.corenlp.chunker.ChunkingFeatureFactory
```
__I then have two questions__:

1) Is this the correct way to run the JAR? (and if not, _how do I run it?_) 
2) How do I access this running instance as a web-service? (i.e. how _exactly_ do I send the service text and retrieve an output in a specified format?).

Thanks very much in advance!

**Comment by hickst** [comment]
Hi John,

1. It is **one** correct way to run Reach: you are running the 'main' program to run a "batch" job; which processes multiple papers in NXML format from a specific directory (specified in the `application.conf` file). The resulting output files are written to a specific output directory (also specified in the `application.conf` file).

2. But, the JAR file contains multiple 'main' programs: Instead of calling the batch job 'main', I think you now just want to run Gus' internal web server 'main' at: `org.clulab.reach.export.server.FileProcessorWebUI`

3. Note that (2) is very similar to how you were going to call it from SBT in your `sbt.sh` script (https://github.com/jvwong/reach_docker/blob/master/sbt.sh#L6), except now you are calling the 'main' method directly in the JAR using the Java runtime.

**Comment by JohnGiorgi** [comment]
Hi Tom, 

Thanks for the quick response. I tried running `org.clulab.reach.export.server.FileProcessorWebUI` but got this error:
```
Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.5.2 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.                 
Uncaught error from thread [reach-export-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[reach-export]
java.lang.NoSuchMethodError: akka.actor.ActorCell.addFunctionRef(Lscala/Function2;)Lakka/actor/FunctionRef;
	at akka.stream.stage.GraphStageLogic$StageActor.<init>(GraphStage.scala:139)
	at akka.stream.stage.GraphStageLogic.getStageActor(GraphStage.scala:903)
	at akka.stream.impl.io.ConnectionSourceStage$$anon$1.preStart(TcpStages.scala:55)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:381)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:576)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:521)[INFO] [08/08/2017 11:15:31.687] [main] [FileProcessorWebUI$(akka://reach-export)] Server online at http://localhost:8888

	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:519)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [SECURITY][08/08/2017 11:15:31.693] [reach-export-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(reach-export)] Uncaught error from thread [reach-export-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
[INFO] [08/08/2017 11:15:31.696] [Thread-0] [CoordinatedShutdown(akka://reach-export)] Starting coordinated shutdown from JVM shutdown hook
```

I do not know anything about Akka. Is there an obvious mistake I am making? __I see this__: `Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath` but as far as I know, there is no instance of Akka in my classpath. 

Again, thanks for your help & patience. Cheers!

**Comment by hickst** [comment]
Oh drats....we just recently added some more code that uses Akka and that must have caused this problem. I apologize; I know it's probably annoying but we appreciate your help in eliminating these FAT JAR related issues.

I'm pretty sure I understand the issue and it will require us to update some portion of the code. I will file a separate issue for this and will probably take us a day or two to fix.

**Comment by JohnGiorgi** [comment]
@hickst 
No worries at all, I will hang tight until that fix is pushed. 

Thanks again for all the help!

**Comment by hickst** [comment]
Hi John,

I've updated Reach to allow you to produce a FAT JAR which directly runs the embedded file processing server. Basically, you will repeat the steps you did before to locally compile the latest version of Processors and then compile a Reach FAT JAR (using an additional flag) from our latest development branch. 

To compile (and use) your own local, SNAPSHOT version of Processors (you've probably already done this):
1. `git clone git@github.com:clulab/processors.git`
2. `cd processors`
3. `sbt compile publishLocal`

You now need to use that local version of Processors 6.0.8-SNAPSHOT in your local copy of Reach. To build a FAT JAR with the latest development branch of Reach:
1. cd to your local working copy of Reach
2. check out the development branch: `git checkout proc6.0.8`
3. compile a FAT JAR configured to run the file processor server:
`sbt -DmainClass=org.clulab.reach.export.server.FileProcessorWebUI assembly`
4. find the FAT JAR: `cd target/scala-2.11`
5. run it on default port (8888): `java -jar reach-1.3.5-SNAPSHOT-FAT.jar`
6. (optional alternate): run it on a different port: `java -jar reach-1.3.5-SNAPSHOT-FAT.jar --port 8080`

For more details on the FAT JAR see the Wiki page: https://github.com/clulab/reach/wiki/Using-Reach-from-a-FAT-JAR
For general informaton on running Reach see the Wiki page: https://github.com/clulab/reach/wiki/Running-REACH

**Comment by JohnGiorgi** [comment]
Hi Tom, 

Thanks so much, I followed your above steps and I was able to get the sever up and running without any trouble. I really do appreciate all the help!

Once the server is up and running, am I able to interact with Reach using a RESTful interface? (as opposed to uploading documents via the webUI).

**Comment by hickst** [comment]
Hmmm.....looking at the code for this little server, it appears very form-oriented (remember, it was built for our own quick and dirty research purposes). I will write to you offline so we can discuss what your needs are and whether there are some alternatives.

**Comment by hickst** [comment]
OK, I've added an internal server to Reach that you can use to process files locally from the command line or shell script (using cURL), or through your local network. To use it, you need to download and compile the latest Reach (master branch) into a standalone FAT JAR and run the FAT JAR, as follows:

1. cd to your local working copy of Reach
2. check out the master branch: `git checkout master; git pull`
3. compile a FAT JAR configured to run the file processor server:
`sbt -DmainClass=org.clulab.reach.export.server.ApiServer assembly`
5. find (or move) the FAT JAR: `cd target/scala-2.11`
6. run the FAT JAR (default port 8080): `java -jar reach-1.3.5-SNAPSHOT-FAT.jar`
7. for instructions on how to use the server, point your browser to `http://localhost:8080/`

**Please note that the first request to the server may take several minutes to complete**; as Reach loads a bunch of large NLP models into memory. After the initial request, responses should be much quicker.

As I believe this update allows you to do what you need locally, I am closing this GitHub issue. If you encounter any problems please feel free to file a new Reach issue. Thanks.
