### ISSUE TITLE
`testReach` in `TestUtils` should use a context engine

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#54]
This should be a quick fix and it may help to reduce our memory footprint.  @enoriega, can you take care of this one?

The relevant line:
https://github.com/clulab/reach/blob/72f3f8eece7125028f239830aa1c105837a13d4d/src/test/scala/edu/arizona/sista/reach/TestUtils.scala#L15

**Comment by enoriega** [comment]
Ready. All tests still pass after the change
