### ISSUE TITLE
Reducing size of KBs

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#55]
We discussed pruning the uniprot stuff somehow.  Have we heard back from our MCB collaborators about @MihaiSurdeanu 's proposal to prune entries over K tokens?

Aside from the uniprot issue, we probably want to remove citations that exist in the species(?) KB.  Though doing so might not greatly reduce its size, this is just excess baggage that will never match.  It's probably making the trie unnecessarily deep.

**Comment by hickst** [comment]
Enhanced generator program to filter out Uniprot protein key phrases with > 5 whitespace-separated tokens. This reduced KB by 134,020 entries, or about %4.6 of the total entries in the previous version of the KB.
