### ISSUE TITLE
POST requests with arguments in POST body

### ISSUE THREAD

**Issue by hickst** [clulab/reach#551]
Six hours ago John Giorgi wrote:

> I am having an issue with POST requests to the local running instance of Reach.
> 
> GET requests work fine, and return the expected output. However with a POST request that looks something like the following:
> 
> Headers
> Content-Type: application/x-www-form-urlencoded
> output: indexcard
> Body
> text: p53 binds to mdm2
> 
> I get an error : Request is missing required query parameter ‘text'.
> 
> Is there anyway to provide the text argument in the Body of a POST request instead of as an argument in the URL? There is a limit on the size of a URL obviously, which will be a problem for us as we plan on passing full abstracts to the server.
>

**Comment by hickst** [comment]
Have you seen the POST examples on the server's own API documentation? There are several examples there of POSTing from a text file using cURL.

Are you saying that you are POSTing, but not from a file? If so, where is your data coming from and what software are you using to do the POST?

**Comment by hickst** [comment]
Capability was added and issue closed by pull request #552

**Comment by JohnGiorgi** [comment]
It works, thanks a lot!!
