### ISSUE TITLE
ReachCLI not picking up .txt files

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#554]
We used to rely on the ReachCLI picking up both .nxml and .txt files for reading. This was changed a while ago in this commit: https://github.com/clulab/reach/commit/7efbccb79fb91cbb6779994d2cf1c03ccd13a9af, which effectively results in skipping .txt files. If I were to make a PR that adds `txt` to the regexp, would you merge it? Or is there some reason why that would be a problem?

**Comment by MihaiSurdeanu** [comment]
@bgyori: that sounds like a bug. I began a discussion in the commit above about this.

**Comment by myedibleenso** [comment]
Oops!  Sorry to have inadvertently broken your workflow, @bgyori.  That pattern should be modified to gather all files matching formats that we support.

I think leaving out `txt` at the time was just an oversight.

**Comment by hickst** [comment]
When I saw this issue I thought "Hey, I fixed that about a month ago (and in a couple of places)". I was right: I did fix it but, unfortunately, I forgot to pull the code into `master` from the development branch.

**Comment by myedibleenso** [comment]
@hickst, why was this reopened?  The fix was already merged...

**Comment by hickst** [comment]
OK, should be fixed by pull request #558.
