### ISSUE TITLE
Get output in BRAT Standoff format?

### ISSUE THREAD

**Issue by JohnGiorgi** [clulab/reach#567]
@hickst 

I noticed the following lines in `application.conf`

```
# this is where the brat standoff and text files are dumped
# if this directory does not exist it will be created
bratDir = ${rootDir}/brat
```

However after running a batch job with reach, I do not see this folder or the output from reach in the BRAT-standoff format. I also can't find any documentation on this in the wiki.

How would I go about getting the output from a batch job with reach in the brat-standoff format? This would be awesome for my workflow. Thanks in advance.

**Comment by MihaiSurdeanu** [comment]
Hi John,

Unfortunately, we no longer support the Brat format. We just don't have the resources to do it. But we would welcome help if you want to volunteer :). Any of the formats in:https://github.com/clulab/reach/tree/master/export/src/main/scala/org/clulab/reach/export
could serve as a starting point...

**Comment by myedibleenso** [comment]
@JohnGiorgi, most of the work has already been done.

Brat standoff can be produced from Mentions using the following method call:  
 

- https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/reach/brat/Brat.scala#L116

```scala
import org.clulab.odin.Mention
import org.clulab.processors.Document
import org.clulab.reach.brat.Brat

val mentions: Seq[Mention] = ???
val doc: Document = ??? // all of the mentions should be from this doc
Brat.dumpStandoff(mentions, doc)
```

The one problem with this is that the code can produce invalid Brat [standoff](http://brat.nlplab.org/standoff.html) (see #383).  

When dumping to Brat standoff, we map every `RelationMention` to a Brat relation annotation:  
 
  

- https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/reach/brat/Brat.scala#L172

Our `RelationMention`s can be nested, but Brat doesn't (or at least didn't asaik) support nested relation annotations.  

I believe I started on a potential solution some time ago, but wasn't satisfied: https://github.com/clulab/reach/commit/c322852b9320c0846565a5f27c350bba1c9860ad
