### ISSUE TITLE
Index Card participants type consistency

### ISSUE THREAD

**Issue by plmrry** [clulab/reach#58]
Currently, if there is only one `participant` in an index card, that `participant` is a JavaScript Object (i.e. the value of the `participant_a` or `participant_b` field). However, if there is more than one participant, the `participant` field is an Array. Thus, one must perform type checking on the `participant_` fields.

Would it break anything if the `participant_` fields were always arrays? 

When there is only one participant, these fields would be a single-element Array.

**Comment by MihaiSurdeanu** [comment]
Unfortunately, this standard is imposed by MITRE. Nothing we can do.
