### ISSUE TITLE
build.sbt dependencies broken

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#584]
If I try to add REACH as a dependency on another `sbt` project by following the README instructions:
```
libraryDependencies ++= Seq(
  "org.clulab" %% "reach" % "1.4.0"
)
```

SBT fails to resolve the following dependency:

>[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.clulab#reach_2.12;1.4.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.clulab:reach_2.12:1.4.0 (/Users/enrique/github/PaperReader-REACH/build.sbt#L7-10)
[warn] 		  +- default:paperreader-reach_2.12:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.clulab#reach_2.12;1.4.0: not found

REACH trying to resolve itself?

**Comment by marcovzla** [comment]
We currently don't cross-compile reach to scala 2.12.
We only release for scala 2.11.
But we could, now that we cross-compile processors.

**Comment by marcovzla** [comment]
try reach-main
http://search.maven.org/#search%7Cga%7C1%7Creach

**Comment by enoriega** [comment]
Yep, that was it. Thanks!
