### ISSUE TITLE
support for scala 2.11 and 2.12

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#585]
what the title says

**Comment by MihaiSurdeanu** [comment]
@kwalcock: this is not urgent, but when you have a moment, it would be great to update Reach to cross-compile for scala 2.11 and 2.12.
There was an issue with that, but I can't recall what it was. @marcovzla: do you remember?
Thanks!!

**Comment by marcovzla** [comment]
Sorry, I don't recall what the issue was.

**Comment by kwalcock** [comment]
The first problem that surfaces is this,
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: ai.lum#nxmlreader_2.12;0.0.9: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```
and maven, according to https://mvnrepository.com/artifact/ai.lum/nxmlreader, thinks that's a legitimate complaint.

**Comment by MihaiSurdeanu** [comment]
@marcovzla or @myedibleenso: can you please cross compile and release nxmlreader?

**Comment by myedibleenso** [comment]
@kwalcock @MihaiSurdeanu:  Can one of you please publish a cross-compiled version to Maven?

- https://repo1.maven.org/maven2/org/clulab/

**Comment by MihaiSurdeanu** [comment]
We will, but there is a bug in the current version that needs to be fixed first.
Can you publishLocal for now?

**Comment by myedibleenso** [comment]
I could, but the bug you mentioned has me thinking it might be better to just wait.  I can get by with using processors v7.5.3 for the time being.

**Comment by MihaiSurdeanu** [comment]
I think you should use the latest. There are many useful improvements.
You can disable the piece of code that has the bug by setting polarity.engine = Linguistic in the conf file.

**Comment by myedibleenso** [comment]
As a bandaid, how about merging that conf change and publishing? : )

**Comment by MihaiSurdeanu** [comment]
Good point. I can do that.

@bgyori: do you have anything against releasing Reach, w/ that DyNet component disabled by default?

**Comment by myedibleenso** [comment]
Any complaints, @bgyori ?

**Comment by MihaiSurdeanu** [comment]
@myedibleenso, @bgyori: there is a Reach PR that fixes the bug I mentioned. I hope to release the full Reach today.

**Comment by bgyori** [comment]
I'm fine with any release approach (with/without dynet). I could run a test off of @zhengzhongliang's PR to see if the dynet crash is gone now and report back if that's useful.

**Comment by MihaiSurdeanu** [comment]
This would be great. I'll move the conversation in that PR.
