### ISSUE TITLE
Running Reach several times produces different results

### ISSUE THREAD

**Issue by hickst** [clulab/reach#59]
Some documents producing more or fewer results over consecutive runs. (ex: PMC3441633).

**Comment by hickst** [comment]
Ran ReachCLI on PMC3441633.nxml twice. Second run produced additional event mention, missing from first run:
```> ================================================================================
> CorefEventMention: S3/723/768: Positive_activation
> text: Ras activation and engagement of specific Ras
> labels: List(Positive_activation, ActivationEvent, ComplexEvent, Event, PossibleController)
> foundBy: Positive_activation_syntax_3_noun
> trigger:
>   TextBoundMention: S3/727/737: Positive_activation
>   text: activation
>   labels: List(Positive_activation, ActivationEvent, ComplexEvent, Event, PossibleController)
>   foundBy: Positive_activation_syntax_3_noun
> controlled (1):
>   CorefTextBoundMention: S3/765/768: Family
>   text: Ras
>   labels: List(Family, BioChemicalEntity, Entity, PossibleController)
>   foundBy: ner-family-entities
>   xref: Xref(interpro,IPR020849)
> controller (1):
>   CorefTextBoundMention: S3/723/726: Family
>   text: Ras
>   labels: List(Family, BioChemicalEntity, Entity, PossibleController)
>   foundBy: ner-family-entities
>   xref: Xref(interpro,IPR001806)
> context:
>   Cellular_component: List(go:GO:0005623)```

Copied 4th sentence (S3 above) and pasted it into ReachShell 3 times: first and second time the event was produced. The third time NO event was produced. Sentence is:

```Our findings suggest a novel model for compartmentalized signaling in which PI3KC2&#x3B2; results in the redistribution of nucleotide-free Ras to intracellular vesicles leading to localized Ras activation and engagement of specific Ras effectors resulting compartmentalized activation of these targets.```

**Comment by myedibleenso** [comment]
@hickst is it only the event that's missing?  Are the entities being found all three times?

**Comment by hickst** [comment]
For ReachCLI runs, the answers are (diff file attached):
[run1-2_diff.txt](https://github.com/clulab/reach/files/118145/run1-2_diff.txt)

1) for the two different 2 runs, yes (run 1 results were the same as run 3 results)
2) yes - no entity changes
3) yes - no entity label changes

For the test at the ReachShell, the answers are:
1) yes, (but it's a single sentence)
2) yes - no entity changes
3) yes - no entity label changes.

**Comment by myedibleenso** [comment]
@marcovzla says this is a grounding issue.  The `xref` ids assigned to the participating entities are inconsistent between runs.  

When the args of this disappearing event have the same id, the mention is pruned; on runs where the ids differ, the mention remains.

**Comment by hickst** [comment]
OK, thanks for figuring that out guys. This problem should go away as soon as we return sequences of candidate groundings instead of picking the head of the list. Of course, I'm not sure how the pruning rule will or should work at that point.
