### ISSUE TITLE
entity which is a RelationMention cannot be cast to BioTextboundMention

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/reach#599]
Sentence:
`Akt1 (Akt334, AktTR, or Akt4H) is phosphorylated.`

Breaks here:
https://github.com/clulab/reach/blob/master/webapp/app/controllers/HomeController.scala#L81

**Comment by maxaalexeeva** [comment]
@marcovzla these are the other failing tests we discussed:

1) Potentially wrong test:

`  val sent5 = "Figure 3. Raf and PI3K bind to ubiquitinated Ras."
  val sent5b = "Figure 3. Raf and PI3K bind more to ubiquitinated Ras than to non-ubiquitinated Ras."
  it should "extract correct bindings with theme and theme2" in {
    var mentions = getBioMentions(sent5)
    var bs = mentions.filter(_ matches "Binding")
    bs should have size (2)
    for (b <- bs) {
      b.arguments.get("theme").get should have size (2) // each binding must have exactly two themes
      b.arguments.get("theme").get.exists(_.text == "Ras") should be (true) // Ras is a theme in all these
      b.asInstanceOf[BioEventMention].isDirect should be (true)
    }

    mentions = getBioMentions(sent5b)
    bs = mentions.filter(_ matches "Binding")
    bs should have size (2)
    for (b <- bs) {
      b.arguments.get("theme").get should have size (2) // each binding must have exactly two themes
      b.arguments.get("theme").get.exists(_.text == "Ras") should be (true) // Ras is a theme in all these
      b.asInstanceOf[BioEventMention].isDirect should be (true)
    }
  }`

Current error message:
`- should extract correct bindings with theme and theme2 *** FAILED *** (208 milliseconds)
[info]   List(org.clulab.reach.mentions.CorefEventMention@7a9947c0, org.clulab.reach.mentions.CorefEventMention@38b449b8, org.clulab.reach.mentions.CorefEventMention@61f51d14, org.clulab.reach.mentions.CorefEventMention@c2c3aeba) had size 4 instead of expected size 2 (TestBindingEvents.scala:90)`

**Comment by maxaalexeeva** [comment]
@marcovzla 

2) potentially wrong test:
https://github.com/clulab/reach/blob/afff6776cf2449c6de1c16c79776a499e1f06dc6/main/src/test/scala/org/clulab/reach/TestCoreference.scala#L233

Error message:
`- should not produce an activation with an activation controlled *** FAILED *** (847 milliseconds)
[info]   List(org.clulab.reach.mentions.CorefEventMention@be0001c, org.clulab.reach.mentions.CorefEventMention@be0001c) had size 2 instead of expected size 3 (TestCoreference.scala:239)
`

**Comment by marcovzla** [comment]
The webapp no longer breaks after 33cddf3bf77fd2a864f2892f6879717b06b7ae30.
The issue is with coref entities. I am currenlty filtering them out, but perhaps a better approach would be to actually display them. I don't currently have the cycles to do it, so I fixed it this way instead.
@maxaalexeeva @MihaiSurdeanu fyi

**Comment by marcovzla** [comment]
addc0eaba6cd23a4161a22c87fbff490370a0775 fixes the `TestCoreference` issue

**Comment by marcovzla** [comment]
I can't reproduce the `TestBindingEvents` error. It passes locally using the `ud` branch.
IDK if addc0eaba6cd23a4161a22c87fbff490370a0775 fixed it too or I should be looking in another branch.

**Comment by marcovzla** [comment]
this test [1] is failing because the output of the NER changed.
This is not a REACH issue, but a processors issue.

@MihaiSurdeanu fyi

[1] https://github.com/clulab/reach/blob/fa27f763b2a40666f836011baa9c061f00b00da1/main/src/test/scala/org/clulab/reach/TestCoreference.scala#L462

**Comment by maxaalexeeva** [comment]
Resolved with processors version 7.4.3
