### ISSUE TITLE
Get document metadata and pass it through to Reach

### ISSUE THREAD

**Issue by hickst** [clulab/reach#60]
We've had several requests from collaborators and users about extracting the publication date of each document and including it in the results. Enrique suggests a general implementation: "We could probably add a dictionary with all the present key, value pairs."

**Comment by hickst** [comment]
Collaborators would still really like this enhancement.

**Comment by enoriega** [comment]
I haven't forgotten about this feature. Will get to it soon. I need to address some NxmlReader issues besides this.

**Comment by hickst** [comment]
I've implemented the smallest thing that answers the issue: I extract the publication year and month from each paper and insert each into a new type of paper section: the 'meta-data' section. The outputters (FRIES and IndexCard) then extract the information from the meta-data sections and add that information to the 'meta-info' output JSON. The new meta-data section is to insure that the solution is generalizable to other future meta-data extraction uses.

**Comment by hickst** [comment]
Issue resolved by pull request #148.
