### ISSUE TITLE
"-KD" suffix (i.e., knockdown) should be added to list of negative polarity terms

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#607]
I only have a single example of this for now, but came across the following:

> Phosphorylation of AKT, a downstream effector of the IGF-1R pathway, at S473 was also increased by BRCA1-KD.

This is getting extracted as "BRCA1 leads to the phosphorylation of AKT on S473", but the implication is in fact the opposite (BRCA1 inhibits AKT phosphorylation).

This suffix is included in the list of inhibition affixes in FamPlex: https://github.com/sorgerlab/famplex/blob/master/gene_prefixes.csv#L133

**Comment by MihaiSurdeanu** [comment]
@enoriega: please extend the polarity component as follows: if the cause ends with "-KD" (or other polarity changing suffixes), flip the polarity.

@zhengzhongliang: what does your NN model produce on this sentence? (just for our own curiosity)

**Comment by enoriega** [comment]
Done

**Comment by zhengzhongliang** [comment]
I run the sentence in the NN model. It predicts "positive activation"

REACH's output for this sentence is:

MENTION TEXT:  Phosphorylation of AKT, a downstream effector of the IGF-1R pathway, at S473 was also increased by BRCA1-KD
LABELS:        List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => Positive_regulation_syntax_2_verb
	TYPE => CorefEventMention
	------------------------------

	------------------------------
	TRIGGER => increased
	controlled (List(Phosphorylation, AdditionEvent, SimpleEvent, Event, PossibleController)) => Phosphorylation of AKT, a downstream effector of the IGF-1R pathway, at S473
	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => BRCA1-KD
CONTEXT: NONE
	------------------------------

I convert the sentence to a python dictionary and feed it to the trained LSTM:

sentence = {"sentence text":"Phosphorylation of AKT, a downstream effector of the IGF-1R pathway, at S473 was also increased by BRCA1-KD.", 
"event interval start":0, 
"event interval end":18,
"trigger":"increased", 
"polarity":"Positive_regulation", 
"rule":"Positive_regulation_syntax_2_verb"}

The final output of LSTM is "1", which means positive activation.
