### ISSUE TITLE
Recognizing negative evidence

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#608]
REACH should distinguish between things that did/do happen ("A phosphorylates B") and things that did/do not happen ("A does not phosphorylate B.") This is more feature request than issue, but I know that Eidos can do this so I thought it would be great to bring this capability into REACH! 

I've noticed a few sporadic examples in the statements I've been curating but I collected a more extensive set by taking a random sample of statements from our database, searching for sentences that contain "does not" or "did not" and then manually curating a handful. I've attached the results in INDRA Statement JSON format. Some examples:

REACH: "AFG1 activates EMT"

> The combined treatment of TNF-alpha and IL-6 could induce morphological changes in A549 cells, characterized by fibroblast like cells, while AFG 1 did not cause EMT in the tumor cells.

REACH: "EGF activates differentiation"

> Although epidermal growth factor- (EGF) and NGF treated PC12 cells share several common properties, including activation of the mitogen activated protein (MAP) kinase pathway and induction of immediate early genes, EGF is mitogenic for PC12 cells and does not normally stimulate differentiation.

The curation showed that simply looking for "did not"/"does not" is not sufficient to unambiguously identify negative relations, since it (unsurprisingly) depends on what is being negated in the context of the sentence.

For example, this sentence:

> Although many forms of apoptosis involve the caspase system, DAC induced cell death did not display activation of one of the most important effector caspases, caspase 3, nor were the cells protected from DAC induced cytotoxicity when pre-treated with a pan-caspase inhibitor.

...yields the relation "DAC activates cell death", which is correct; the "did not" applies to the description that follows. Other examples of correct extractions/non-negations:

REACH: "AFP activates apoptosis":

> Incubation of AFP sensitive tumor cells (HepG2, Raji) with neutralizing anti-Fas, anti-tumor necrosis factor receptor (TNFR) 1 or anti-TNFR2 mAb did not prevent AFP induced apoptosis, demonstrating its independence of Fas dependent and TNFR dependent signaling.

REACH: "P-cadherin activates signal transduction"

> Intracellular signal transduction triggered by P-cadherin involves activation of Rac1 and Cdc42 Rho GTPases [XREF_BIBR], but it has been found that Rac1 and Cdc42 activation alone does not fully account for the ability of P-cadherin to suppress anoikis [XREF_BIBR].

In addition to these fairly straightforward examples of non-negation, there are also trickier cases where a positive and negative statement are included in the same sentence, e.g. "low dose A does not activate B, but high dose A does" or "A alone does not activate B but A and C together activate B." This again may require a modified extraction approach and new knowledge representation for experimental parameters. Examples:

REACH: "BAG activates cell death":

>Treatment of cells with 10mug/ml BAG alone did not affect the cell viability, whereas 1 or 10mug/ml BAG with LT significantly augmented the frequency of cell death.

REACH: "BMP2 activates osteocalcin":

>Dex or BMP-2 treatment alone did not affect the basic osteocalcin levels, but in combination with vitamin D, BMP-2 increased the osteocalcin production, while Dex treatment completely suppressed osteocalcin production.

And here's a case where I've read the sentence several times and I'm still a little fuzzy on what the results mean:

> Addition of purified BMP-2 protein did not increase the upregulation of alkaline phosphatase activity and osteocalcin secretion by piceatannol, whereas the BMP-2 antagonist noggin blocked piceatannol and BMP-2-mediated alkaline phosphatase activity, and osteocalcin secretion enhancement, indicating that BMP-2 production is required in piceatannol mediated osteoblast maturation and differentiation."

Let me know if you need more examples!

[neg_stmts.json.txt](https://github.com/clulab/reach/files/2576144/neg_stmts.json.txt)

**Comment by johnbachman** [comment]
Also note that there are certainly other triggers for negative results than "did not"/"does not", one common one that comes to mind is "failed to". Will keep an eye out for others.

**Comment by MihaiSurdeanu** [comment]
Thanks @johnbachman!

We will look at these examples soon. But note that Reach does extract negation. In fact, the code in Eidos is taken from the Reach code. It should appear as a modification. You don't see it even on simple statements?

**Comment by johnbachman** [comment]
Hi @MihaiSurdeanu, sorry, yes! After filing the issue @bgyori actually reminded me that REACH *does* in fact extract negative evidence. However, the REACH processor in INDRA currently ignores these (it was written before we had an approach to handling this kind of evidence in assembly, whereas now we do--we will update accordingly). However, these examples are cases where REACH is not flagging the relation as negative evidence, and they are passing through the processor. So take them as cases that the REACH negative evidence detector is missing.

**Comment by johnbachman** [comment]
Additional clarification: the INDRA REACH processor currently checks the JSON output for the `is_negated` flag, as shown here: https://github.com/sorgerlab/indra/blob/3c19b13def4232f70b1b529d9bf5eb4c5d35a0e9/indra/sources/reach/processor.py#L590

(Currently, negated events are then skipped).

However, note that I tried the following simple sentences (using the REACH web service) and in each case I got the expected relation but without any negation flag in the output JSON:

* "MAP2K1 does not phosphorylate MAPK1"
* "MAP2K1 does not activate MAPK1"
* "MAP2K1 failed to phosphorylate MAPK1"
* "MAP2K1 did not phosphorylate MAPK1"

**Comment by MihaiSurdeanu** [comment]
@enoriega: can you please see what is happening in the 4 simple statements mentioned by @johnbachman? This might be a major issue...

**Comment by MihaiSurdeanu** [comment]
@maxaalexeeva says that these examples work in the shell. So it may be that the JSON output is broken?

**Comment by johnbachman** [comment]
Here is a real world example that I just came across with "fail to". REACH extracts this as "RAS phosphorylates BCL2":

>"MEKK1 and Ras, upstream activators of JNK and ERK MAPK, also fail to induce Bcl-2 hyperphosphorylation."

**Comment by MihaiSurdeanu** [comment]
@MihaiSurdeanu will take a look at this.

**Comment by enoriega** [comment]
I took a look to that final example, and REACH indeed detects `fail` as a negation, as well as `not` on the previous four examples. I attach the shell output at the end of this post. I suspect that either the json output code is not writing the negation modification or maybe the latest version of REACH fixed this issue.

Maybe @zhengzhongliang could take a look into the json output code? @MihaiSurdeanu 

```
EVENTS:   4

MENTION TEXT:  Bcl-2 hyperphosphorylation
LABELS:        List(Phosphorylation, AdditionEvent, SimpleEvent, Event, PossibleController)
DISPLAY LABEL: Phosphorylation
	------------------------------
	RULE => Phosphorylation_syntax_4_noun
	TYPE => BioEventMention
	------------------------------

	------------------------------
	TRIGGER => hyperphosphorylation
	theme (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => Bcl-2
CONTEXT: NONE
	------------------------------



MENTION TEXT:  MEKK1 and Ras, upstream activators of JNK and ERK MAPK, also fail to induce Bcl-2 hyperphosphorylation
LABELS:        List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => Positive_regulation_syntax_1_verb
	TYPE => BioEventMention
	------------------------------

	with 1 modification =>
		Negated by "fail"
	------------------------------
	TRIGGER => induce
	controlled (List(Phosphorylation, AdditionEvent, SimpleEvent, Event, PossibleController)) => Bcl-2 hyperphosphorylation
	controller (List(Gene_or_gene_product, MacroMolecule, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => MEKK1
CONTEXT: NONE
	------------------------------



MENTION TEXT:  Ras, upstream activators of JNK and ERK MAPK, also fail to induce Bcl-2 hyperphosphorylation
LABELS:        List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => Positive_regulation_syntax_1_verb
	TYPE => BioEventMention
	------------------------------

	with 1 modification =>
		Negated by "fail"
	------------------------------
	TRIGGER => induce
	controlled (List(Phosphorylation, AdditionEvent, SimpleEvent, Event, PossibleController)) => Bcl-2 hyperphosphorylation
	controller (List(Family, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => Ras
CONTEXT: NONE
	------------------------------



MENTION TEXT:  ERK MAPK, also fail to induce Bcl-2 hyperphosphorylation
LABELS:        List(Positive_regulation, Regulation, ComplexEvent, Event, PossibleController)
DISPLAY LABEL: Positive_regulation
	------------------------------
	RULE => Positive_regulation_syntax_1_verb
	TYPE => BioEventMention
	------------------------------

	with 1 modification =>
		Negated by "fail"
	------------------------------
	TRIGGER => induce
	controlled (List(Phosphorylation, AdditionEvent, SimpleEvent, Event, PossibleController)) => Bcl-2 hyperphosphorylation
	controller (List(Family, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)) => ERK MAPK
CONTEXT: NONE
	------------------------------
```

**Comment by MihaiSurdeanu** [comment]
Thanks @enoriega!

I just ran the 4 examples in @johnbachman's latest post, and I can confirm that they are properly negated in the shell. I will take a look at the output format. @johnbachman: which output format do you commonly use?

**Comment by MihaiSurdeanu** [comment]
Note that the "json" format includes these negation modification. Search for "Negation" in the attached file, for example. 
I am looking into our other formats.


[1.json.txt](https://github.com/clulab/reach/files/2630784/1.json.txt)

**Comment by MihaiSurdeanu** [comment]
Sorry, the above format is "serial-json"

**Comment by MihaiSurdeanu** [comment]
And I can confirm that the "arizona" and "fries" formats do NOT capture negation... I will look into this.

**Comment by zhengzhongliang** [comment]
Hi Enrique,
I can take a look at the Json file.

Best regards,
Zhengzhong



Mihai Surdeanu <notifications@github.com>于2018年11月29日 周四下午1:36写道：

**Comment by MihaiSurdeanu** [comment]
@zhengzhongliang: I will fix this.

**Comment by zhengzhongliang** [comment]
Thanks professor.

Mihai Surdeanu <notifications@github.com>于2018年11月29日 周四下午1:45写道：

**Comment by johnbachman** [comment]
@MihaiSurdeanu excellent! We use the FRIES format. For future reference here is a link to the REACH config file that we use in INDRA:

https://github.com/sorgerlab/indra/blob/4d687fc8eba9f479080d9d8dbfd0088b51a3b61a/indra/tools/reading/util/reach_conf_fmt.txt

**Comment by MihaiSurdeanu** [comment]
Thanks!

This was merged in master over the weekend, so closing this.
