### ISSUE TITLE
Misrecognition of clauses "process-inducing factor X"

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#609]
I've included 89 sentences (INDRA JSON) that all lead to the generally incorrect extraction that "EMT activates SNAI2", where EMT refers to epithelial-mesenchymal transition and SNAI2 is a gene that is also referred to as Slug. In all cases that I've looked at, the relation should actually be reversed, i.e., "SNAI2 activates EMT". Here's one example of how the failure occurs:

>The expression levels of EMT inducing TFs (TWIST1, SNAIL1, SLUG, ZEB1, and FOXC2) in the CD45 - cells were determined using qRT-PCR.

In many, though not all cases, the issue appears to be phrases like 

* "...EMT activating transcription factors, Twist and SNAI2 and Slug..."
* "...EMT inducing transcription factors - TWIST1, SNAIL1, SNAIL2 (SLUG),..."
* "...EMT inducing TFs, notably Slug, Twist, ZEB1 and ZEB2."
* "...the EMT and survival inducing functions of Slug"
* "...the EMT inducer Slug"
* "...EMT driving transcription factors Slug, Twist1 and ZEB1"

...etc. It appears that "EMT activating factor Slug" is getting interpreted as "EMT activates Slug".

[emt_induces_slug.json.txt](https://github.com/clulab/reach/files/2582041/emt_induces_slug.json.txt)

**Comment by MihaiSurdeanu** [comment]
This is tricky, because the critical "-" is not available to rules. So, this needs to be handled by the polarity component as follows:
- If the controller occurs to the left of trigger at 1 character distance, AND
- The character in between is "-", THEN
flip the polarity.

@enoriega: can you please look at this?

**Comment by MihaiSurdeanu** [comment]
Sorry, incorrect statement "flip the polarity". The action should be flip the participant roles, e.g., the controller becomes the controlled

**Comment by enoriega** [comment]
@MihaiSurdeanu: My plan is to plug in a function that follows the description you mentioned into this function: 

```scala
def extractEventsFrom(doc: Document, entities: Seq[BioMention]): Seq[BioMention] = {
    val mentions = eventEngine.extractByType[BioMention](doc, State(entities))
    // clean modified entities
    // remove ModificationTriggers
    // Make sure we don't have any "ModificationTrigger" Mentions
    val validMentions = mentions.filterNot(_ matches "ModificationTrigger")
    // handle multiple Negation modifications
    NegationHandler.handleNegations(validMentions)

    // Probably here, operating over validMentions

    validMentions
}
```

Which can be found here: https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/reach/ReachSystem.scala#L200-L209

I think the best place to write the implementation of that role-flipping function is in the `org.clulab.reach.darpa` package, along `MentionFilter`, `NegationHandler` and `HypothesisHandler`. 

I'll start as soon as I get the green light.

**Comment by MihaiSurdeanu** [comment]
I agree the best place for this is in the `org.clulab.reach.darpa` package.
And the example in extractEventsFrom makes sense. Of course, your code will be different (see my comment above).

**Comment by enoriega** [comment]
Finished
