### ISSUE TITLE
Inconsistencies in text / verbose-text / entity-text

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#612]
We use an extracted `event`'s `verbose-text` entry as evidence text since the simple `text` entry of an `event` sometimes omits important information. The issue is that `verbose-text` doesn't exactly match the original raw text in some cases. Example:

The actual raw sentence from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4729835/ is:
```
Nf1 is a GTPase-activating protein that negatively regulates
Ras activity downstream of Kit signalling.
```

The corresponding (edited) JSON extraction is:
```json
{"events":{ "frames":[
      {
        "text":"GTPase-activating protein that negatively regulates Ras",
        "arguments":[
          {
            "text":"GTPase-activating protein",
            "type":"controller",
          }],
        "sentence":"sent-api1661-UAZ-r1--106",
        "verbose-text":"Nf1 is a GTPase activating protein that negatively 
                        regulates Ras activity downstream of Kit signalling."
    }
]}
```

Notice how the (1) original sentence, (2) event text and (3) entity text all say "GTPase-activating", but the `verbose-text` says "GTPase activating" with no "-". Also note that the sentence ID (sent-api1661-UAZ-r1--106) points to an entry which has `text` equal to the `verbose-text` of the event. 

This inconsistency indicates that the two types of text entries have been processed in slightly different ways. This is currently causing issues downstream because the entity text cannot trivially be found in the evidence sentence in these cases. Would it be possible to change verbose-text (or introduce a new entry) that is in the same processing state as the other text entries i.e. matching the original raw text?

**Comment by MihaiSurdeanu** [comment]
Yes, with the latest major release (1.5.0) this is now possible. Previously, it was not. We will work on this soon.

**Comment by bgyori** [comment]
@MihaiSurdeanu I confirmed that with the latest master, in the `fries` output, `verbose-text` is the same as before. Would it be possible to either change `verbose-text` to be unprocessed text, or add a new entry under some other name that captures the original text? Thanks!

**Comment by MihaiSurdeanu** [comment]
Can you please provide a simple example I can debug? verbose-text now comes from Sentence.raw, so I'd like to understand better what is going on.

**Comment by MihaiSurdeanu** [comment]
Oh, nm. I see the example above. I'll use that.

**Comment by MihaiSurdeanu** [comment]
I believe this is now fixed. The current output (in a branch) for the text above is:

```
{
  "frames" : [ {
    "frame-id" : "evem-1-UAZ-r1-1-0-2",
    "text" : "GTPase-activating protein that negatively regulates Ras activity downstream of Kit",
    "arguments" : [ {
      "text" : "Kit",
      "argument-type" : "entity",
      "type" : "controlled",
      "object-type" : "argument",
      "index" : 0,
      "arg" : "ment-1-UAZ-r1-1-0-4"
    }, {
      "text" : "GTPase-activating protein",
      "argument-type" : "entity",
      "type" : "controller",
      "object-type" : "argument",
      "index" : 0,
      "arg" : "ment-1-UAZ-r1-1-0-2"
    } ],
    "type" : "activation",
    "frame-type" : "event-mention",
    "subtype" : "negative-activation",
    "is-direct" : false,
    "end-pos" : {
      "reference" : "pass-1-UAZ-r1-1",
      "offset" : 91,
      "object-type" : "relative-pos"
    },
    "trigger" : "negatively regulates",
    "object-type" : "frame",
    "start-pos" : {
      "reference" : "pass-1-UAZ-r1-1",
      "offset" : 9,
      "object-type" : "relative-pos"
    },
    "sentence" : "sent-1-UAZ-r1-1-0",
    "found-by" : "Negative_activation_syntax_1_verb",
    "verbose-text" : "Nf1 is a GTPase-activating protein that negatively regulates Ras activity downstream of Kit signalling."
  }, {
...
```

Is this what you expect @bgyori ?

**Comment by bgyori** [comment]
Yes, I also just tested some other examples on your branch and it works great! Once merged, we can close this issue.

**Comment by MihaiSurdeanu** [comment]
Ok. Running all tests. If no issues, I'll merge next.

**Comment by MihaiSurdeanu** [comment]
Merged in master.
