### ISSUE TITLE
Add BioProcess to taxonomy and modify rule templates accordingly

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#63]
We now detect high-level bioprocesses (ex. "apoptosis"), but they haven't been fully integrated into our existing grammars and taxonomy.

**Comment by myedibleenso** [comment]
@MihaiSurdeanu: I have this change integrated into the taxonomy, but I don't see an entity rule for any `BioProcess` on `master`.  What is the label produced by the NER for these guys (ex. "apoptosis")?

**Comment by MihaiSurdeanu** [comment]
The label is BioProcess. And yes, we need a rule to capture the IOB annotations.
Thanks!
