### ISSUE TITLE
Add Verbose Text to Index Output

### ISSUE THREAD

**Issue by cannin** [clulab/reach#630]
Would it be possible to add the verbose-text used in the FRIES format to the index card format? Perhaps, it could be added as verbose_evidence. This is related to #612 
 
# Index Format
<img width="359" alt="Screen Shot 2019-06-06 at 7 30 10 PM" src="https://user-images.githubusercontent.com/790284/59072716-b207c580-8891-11e9-899d-83a887c4e997.png">

# FRIES Format 
<img width="486" alt="Screen Shot 2019-06-06 at 7 30 42 PM" src="https://user-images.githubusercontent.com/790284/59072722-b502b600-8891-11e9-80dc-697cedafbbe0.png">

**Comment by MihaiSurdeanu** [comment]
This is now fixed in master.
