### ISSUE TITLE
REACH crashes

### ISSUE THREAD

**Issue by guerrerosimonl** [clulab/reach#648]
Hi!

We have been using REACH within INDRA system from the sorgerlab. It has been working perfectly until a few days ago, when one of the commands started crashing, and I think it is a REACH problem, because the error has taken place when reading plain text with REACH. 

In some cases it works normally, but in some others it doesn't (it gets stuck and there is no output), like for example with this text:

_"Correlation between benzene and testosterone in workers exposed to urban pollution. Many studies have examined the effects of benzene on testosterone. The purpose of this study was to evaluate the possible correlation between the blood levels of benzene and the levels of testosterone. The study involved a group of 148 subjects. For every worker have been made out a blood sample for the evaluation of benzene and testosterone levels and an urine analysis for the evaluation of the levels of trans, trans-muconic acid and S-phenylmercapturic acid. We estimated the Pearson correlation coefficient between the variables in the sample and the urinary metabolites, age, length of service, gender, BMI. For the analysis of the major confounding factors it was performed a multiple linear regression. The Pearson correlation coefficiet showed: 1. a significant inverse correlation between the S-phenyl mercapturic acid and free testosterone; 2. a significant direct correlation between trans-trans muconic acid and BMI. After dividing the sample according to the median of blood benzene (161.0 ng / L), Pearson correlation coefficient showed a significant inverse correlation between the S-phenyl mercapturic acid and free testosterone in the group with values below this median. Our results, to be considered preliminary, suggest that occupational exposure to low levels of benzene, present in urban pollution, affect the blood levels of testosterone. These results need to be confirmed in future studies, with the eventual possibility of including more specific fertility tests."_ 

Can you check it out, please?

Thank you in advance,

Laura

**Comment by MihaiSurdeanu** [comment]
Thanks @guerrerosimonl!
I will take a look. But I am traveling for the next two weeks, so it might take a while.

**Comment by bgyori** [comment]
I believe there is some confusion between a local instance of REACH and the REACH web service instance. The _web service_ seems to be having some issues, including getting stuck on this text. But this text can otherwise be processed well with a local instance of REACH. I advised using a local instance of REACH for reading tasks: https://github.com/sorgerlab/indra/issues/1032

**Comment by MihaiSurdeanu** [comment]
So, should this be closed @bgyori ?
