### ISSUE TITLE
Exclude promoter binding as complex formation event

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#653]
There are many sentences of the form "A binds the B _promoter_". Here, a Binding event between A and B (implying physical interaction between two proteins) should not be extracted since promoter binding is a form of (possible) gene expression regulation.

To achieve this, `binding1b` should be changed to not allow an incoming `compound` edge from "promoter" on the second theme. Further, to handle "A binds the _promoter of_ B", "promoter" should not be allowed to be an incoming `nmod_of` to the second theme in `binding_syntax_23_verb`. I couldn't figure out the correct syntax to add these constraints and am therefore asking for help. I pushed two tests that should pass on the `no_promoter` branch: https://github.com/clulab/reach/blob/no_promoter/main/src/test/scala/org/clulab/reach/TestBindingEvents.scala#L476-L486

**Comment by MihaiSurdeanu** [comment]
Hi @bgyori,
You need a negative look around in the binding rule(s), which has the "(?! pattern)" form. 
Syntactic look arounds are described in section 4.4.3 (page 18) of this document:
https://arxiv.org/pdf/1509.07513.pdf

Can you please see if these work? If not, I'll take a look. Or bring in one of the Odin experts.

**Comment by bgyori** [comment]
Thanks, that was useful but in the end I realized that the solution was a bit simpler and opened a PR with the fix.
