### ISSUE TITLE
Relative path to resource files cause problems with JAR-based reading

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#658]
Context: One of the ways in which we use Reach is by creating a far JAR (using `sbt assembly`), putting it on the CLASSPATH, and then instantiating a Python-Java bridge to interact with Reach classes directly.

I noticed that the polarity classifier refers to resource files whose path is not correctly resolved in the context of a fat JAR. For instance, the logging output
```
12:24:40.842 [main] INFO  o.c.p.m.DeepLearningPolarityClassifier - Loading saved model main/src/main/resources/SavedLSTM_WideBound_u_tag
```
indicates that `SavedLSTM_WideBound_u_tag` is accessed from a relative path with respect to the Reach repository folder. This fails if the JAR file is invoked from any working folder other than this folder.

**Comment by MihaiSurdeanu** [comment]
Yes, this is a bug. @kwalcock: can you please fix this, by changing the model path to the value that is resource friendly? Basically, just `SavedLSTM_WideBound_u_tag`
Thanks!

**Comment by bgyori** [comment]
Thanks! Note that there are other files that would need a similar change, e.g., SentencesInfo_all_label_final_ExactRecur_ExpandBound.txt, perhaps more.

**Comment by kwalcock** [comment]
I saw this and it is gradually getting to the top of the list.

**Comment by kwalcock** [comment]
If I understand it correctly, a change to the value in the config file won't be enough.  There is code like
```scala
Files.exists(Paths.get(savedModelPath)
```
that looks for a file rather than a resource.  If Ben has used `sbt assembly`, there is no more file, unless he copies from the source code and puts it relative to the pwd/cwd at runtime so that it is found.  The next step is
```scala
val modelLoader = new ModelLoader(savedModelPath)
```
which has the Java dynet call the C++ dynet to load the model.  This can only work from a files as well unless the FatDynet additions are used.  I *think* even that on Windows the filename must be suitable for C++ with backslashes.

The spreadsheet has similar issues.  Is it expected to be a file
```scala
val bufferedSource = Source.fromFile(spreadsheet_path)
```
which isn't going to work from an assembled jar.  This can be fixed with a `Source.fromResource` and a change in the confuration file to

```
spreadsheetPath = SentencesInfo_all_label_final_ExactRecur_ExpandBound_universal.txt
 ```
 as you mentioned, possibly with a /.

So, I would need to update the fatdynet to a version that includes zip support to get the model from the jar and change code in a couple of places.

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please address this issue?
Thank you!

**Comment by kwalcock** [comment]
Yes.  Are those slightly more invasive changes acceptable?

**Comment by MihaiSurdeanu** [comment]
I think so. Thanks!

**Comment by kwalcock** [comment]
It's at the top of the list now.

**Comment by kwalcock** [comment]
Just for the record, I'm reading the model and writing it out as a test.  The model changes ever so slightly in the process:
```
919615c919615
< +1.02539063e-02
---
> +1.02539062e-02
1069503c1069503
< -6.10351563e-04
---
> -6.10351562e-04
```
I have not noticed this behavior before.  Now it's at least written down.

**Comment by kwalcock** [comment]
This is being addressed with #660.

**Comment by bgyori** [comment]
Thank you so much for looking into this! I am just in the process of testing this, and it appears that the specific problem related to the polarity classifier models has been fixed. However, I am still running into an error when invoking the JAR file is from any working folder other than the Reach  repo folder. I am trying to figure out what the specific issue is and will post it here.

**Comment by kwalcock** [comment]
Stranger things have happened.  Let me know how I can help.

**Comment by bgyori** [comment]
It took me a while but I figured out how to reproduce the error I mentioned above without going through INDRA. On the latest master, if you do `sbt assembly`, you get `<reach_repo>/target/scala-2.11/reach-1.5.2-SNAPSHOT-FAT.jar`. Now navigate to any folder other than `<reach_repo>`, and do
```
java -cp <reach_repo>/target/scala-2.11/reach-1.5.2-SNAPSHOT-FAT.jar org.clulab.reach.export.server.ApiServer
```
and send a request on the api/text endpoint to read some text. I get the following error:
```
15:40:40.825 [apiserver-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
15:40:41.312 [apiserver-akka.actor.default-dispatcher-4] INFO  o.c.reach.export.server.ApiService - Server timeout: 5 minutes, Upload timeout: 2 minutes
15:40:41.313 [apiserver-akka.actor.default-dispatcher-4] INFO  o.c.reach.export.server.ApiService - Server online at http://localhost:8081
15:40:46.566 [apiserver-akka.actor.default-dispatcher-6] INFO  o.c.reach.export.server.ApiService - POST api/text -> SRF induces TAZ transcription., fries
[dynet] random seed: 3016767661
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
15:40:46.749 [apiserver-akka.actor.default-dispatcher-3] INFO  o.c.p.m.DeepLearningPolarityClassifier - Making vocabulary for deep learning model ...
15:40:46.749 [apiserver-akka.actor.default-dispatcher-3] INFO  o.c.p.m.DeepLearningPolarityClassifier - Loading data from spreadsheet ...
Uncaught error from thread [apiserver-akka.actor.default-dispatcher-3]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[apiserver]
java.lang.ExceptionInInitializerError
	at org.clulab.reach.export.server.ApiImpl$class.doText(ApiServer.scala:55)
	at org.clulab.reach.export.server.ApiService.doText(ApiServer.scala:99)
	at org.clulab.reach.export.server.ApiService$$anonfun$3$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(ApiServer.scala:222)
...
The same error doesn't happen when I launch the server from `<reach_repo>` indicating that it could be a relative path problem.

**Comment by kwalcock** [comment]
Thanks, @bgyori.  I didn't try the ApiServer and so will now.

**Comment by bgyori** [comment]
I don't think it's specific to the ApiServer - you can probably reproduce this with other entry points of Reach. I just thought that was relatively easy to work with.

**Comment by kwalcock** [comment]
Thanks for the tip.  I do get errors when running ApiServer.  For me they have to do with a different part of the configuration,
```
experimentalRegulation{
  keywords = main/src/main/resources/experimental_regulation_type_keywords.csv
}
```
which I hadn't addressed.  So hopefully we're looking at the same problem.

**Comment by kwalcock** [comment]
The branch just PRed as #661, kwalcock-ResourceAccess, should fix the problem.  It will probably be merged shortly.

**Comment by bgyori** [comment]
Just tested it and it now appears to work! Thank you!
