### ISSUE TITLE
Unnecessary code in DeepLearningPolarityClassifier

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#663]
This method gets called when the polarity classifier is used in Reach:
https://github.com/clulab/reach/blob/master/main/src/main/scala/org/clulab/polarity/ml/DeepLearningPolarityClassifier.scala#L523

It should not be called, as it has no impact at runtime.

**Comment by zhengzhongliang** [comment]
Hi Professor,
I think this function is called only when we instantiate it, so it is loaded when we start Reach, and will not be loaded for each sample (but please correct me if I am wrong). And as for usefulness, I think every time I load the model, I use the spreadsheet to build the vocabulary. But let me check if I am wrong.

**Comment by MihaiSurdeanu** [comment]
You are right that this method is called only at initialization. BUT, it is bad practice to construct the vocabularies at runtime. Vocabularies and other meta data you need should be constructed during training and saved then. At runtime, you should simply load them from the saved files.
See, for example, how this is done in processors:

Meta data is stored in the corresponding objects:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/sequences/LstmCrfMtl.scala#L374

It is saved when training is done:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/sequences/LstmCrfMtl.scala#L430

And it is loaded at runtime:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/sequences/LstmCrfMtl.scala#L453

(As you can see, I use a .x2i file to store all this meta data)
This is a better strategy for two reasons:
1. For some tasks, the vocabularies are very large and it is expensive to construct them at runtime.
2. More importantly, somebody may modify your spreadsheet, and your vocabulary becomes different from what was used in the model. A small change like that may completely break your model.

**Comment by zhengzhongliang** [comment]
Hi Professor,
Thanks for the suggestions and the examples. I saved the word to index map and the character to index map to two txt files in the resource folder, so that they are loaded at runtime. I created a new branch to clean this and I will send a pull request.

Best regards,
Zhengzhong
