### ISSUE TITLE
Double checking Family resolution

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#664]
Hi Ben,
This may be a non issue, but I'd like to check that it is Ok that the entities commented out in this test block are no longer Family:

https://github.com/clulab/reach/blob/proc800/main/src/test/scala/org/clulab/reach/TestFamilyResolutions.scala#L229

Thanks!

**Comment by bgyori** [comment]
The ones with underscores were a very old artifact, obviously those are not valid lexicalizations, so those can be deleted, e.g.:
//(bePF.resolve("IKK_family")) should be (defined)
 However, at least one example I looked at that is currently uncommented should work:
//(bePF.resolve("death receptor")) should be (defined)

**Comment by MihaiSurdeanu** [comment]
Thanks!

Where is "death receptor" defined now in bioresources?

**Comment by bgyori** [comment]
Locally, I have it on line 1301 of famplex.tsv. I couldn't find it in any of the other tsv-s, so I believe it should resolve to FamPlex without an override.

**Comment by MihaiSurdeanu** [comment]
Ok, thanks!

I'll look at this next.
Other than this issue, processors + bioresources have been released. Reach has been modified to depend only minimally on processors. For most changes, we will have to modify only bioresources and reach. All unit tests pass. This is all in the "proc800" branch. I will merge it in master once I fix this issue.

Thanks for all the help!!

**Comment by MihaiSurdeanu** [comment]
False alarm. "death receptor" is recognized correctly.
I added back a unit for this.
