### ISSUE TITLE
assembly subproject still needed?

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/reach#666]
@myedibleenso : are you still using the assembly subproject here? If not, should we remove it? I'd like to begin streamlining reach, and this is a subproject that might have a single user...

**Comment by myedibleenso** [comment]
Thanks for letting me know.  I certainly don't to place the burden of maintaining unused code on the future of the project.  This why I had originally created `assembly` as a standalone project.

Considering the amount of time I spent on it, though, I should be the one to put the pillow to its lips and usher it into oblivion.  

I've forked reach, and I'll put in a PR to resolve this.

**Comment by MihaiSurdeanu** [comment]
Thanks!

The pipes are singing in the background.

**Comment by myedibleenso** [comment]
btw, I'm honored this is issue 666! 👿
