### ISSUE TITLE
FamPlex with incorrect keys in xrefs

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#671]
It appears that there is an issue with how I integrated the recent update for FamPlex in Bioresources. For instance, in the fries output, "MEK" appears as
```
      "xrefs" : [ {
        "namespace" : "family",
        "species" : "fplx",
        "object-type" : "db-reference",
        "id" : "MEK"
      } ],
```
Here, "namespace" should be "fplx", and I don't think "family" should appear as a value under xrefs. Also, I now realize that "species" is not necessary for FamPlex entries (that is something I remember adding so I can revert that). "id" and "object-type" are correct.

**Comment by MihaiSurdeanu** [comment]
I see. Do you want to fix it? I can release it then.

**Comment by bgyori** [comment]
Yes, I'll look at this tomorrow
