### ISSUE TITLE
Extending PTM rules

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#69]
We need to extend PTM coverage to include relative clauses (that, when, etc). 

Examples (and description of desired behavior):
- "Src tyrosyl phosphorylates Ras that is ubiquitinated."
  - `theme` of `Phosphorylation` `EventMention` should have `PTM` with the label `Ubiquitination`
- "Src tyrosyl phosphorylates Ras that was previously ubiquitinated."
  - `theme` of `Phosphorylation` `EventMention` should have `PTM` with the label `Ubiquitination`
- "KEAP1 interacts with endogenous WTX that is phosphorylated at serine 286."
  - "endogenous WTX" `theme` of `Binding` `EventMention` should have `PTM` with the label `Phosphorylation` and Site `serine 286`

Requirements:
- A PTM rule should only match when a `cause` isn't present. 
  - This is to avoid capturing something like a `Regulation` containing a `Phosphorylation` of a phosphorylated entity.
- Tests!

**Comment by myedibleenso** [comment]
We probably want to include other relativizers (i.e., not just "that").  @danebell, can we continue the conversation started on your last PR here?  

@danebell had suggested that "when" might be dangerous, but "which" seemed safe.  Can we think of some scenarios where "when" is safe (or, conversely, scenarios where it definitely is not)?

**Comment by danebell** [comment]
Definitely safe:

- "When Ras is ubiquitinated, it binds WTX."
- "When ubiquitinated, Ras binds WTX."
- "Ras binds WTX when ubiquitinated." (cf. "Bob drinks tea when hot." -- Bob must be hot, not the tea)

Probably safe:

- "Ras binds WTX when they are ubiquitinated."
- "Ras binds WTX when each is ubiquitinated."
- "Ras binds WTX when both are ubiquitinated."

Unsafe:

- "WTX binds Ras when it is ubiquitinated."

**Comment by myedibleenso** [comment]
> "WTX binds Ras when it is ubiquitinated."

@danebell, I'm curious...what would coref do with this example?

**Comment by danebell** [comment]
It searches left-to-right within a sentence, so _it_ would get linked to _WTX_

**Comment by danebell** [comment]
To be clear, it would **not** apply a PTM to the WTX participant of the binding

**Comment by myedibleenso** [comment]
>To be clear, it would not apply a PTM to the WTX participant of the binding

Do you think we should avoid attempting resolution in this kind of case since it is unreliable?

In the safer examples you provided, do you intend to link the PTM to the antecedent?

**Comment by danebell** [comment]
> Do you think we should avoid attempting resolution in this kind of case since it is unreliable?

I'd definitely be willing to entertain the possibility, but I'm not sure how to detect this kind of ambiguity in the general case.

> In the safer examples you provided, do you intend to link the PTM to the antecedent?

This is a good idea. I'd like to figure out how to do that, although it might be better to put it farther down the priority list until after the dry-run and the LREC deadline, since it'll be more complicated than writing a rule.

**Comment by myedibleenso** [comment]
We will (eventually) need to link those features for assembly.  Where it should happen, I don't know, but I think it should be wherever it is easiest to do so.  

It's unclear if we will need to do this for the dry run or not, but Winter Is Coming.

**Comment by danebell** [comment]
Testing my prediction of coref's behavior shows that we actually get a ubiquitination of both, once by a direct rule and once through coref.

```
events:
mention text: WTX binds Ras
List(Binding, SimpleEvent, Event, PossibleController)
	------------------------------
	Rule => binding1b
	Type => CorefEventMention
	------------------------------
	------------------------------
	trigger => binds
	theme (List(Gene_or_gene_product, MacroMolecule, BioChemicalEntity, Entity, PossibleController)) => WTX
	theme (List(Family, BioChemicalEntity, Entity, PossibleController)) => Ras
	------------------------------

mention text: Ras when it is ubiquitinated
List(Ubiquitination, SimpleEvent, Event, PossibleController)
	------------------------------
	Rule => Ubiquitination_syntax_6_verb
	Type => CorefEventMention
	------------------------------
	------------------------------
	trigger => ubiquitinated
	theme (List(Family, BioChemicalEntity, Entity, PossibleController)) => Ras
	------------------------------

mention text: it is ubiquitinated
List(Ubiquitination, SimpleEvent, Event, PossibleController)
	------------------------------
	Rule => Ubiquitination_syntax_2_verb, pronominalMatch
	Type => CorefEventMention
	------------------------------
	------------------------------
	trigger => ubiquitinated
	theme (List(Gene_or_gene_product, MacroMolecule, BioChemicalEntity, Entity, PossibleController)) => WTX
	------------------------------
```

**Comment by myedibleenso** [comment]
Good, but transferring the PTM will give us precedence information on these reactions.

**Comment by danebell** [comment]
I agree, but is Coref the place to do that? This seems like something recoverable the same way that all the other PTMs will get transferred by precedence. All you have to do is check the antecedents as well.
