### ISSUE TITLE
Maintenance issues

### ISSUE THREAD

**Issue by kwalcock** [clulab/reach#695]
* sbt and plugins need to be updated
  * there's a branch kwalcock-updateSbt in waiting for this
* possibly account for Java 11, the default for newer Ubuntu releases
  * just one compilation problem was noted so far and addressed with kwalcock-updateSbtJava11
* make the correction in proonto branch
  * this is done
* remove CR/LF from github
  * this is on bioresources, but the code that generates them is here
* figure out what is happening in ner_kb.sh that prevents the model from being updated on the first pass
  * instructions and shell scripts have been updated
* update to the most recent version of processors
  * this seems to be causing an error

**Comment by MihaiSurdeanu** [comment]
Awesome. Thank you!

**Comment by kwalcock** [comment]
All the issues above except the last have been solved.  The last one causes an error in export/test TestApi.scala.  the positive activation only gets 7 of the 9.
```scala
  it should "return 9 positive activation and 3 phosphorylation results from NXML test" in {
    val results = Api.runOnNxml(nxmlText)
    results.filter(_.label == "Positive_activation") should have size (9)
    results.filter(_.label == "Phosphorylation") should have size (3)
  }
```
```
[info] - should return 9 positive activation and 3 phosphorylation results from NXML test *** FAILED *** (4 seconds, 873 milliseconds)
[info]   Vector(org.clulab.reach.mentions.CorefEventMention@ed6620fa, org.clulab.reach.mentions.CorefEventMention@1aa155ea, org.clulab.reach.mentions.CorefEventMention@15fde8d6, org.clulab.reach.mentions.CorefEventMention@f71c0834, org.clulab.reach.mentions.CorefEventMention@32c124b2, org.clulab.reach.mentions.CorefEventMention@efacda5c, org.clulab.reach.mentions.CorefEventMention@31d5ece8) had size 7 instead of expected size 9 (TestApi.scala:124)
```
I will try to provide details tomorrow.

**Comment by kwalcock** [comment]
Recent changes, probably to reach, result in the following results being now missing from the new version so that the test fails:
```
26: mM
Simple_chemical, BioChemicalEntity, BioEntity, Entity, PossibleController

40: mM
Simple_chemical, BioChemicalEntity, BioEntity, Entity, PossibleController

60: mM nickel in the presence of fibrinogen induced platelet aggregation
Positive_activation, ActivationEvent, ComplexEvent, Event, PossibleController

64: nickel in the presence of fibrinogen induced platelet aggregation (independently of protein kinase C activation
Positive_activation, ActivationEvent, ComplexEvent, Event, PossibleController
```
There's also a case where the "mM' is now missing in the text of the mention, but it doesn't cause a problem with the test.
```
63: mM nickel in the presence of fibrinogen induced platelet aggregation (independently of protein kinase C activation
Positive_activation, ActivationEvent, ComplexEvent, Event, PossibleController
```

**Comment by MihaiSurdeanu** [comment]
@bgyori : I think these are also side effects of you (correctly) removing 2-character entities?

**Comment by bgyori** [comment]
Yes `mM` stands for micro-molar, a unit, not a named physical entity, and so this is actually a good change!

**Comment by kwalcock** [comment]
Thanks, both.  It sounds like 60 and 63 which had Positive_activation before but aren't found any longer, should have been there anyway and I should have the test check for 7 rather than 9 Positive_activation instances.

**Comment by MihaiSurdeanu** [comment]
Yep. Thanks!


On October 15, 2020 at 1:01:50 PM, Keith Alcock (notifications@github.com)
wrote:

Thanks, both. It sounds like 60 and 63 which had Positive_activation before
but aren't found any longer, should have been there anyway and I should
have the test check for 7 rather than 9 Positive_activation instances.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/reach/issues/695#issuecomment-709495772>, or
unsubscribe
