### ISSUE TITLE
Two tests failing on master (TestDeterministicPolicies)

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#70]
I'm getting these two failures on `master` (true of `7ee0e47c242526a4ac273f9fc88fb6eaeff6351a`, but possibly an older issue):

```
[info] + Testing bounding padding context
[info] - should not extend an existing context more than 5 times *** FAILED *** (3 milliseconds)
[info]   6 was not less than or equal to 5 (TestDeterministicPolicies.scala:92)
[info] + Testing bidirectional bounding padding context
[info] - should not extend an existing context more than 10 times in both directions *** FAILED *** (2 milliseconds)
[info]   11 was not less than or equal to 10 (TestDeterministicPolicies.scala:131)
```

Any idea why this would break, @enoriega?  @danebell, did all of the tests pass before the merge?

**Comment by myedibleenso** [comment]
Well, I ran an earlier version of `master` (`ffb60a14b822060af06a9318cfd2223d604751de`) and both these tests passed.  @danebell, somehow adding that rule seems to have broken the @enoriega's tests.

**Comment by myedibleenso** [comment]
@enoriega, any idea why adding a binding rule would break those tests?  I don't think I understand enough of what's happening in context to speculate here.

**Comment by MihaiSurdeanu** [comment]
Gus, thanks for following up!

**Comment by myedibleenso** [comment]
Can someone else please confirm that the tests were passing on `ffb60a14b822060af06a9318cfd2223d604751de`?

https://github.com/clulab/reach/compare/ffb60a14b822060af06a9318cfd2223d604751de...master

**Comment by danebell** [comment]
Confirmed: all tests pass on `ffb60a14b822060af06a9318cfd2223d604751de`.

**Comment by enoriega** [comment]
I just ran the context tests in the master branch and they all pass. @myedibleenso, could you give me more details to try to replicate the bug? Did you remove the rule that presumably broke context?

**Comment by danebell** [comment]
Did you pull first, @enoriega? The tests that are failing for us are:

```
[info] + Testing bounding padding context 
[info] - should not extend an existing context more than 5 times *** FAILED *** (13 milliseconds)
[info]   6 was not less than or equal to 5 (TestDeterministicPolicies.scala:92)
[info] + Testing bidirectional bounding padding context 
[info] - should not extend an existing context more than 10 times in both directions *** FAILED *** (1 millisecond)
[info]   11 was not less than or equal to 10 (TestDeterministicPolicies.scala:131)
```

**Comment by enoriega** [comment]
I did a clean clone of master

**Comment by danebell** [comment]
And processors?

**Comment by myedibleenso** [comment]
@enoriega, how about on `7ee0e47c242526a4ac273f9fc88fb6eaeff6351a`?  A pull request was merged last night, so the newest version has changed.  I will run the latest version and let you know if I observe the same failures.  

Are the tests in question at all dependent on the output of Odin rules?  I'm just trying to understand what could be happening here...

**Comment by myedibleenso** [comment]
Is it possible that some of these context entities are being grounded differently between runs?  That might explain things, no?

**Comment by myedibleenso** [comment]
@hickst, are you grounding Mentions with the label "Context" in any special way?

**Comment by enoriega** [comment]
@danebell processors gets downloaded from maven. I'm running now the tests on `7ee0e47c242526a4ac273f9fc88fb6eaeff6351a` and see how it goes

**Comment by myedibleenso** [comment]
I just ran on the latest commit, and I'm still getting those failures.  I'm running on a fresh clone now as well, but the tests haven't yet finished running.

**Comment by myedibleenso** [comment]
At least in the run that just completed all tests pass on `fed872f766976785cfe7718676923003bf47415a` with a fresh clone.

**Comment by enoriega** [comment]
Context tests pass on `7ee0e47c242526a4ac273f9fc88fb6eaeff6351a`

**Comment by enoriega** [comment]
All tests pass on the master branch and on `7ee0e47c242526a4ac273f9fc88fb6eaeff6351a` for me. Any other idea on how to replicate the bug?

**Comment by myedibleenso** [comment]
I'm trying to reproduce this (running the full suite v. just TestDeterministicPolicies).  I'll let you know in a bit.  If I/we can't, I'll close the issue.  Thanks!

**Comment by myedibleenso** [comment]
Well, I guess @danebell and will need fresh copies.  @marcovzla was able to simple pull and run the tests without any problems.
