### ISSUE TITLE
Reach release does not look right

### ISSUE THREAD

**Issue by kwalcock** [clulab/reach#709]
I tried to publish reach, using the usual "sbt release" and was surprised to see some output on the screen that seemed to mean that  a snapshot version was being published.  The screen at sonatype seems to confirm that's what happened, not just now but also for the previous release.  It seems like we recently started trying to release versions for both Scala 2.11 and 2.12.  Another screen makes it look like that didn't work.  Another site seems to think that version 1.6.0 is missing for both versions of Scala.  Something seems to have been going wrong.  We were using quite old versions of the plugins before.  Updating them alone didn't seem to help.  I'm putting this here in case anyone else has insights before I start to investigate.

![image](https://user-images.githubusercontent.com/8679738/96529413-eb986100-1239-11eb-87e6-26cc4ef04c7b.png)
![image](https://user-images.githubusercontent.com/8679738/96529541-4cc03480-123a-11eb-946e-9335aa1549ff.png)
![image](https://user-images.githubusercontent.com/8679738/96529731-c9531300-123a-11eb-83a2-f897ad6862c0.png)

**Comment by MihaiSurdeanu** [comment]
Hmm... It's possible I screwed up the release of 1.6.0...
And it looks like 1.6.1 never happened. Based on the CHANGES file, all changes in 1.6.1 should be 1.6.2, no?

And unfortunately, I have no idea why we're releasing snapshots...

**Comment by MihaiSurdeanu** [comment]
But it looks like the release process in processors is very different:

```
releaseProcess := Seq[ReleaseStep](
  checkSnapshotDependencies,
  inquireVersions,
  runClean,
  runTest,
  setReleaseVersion,
  ReleaseStep(action = Command.process("+publishSigned", _)),
  ReleaseStep(action = Command.process("sonatypeReleaseAll", _)),
  commitReleaseVersion,
  tagRelease,
  setNextVersion,
  commitNextVersion,
  pushChanges
)
```

**Comment by MihaiSurdeanu** [comment]
The above one is reach. The one in processors is:

```
releaseProcess := Seq[ReleaseStep](
  checkSnapshotDependencies,
  inquireVersions,
  runClean,
  runTest,
  setReleaseVersion,
  commitReleaseVersion,
  tagRelease,
  releaseStepCommandAndRemaining("+publishSigned"),
  setNextVersion,
  commitNextVersion,
  releaseStepCommandAndRemaining("sonatypeReleaseAll"),
  pushChanges
)
```

**Comment by kwalcock** [comment]
An update of build.sbt seemed to do the trick.  Is it important to release a version 1.6.0 that was intended back in May?

![image](https://user-images.githubusercontent.com/8679738/96546417-121cc300-125f-11eb-969d-8916203be5de.png)

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
No, it's not important to release 1.6.0.
