### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by sateeshperi** [clulab/reach#713]
I am trying to run the FAT jar of reach on HPC and get the following error. It works fine on VM where I assemble the fat jar.	

	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class edu.cmu.dynet.internal.dynet_swigJNI
			... 35 more
			Suppressed: java.lang.UnsatisfiedLinkError: /tmp/dynet816865678061882470.dll: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/dynet816865678061882470.dll)

**Comment by kwalcock** [comment]
Here is an old email I have about that error.  I haven't closely followed the updates on UA's HPCs to know whether simply moving to the other one would solve it or not (if there still are two).  A docker container could provide the necessary version if necessary.

```
The HPCs have El Gato and Ocelote with different versions of their
operating systems.  Ocelote's is older, despite seeming to be a newer
machine, and its version of CLIBC was too old for fatdynet.  Fan moved
to El Gato and the program ran without change.  She wasn't in a
container, though.  If a container is involved, it may be supplying
GLIBC.  I went back as far as Ubuntu 14 when building fatdynet, but if
it continues to be a problem, I could try for earlier.
```

**Comment by sateeshperi** [comment]
The `El Gato` and `Puma` compute nodes have no `java/8/` module available for executing the fat jar. 

I tried installing `glibc` as per the instructions [here](https://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5) but, was unsuccessful

please see my notebook with error logs [Here](https://github.com/sateeshperi/reach_pubmed/blob/main/PubmedReach.ipynb)

**Comment by kwalcock** [comment]
The unavailability of Java on El Gato may not be accurate.  It *seems* to be preinstalled and I'm fairly sure this was the machine we've run on before.

```sh
[kalcock@gpu64 Projects]$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```

```sh
[kalcock@gpu64 Projects]$ ldd libdynet_swig.so 
	linux-vdso.so.1 =>  (0x00007ffc22d84000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fed43184000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fed42e82000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fed42c6c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fed4289e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fed43da2000)
```

**Comment by MihaiSurdeanu** [comment]
Thanks Keith!

**Comment by kwalcock** [comment]
https://public.confluence.arizona.edu/display/UAHPC/Software+Resources says that Puma has Java pre-installed, but it doesn't say which version.  Have you checked it out?

**Comment by sateeshperi** [comment]
Thank you @kwalcock I can confirm java8 is pre-installed on `elgato` and `puma` and it works now.
