### ISSUE TITLE
cannot run javac

### ISSUE THREAD

**Issue by sateeshperi** [clulab/reach#729]
[error] (processors / Compile / compileIncremental) java.io.IOException: Cannot run program "javac" (in directory "/xdisk/sateesh/reach"): error=2, No such file or directory

**Comment by enoriega** [comment]
I think there is a problem in the configuration of your environment. I assume you're trying to run on the HPC. 
Have you tried running `module load java/1.8` in your script before calling `sbt`?

**Comment by sateeshperi** [comment]
hi @enoriega this is the jdk available on the node
```java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)```

**Comment by enoriega** [comment]
Thinking about it, you shouldn't need to compile reach in the HPC.  Please try building a "fatjar" in your work station by running: `sbt assembly`

Then upload it to the HPC and run

```bash
$ java -jar reach-1.6.3-SNAPSHOT-FAT.jar 
```
