### ISSUE TITLE
Update Wiki with latest updates

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#731]
Some of the wiki pages in this repo are out of date. For example, https://github.com/clulab/reach/wiki/Running-REACH still makes reference to the processors server, which has been removed now. 

Go through the pages and remove or update outdated information as necessary

**Comment by kwalcock** [comment]
See also #712.  The readme file also has problems.

**Comment by enoriega** [comment]
I went through the wiki pages and updated them where it seemed appropriate. I also looked at the README.md file and made a slight change.
