### ISSUE TITLE
Change the Odin BIO rules: if it ends with "family", etc. label as Family instead of Protein.

### ISSUE THREAD

**Issue by hickst** [clulab/reach#74]
Since grounding now dispatches on head label, the bio rules should recognize, and set the appropriate label, for the special cases:

XXX protein family
XXX family

Once rules are enhanced, grounding code will be updated to remove the several special cases.

**Comment by MihaiSurdeanu** [comment]
No, we discussed this. Ideally, we should never label these phrases as proteins because they are not: only the XXX part should be labeled. However, the CRF often mistakes the span of an entity phrase, including these common nouns as well. This is harder to fix, so we should just address this in grounding.

**Comment by hickst** [comment]
I'm confused....I remember discussing this but I remember we decided to modify the bio rules for it AND your current TODO list says"
"- change the Odin BIO rules: if it ends with "family", etc. label as Family instead of Protein. - GUS, TOM"

**Comment by MihaiSurdeanu** [comment]
Sorry, I misinterpreted this issue. I thought you wanted to add new rules. This is about changing existing rule for the IOB Gene_or_gene_product wrapper rule: if the span contains "family" label as Family instead.

**Comment by hickst** [comment]
Yes, I think that's a good statement of the issue. Sorry for the confusion.

**Comment by myedibleenso** [comment]
I'll change those rules.  @hickst, do you have any examples of any strings that are consistently being detected a GGP or Family?  This will help for writing tests.

**Comment by myedibleenso** [comment]
Following the plan from today's discussion, I'll manipulate the entity tags to test this feature.

**Comment by hickst** [comment]
Sorry, I don't have any examples on hand. My previous tests used made up examples since this is very simple. If you need to use real examples, it may just be a matter of searching recent results for "family" or "protein family" and then seeing if the label is GGP. Here are many recent FRIES results:
/net/kate/storage/data/nlp/corpora/pmc_openaccess/darpa_eval_dec2015/fries_160120

**Comment by myedibleenso** [comment]
I don't think we need to use anything real.  I just didn't think about manipulating the contents of the `entities` array.  That's really all that's necessary for testing this tweak.  

It seems to work:
```scala
  // test lookahead assertions on ner rules for GGP and Family entities
  val mekText = "the MEK family"
  mekText should "contain 1 Family entity for \"MEK\" even if the entity tag is B-Gene_or_gene_product" in {
    val doc = bioproc.annotate(mekText)
    val ggpLabels: Array[String] = Array("O", "B-Gene_or_gene_product", "O")
    // manipulate the document for this test
    doc.id = Some("MEK-test")
    doc.text = Some(mekText)
    doc.sentences.head.entities = Some(ggpLabels)
    val mentions = testReach.extractFrom(doc)
    mentions should have size (1)
    mentions.head matches "Family" should be (true)
  }
```

**Comment by hickst** [comment]
I still need to check, and possibly cleanup, grounding code related to this change.

**Comment by hickst** [comment]
This change to the biorule doesn't seem to handle the "XXX protein family" case. Can we lookahead either one or two lemmas (i.e., for either "family" or "protein family"?

**Comment by myedibleenso** [comment]
Oh, good point.  I hadn't considered that pattern.  I will make some adjustments and add another test.

**Comment by myedibleenso** [comment]
I've pushed an update addressing the issue you raised, @hickst.  Do you want to test against that before I put in a pull request?

**Comment by myedibleenso** [comment]
Here is the relevant commit: https://github.com/clulab/reach/commit/e1edfb9999ce6a89271a898cfae6ea8fe2a4b01a

You can find it on the `ner-rule-fixes` branch.
