### ISSUE TITLE
TestDeterministicPolicies fails when run as part of project tests

### ISSUE THREAD

**Issue by hickst** [clulab/reach#76]
I'm unable to get the TestDeterministicPolicies tests to pass when run as part of the entire test suite.
I've tried:
1) a fresh clone of the entire Reach project from GitHub. 
2) increasing memory to 16G when running the tests. 
3) deleting all sbt-created 'target' directories between runs.
4) removing the .sbtopts in reach home directory when running

Error messages in the output:
...
[info] + Testing bounding padding context
[info] - should not extend an existing context more than 5 times *** FAILED *** (9 milliseconds)
[info]   6 was not less than or equal to 5 (TestDeterministicPolicies.scala:92)
[info] + Testing bidirectional bounding padding context
[info] - should not extend an existing context more than 10 times in both directions *** FAILED *** (1 millisecond)
[info]   11 was not less than or equal to 10 (TestDeterministicPolicies.scala:131)
...

**Comment by hickst** [comment]
Important new data point: the test fails in the 'gsel' branch but not in the master branch.
Let's start with what this test was supposed to do and under what conditions would the test be violated?

**Comment by myedibleenso** [comment]
This may be related to #70...

**Comment by hickst** [comment]
Yes, sorry, I overlooked the previous, closed issue #70. This looks like exactly the same problem. I suggest the first step is that Enrique pull the 'gsel' branch and see if that replicates the failure for him.

**Comment by enoriega** [comment]
@Tom did you say the tests don't pass only if you run them along all the other suites?

**Comment by hickst** [comment]
Yes, that's correct, a quirk which I think was also reported in issue #70.

**Comment by enoriega** [comment]
Again the same, I can't replicate it. Any ideas on how to replicate it?

**Comment by hickst** [comment]
I just made a fresh clone of Reach on a Linux box (fedora), ran all tests on the master branch, and got the 'context ghost' bug again.

**Comment by enoriega** [comment]
Does this include the ReachCLI paper is related to the ghost?

**Comment by myedibleenso** [comment]
@enoriega: maybe you can explain what this test is doing and why it's doing it?  That might help us in figuring out how to reproduce it.

**Comment by enoriega** [comment]
It tests wether the context policy is padding the correct number of sentences for any given context mention. Imagine the document as a sequence of sentence where in sentence `x` a context mention shows up. The context engine sweeps the remaining sentences to make sure it's not padded more than `bound` times, where the bound in the case of the test is 5. Somehow this was exceeded by one line.

**Comment by myedibleenso** [comment]
Could it be that a mention on the other side of this boundary is getting labeled differently (the crf's output is nondeterministic) between runs.  Perhaps you're ending up with two sources of the same context meeting at where you expect you boundary to be.  Is that possible?

**Comment by enoriega** [comment]
Maybe, but none of the context mentions come from the CRF NER.

**Comment by MihaiSurdeanu** [comment]
The CRF output *is* deterministic...
Let's brainstorm tomorrow. Meanwhile, Enrique or Tom, can you find out
*how* it fails when it fails?

**Comment by myedibleenso** [comment]
closing this for now...
