### ISSUE TITLE
Installation Error When Attempting to make REACH Jar

### ISSUE THREAD

**Issue by compbiolover** [clulab/reach#773]
Hi @kwalcock,
I have tried to package REACH and its dependencies into a `JAR` by following the directions from here: https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html.
I have successfully installed `SBT` and `Java JDK version 8` but I am getting an error when running `sbt assembly`. It appears to be a bad gateway error with a couple of dependencies. I am attaching a screenshot of the terminal output. It looks like it is the `glove` and `processors` dependencies that are causing the issues. Let me know if I can provide any additional information.

-Andrew 

![Screen Shot 2022-08-26 at 19 15 05](https://user-images.githubusercontent.com/39838470/187002272-0bfa3fb4-054d-49c2-aaee-24cc2d121063.png)

**Comment by kwalcock** [comment]
Thanks for letting me know.  It looks like one (or more) of our servers is down.  We're looking into it and will report back.

**Comment by compbiolover** [comment]
No problem, @kwalcock. Will watch for your update.

**Comment by kwalcock** [comment]
@compbiolover, the server seems to be working again.  Thanks for your patience.
