### ISSUE TITLE
Error installing REACH with sbt.

### ISSUE THREAD

**Issue by Crispae** [clulab/reach#774]
I followed the steps mentioned in documentation:  

`git clone https://github.com/clulab/reach.git  
 cd reach  
 sbt 'runMain org.clulab.reach.export.server.ApiServer'`

Gettiing this error

<img width="440" alt="Screenshot 2022-10-27 122822" src="https://user-images.githubusercontent.com/74324530/198261517-67f07aea-17af-42a0-b8ee-279d77fa21a7.png">

**Comment by kwalcock** [comment]
Can you try that command with double quotes instead of single ones?  I don't see that step in the documentation.  Can you point me to it?  Thanks.

**Comment by Crispae** [comment]
> 



> Can you try that command with double quotes instead of single ones? I don't see that step in the documentation. Can you point me to it? Thanks.

I follow the steps mentioned in this documentation https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html. In this there are 4 steps.

I tried  **INDRA communicating with a locally running REACH Server**, on normal command line. It is giving error while in power shell it is working fine.

While i was trying the **INDRA using a REACH JAR through a Python-Java bridge**, using the command **sbt assembly** it is throwing new error
<img width="523" alt="Screenshot 2022-10-28 153813" src="https://user-images.githubusercontent.com/74324530/198616460-df674d16-dec9-46d1-8598-72570153dd57.png">

Although, i can successfully run the reach server with first method on power shell, but it would be better to look into why sbt assembly throwing error.

Thanks

**Comment by kwalcock** [comment]
That's strange.  I get a clean assembly.  There is code in `build.sbt` to take care of the conflicts.  Can you do a `git status` to check what you are working on?  That code has been in place since 4/9/2022.  Thanks.

**Comment by Crispae** [comment]
<img width="357" alt="Screenshot 2022-10-31 100938" src="https://user-images.githubusercontent.com/74324530/198972377-9c9e44e7-fd41-47d9-b6ee-abc4fde1d512.png">

This is up to date with current changes. May be environment variables are causing this issue?

**Comment by Crispae** [comment]
I added all my environment variables in path 
<img width="416" alt="Screenshot 2022-10-31 101239" src="https://user-images.githubusercontent.com/74324530/198973052-3936ed5e-2275-44d3-adfb-e009fef2a759.png">

**Comment by kwalcock** [comment]
What has changed in build.sbt?  To unchange it to match the current master branch, you would need to do `git restore build.sbt`.  It would be nice to know what the change is first: `git diff build.sbt`.

**Comment by kwalcock** [comment]
I don't see anything suspicious in the environment variables.  We generally use Java 8, but I don't think that's the problem.

**Comment by Crispae** [comment]
Assembly is working fine now, but still offline reading is not available. I already installed pyjnus.
<img width="762" alt="Screenshot 2022-11-02 111750" src="https://user-images.githubusercontent.com/74324530/199464494-f5890f71-3b2a-4f85-ab33-041a1c46d07b.png">

**Comment by kwalcock** [comment]
If you have advice for others on how to get assembly to work, I'm sure they'd appreciate it.

Given those error messages, I wouldn't trust that jnius is installed or configured correctly.  Is REACHPATH set, for example?  For questions that are more about INDRA than REACH, you might have better luck at https://github.com/sorgerlab/indra/issues.

**Comment by Crispae** [comment]
Sorry for late response. offline system work fine, in the process_pmc function no need to add offline parameter, In url just use api.local_nxml_url.
