### ISSUE TITLE
Possible NER bug

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#79]
Using `bioresources 1.1.1-SNAPSHOT` with the REACH Shell, `milk` gets labels as a CellType:

```
>>> milk
sentence #0
milk
Tokens: (0,milk,NN)
roots: 0
outgoing:
incoming:


entities:
mention text: milk
List(CellType, Context)
	------------------------------
	Rule => nee-cell-type
	Type => CorefTextBoundMention
	------------------------------
	CellType|List(CellType, Context) => milk
	grounding: KBResolution(milk, uaz, UAZ00001, )
	------------------------------


events:
==================================================
```
Inspecting the rule, it looks fine:

```
- name: ner-cell-type
  label: CellType
  action: mkNERMentions
  priority: 3
  type: token
  pattern: |
    [entity='B-CellType'] [entity='I-CellType']*
```

And inspecting `CellType.tsv.gz`, there's a single entry that contains _milk_:  `CellType.tsv.gz:First milk`.

Is it possible that the NER is tagging with `B-CellType` a token that is only a partial match of an entry in the file?

**Comment by enoriega** [comment]
This is causing spurious context mentions with CellType label

**Comment by MihaiSurdeanu** [comment]
This is a processors bug. I'll fix it.

**Comment by MihaiSurdeanu** [comment]
@enoriega: this might not be a bug. Milk does appear as a CellType:

[mihais@211 ~/github/bioresources (master)]$ grep -i milk ~/Desktop/CellType.tsv
First milk
Milk

**Comment by enoriega** [comment]
If it was the case, then there should be a grounding id for `Milk`

**Comment by hickst** [comment]
@mihai that's exactly the problem: Milk appears in the generated NER file but not in the original KB or in the grounding KB.

**Comment by MihaiSurdeanu** [comment]
"Milk" comes from the tissue-type KB:

[mihais@211 ~/github/bioresources (master)]$ grep -i milk ~/Desktop/tissue-type.tsv
First milk	TS-0167
Milk	TS-0636

**Comment by enoriega** [comment]
Ah, then I think the problem is that the file `tissue-type.tsv` is not listed in the grounding list for `CellType`

**Comment by MihaiSurdeanu** [comment]
Assigning to Tom.

**Comment by hickst** [comment]
Ah so...an out-of-sync problem. Thanks for finding that.

**Comment by hickst** [comment]
So, grounding has not been/is not using the tissue-type file. Should we be using this KB or should NER not use it?

**Comment by enoriega** [comment]
Removing it from NER would involve a new release of bioresouces, adding it only implies changes in REACH

**Comment by MihaiSurdeanu** [comment]
Either one is fine. But, if tissue-type has useful information, we should
keep it!

**Comment by enoriega** [comment]
A quick skim over that file makes me think it has useful info that must be curated before using it. It does have many cell types, as it is being labeled, but it also has organs: `Cornea  TS-0171`, `Embryonic skin`, `Eye     TS-0309`.

Maybe remove it while someone puts the entries in the file they belong (Organ.tsv, Cell_type.tv)

**Comment by MihaiSurdeanu** [comment]
Rereleased bioresources 1.1.1, which removes tissue-type from the NER. 
This fixes this issue.

**Comment by hickst** [comment]
IF we use it....since Grounding is now "label-dispatched", which label should cause grounding to search this KB for an ID?:

https://github.com/clulab/reach/blob/dc963d944d25239fa6bb7868853e1935a09ebe20/src/main/scala/edu/arizona/sista/reach/grounding/ReachEntityLookup.scala#L38-L53
