### ISSUE TITLE
Proposal to improve grounding (pXXX and XXX should be the same)

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#90]
I've noticed a pattern in the literature where the phosphorylated form of some entity is given as a lowercase *p* prefix to the entity's name.  If you look at [PMC3058384](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3058384/), one of our test papers, you'll see mentions of both ERK and its phosphorylated form, pERK.  It seems that grounding is mostly agnostic to case and so ends up assigning different IDs to these two strings.   

```
pERK expression

Protein|List(Gene_or_gene_product, MacroMolecule, BioChemicalEntity, BioEntity, Entity, PossibleController) => pERK
grounding: KBResolution(perk, uniprot, Q9NZJ5, homo sapiens)

ERK phosphorylation

Protein|List(Gene_or_gene_product, MacroMolecule, BioChemicalEntity, BioEntity, Entity, PossibleController) => ERK
grounding: KBResolution(erk, uniprot, P29323, homo sapiens)
```

Odin is not really designed for sub-token matching, so this is probably something that would need to be handled elsewhere.  We could, however, detect these as PTMs...

I am thinking we might want to check for the pXXX word shape, where X is 3 or more capital letters followed by 0 or more digits.  Probably there are additional PTMs using this pattern.   

For example, I would expect something like uXXX for ubiquitinated XXX, but we should confirm this with a biologist.  Here are some tokens matching that pattern:

```
uABC
uATG
uAUG
uCLEAR
uCRFB4
uDOS
uEGF
uEPO
uERV
uGEN
```

I tried to get a sense of how common this pattern is by running `grep -Poh "p[A-Z]{3,}[0-9]*" * | wc -l` over the 905 nxml files under `/data/nlp/corpora/pmc_openaccess/darpa_eval_dec2015_forSRI/nxml`

I found 3072 matches (498 unique according to `grep -Poh "p[A-Z]{3,}[0-9]*" * | sort | uniq | wc -l`).

Here are a few examples:

```
pSSSSSD
pSST91
pSTAT
pSTAT1
pSTAT3
pSTAT5
pSTAT6
pSTB
```

I am not sure if all (or any) of these are phosphorylated proteins (perhaps a GGP?), but it might be worth an email.

I'm thinking grounding could try a regex like this on mentions it receives. A match would mean stripping the leading lowercase character and performing a case-sensitive lookup on the remaining string.  

If grounding were to retrieve both candidate resolutions (i.e., the current id and whatever it comes up with when using the new lookup), we could have a resolution policy that prefers the resolution intersecting with the candidate resolutions belonging to other mentions in the same section of the paper (you're more likely to see mentions of an entity repeated in a given section of paper).

**Comment by MihaiSurdeanu** [comment]
Yes, definitely ask RGX!

**Comment by hickst** [comment]
Well except for the SSSSSD (a typo?) all the listed stems are found in our uniprot protein KB (uniprot also includes 69 SSD* proteins and 127 SSS*) so this analysis seems very plausible to me.

Some comments:
1) The grounding data is canonicalized when loaded (lowercased, removal of spaces, dashes, etc). Text strings are treated the same way upon lookup. This means there is no capability for 'case-insensitive' lookup.
2) We could, however, try a simpler algorithm: simply strip a leading 'p' or 'u' and re-lookup the remaining string in the protein KB.

**Comment by hickst** [comment]
Recent grounding (step1) enhancements allow us to test for a more specific pattern: pXyz where 'p' is lowercase only and 'Xyz' begins with uppercase letter. I think this may more accurately reflect the actual usage of this shorthand notation (e.g., pERK or uAkt1).

Should we implement this more restricted pattern?

**Comment by MihaiSurdeanu** [comment]
Yes.
Mihai

**Comment by myedibleenso** [comment]
Should this be closed?
