### ISSUE TITLE
Pluralize the Cellular Location files

### ISSUE THREAD

**Issue by enoriega** [clulab/reach#96]
Add plural forms for the files that correspond to the cellular location context type

**Comment by enoriega** [comment]
Done

**Comment by MihaiSurdeanu** [comment]
Should I release bioresources?

**Comment by enoriega** [comment]
Yes. I didn’t update the version number in build.sbt.

**Comment by MihaiSurdeanu** [comment]
That is fine. It's trivial to do.
However, in the future, please update the CHANGES.md file with a summary of the changes.
